{
//=========Macro generated from canvas: c_cross_section_variations_dispersion/c_cross_section_variations_dispersion
//=========  (Wed May 29 06:56:11 2019) by ROOT version5.34/30
   TCanvas *c_cross_section_variations_dispersion = new TCanvas("c_cross_section_variations_dispersion", "c_cross_section_variations_dispersion",0,64,1500,1000);
   gStyle->SetOptStat(0);
   c_cross_section_variations_dispersion->SetHighLightColor(2);
   c_cross_section_variations_dispersion->Range(0,0,1,1);
   c_cross_section_variations_dispersion->SetFillColor(10);
   c_cross_section_variations_dispersion->SetBorderMode(0);
   c_cross_section_variations_dispersion->SetBorderSize(2);
   c_cross_section_variations_dispersion->SetTickx(1);
   c_cross_section_variations_dispersion->SetTicky(1);
   c_cross_section_variations_dispersion->SetLeftMargin(0.135);
   c_cross_section_variations_dispersion->SetRightMargin(0.035);
   c_cross_section_variations_dispersion->SetTopMargin(0.03);
   c_cross_section_variations_dispersion->SetBottomMargin(0.125);
   c_cross_section_variations_dispersion->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_cross_section_variations_dispersion_1
   TPad *c_cross_section_variations_dispersion_1 = new TPad("c_cross_section_variations_dispersion_1", "c_cross_section_variations_dispersion_1",0.005,0.501,0.3283333,0.999);
   c_cross_section_variations_dispersion_1->Draw();
   c_cross_section_variations_dispersion_1->cd();
   c_cross_section_variations_dispersion_1->Range(-21.49473,-0.5991124,17.5866,4.193787);
   c_cross_section_variations_dispersion_1->SetFillColor(10);
   c_cross_section_variations_dispersion_1->SetBorderMode(0);
   c_cross_section_variations_dispersion_1->SetBorderSize(2);
   c_cross_section_variations_dispersion_1->SetTickx(1);
   c_cross_section_variations_dispersion_1->SetTicky(1);
   c_cross_section_variations_dispersion_1->SetLeftMargin(0.135);
   c_cross_section_variations_dispersion_1->SetRightMargin(0.035);
   c_cross_section_variations_dispersion_1->SetTopMargin(0.03);
   c_cross_section_variations_dispersion_1->SetBottomMargin(0.125);
   c_cross_section_variations_dispersion_1->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_1->SetFrameBorderMode(0);
   c_cross_section_variations_dispersion_1->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_1->SetFrameBorderMode(0);
   
   TH1F *hframe__45 = new TH1F("hframe__45","",1000,-16.21875,16.21875);
   hframe__45->SetMinimum(0);
   hframe__45->SetMaximum(4.05);
   hframe__45->SetDirectory(0);
   hframe__45->SetStats(0);
   hframe__45->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__45->GetXaxis()->SetNdivisions(506);
   hframe__45->GetXaxis()->SetLabelFont(43);
   hframe__45->GetXaxis()->SetLabelSize(24);
   hframe__45->GetXaxis()->SetTitleSize(24);
   hframe__45->GetXaxis()->SetTitleOffset(2.3);
   hframe__45->GetXaxis()->SetTitleFont(43);
   hframe__45->GetYaxis()->SetTitle("Entries");
   hframe__45->GetYaxis()->SetNdivisions(506);
   hframe__45->GetYaxis()->SetLabelFont(43);
   hframe__45->GetYaxis()->SetLabelSize(24);
   hframe__45->GetYaxis()->SetTitleSize(24);
   hframe__45->GetYaxis()->SetTitleOffset(2.8);
   hframe__45->GetYaxis()->SetTitleFont(43);
   hframe__45->GetZaxis()->SetLabelFont(43);
   hframe__45->GetZaxis()->SetLabelSize(24);
   hframe__45->GetZaxis()->SetTitleOffset(1.1);
   hframe__45->GetZaxis()->SetTitleFont(43);
   hframe__45->Draw(" ");
   
   TH1D *syst_sigma_long_sig_shift_dispersion = new TH1D("syst_sigma_long_sig_shift_dispersion","",1000,-75,75);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(445,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(463,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(468,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(477,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(479,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(481,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(487,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(492,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(499,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(500,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(522,3);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(547,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(553,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(571,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(577,1);
   syst_sigma_long_sig_shift_dispersion->SetBinContent(587,1);
   syst_sigma_long_sig_shift_dispersion->SetEntries(18);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift_dispersion->SetFillColor(ci);
   syst_sigma_long_sig_shift_dispersion->SetFillStyle(0);

   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift_dispersion->SetLineColor(ci);

   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift_dispersion->SetMarkerColor(ci);
   syst_sigma_long_sig_shift_dispersion->SetMarkerSize(1.1);
   syst_sigma_long_sig_shift_dispersion->GetXaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift_dispersion->GetXaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift_dispersion->GetXaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift_dispersion->GetXaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift_dispersion->GetYaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift_dispersion->GetYaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift_dispersion->GetYaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift_dispersion->GetYaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift_dispersion->GetZaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift_dispersion->GetZaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift_dispersion->GetZaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift_dispersion->GetZaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift_dispersion->Draw("histsame");
   TLatex *   tex = new TLatex(0.195,0.895,"Mean = 1.514 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.195,0.82,"RMS = 6.121 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.905,0.885,"Signal #sigma_{long}^{2} cut");
tex->SetNDC();
   tex->SetTextAlign(32);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__46 = new TH1F("hframe__46","",1000,-16.21875,16.21875);
   hframe__46->SetMinimum(0);
   hframe__46->SetMaximum(4.05);
   hframe__46->SetDirectory(0);
   hframe__46->SetStats(0);
   hframe__46->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__46->GetXaxis()->SetNdivisions(506);
   hframe__46->GetXaxis()->SetLabelFont(43);
   hframe__46->GetXaxis()->SetLabelSize(24);
   hframe__46->GetXaxis()->SetTitleSize(24);
   hframe__46->GetXaxis()->SetTitleOffset(2.3);
   hframe__46->GetXaxis()->SetTitleFont(43);
   hframe__46->GetYaxis()->SetTitle("Entries");
   hframe__46->GetYaxis()->SetNdivisions(506);
   hframe__46->GetYaxis()->SetLabelFont(43);
   hframe__46->GetYaxis()->SetLabelSize(24);
   hframe__46->GetYaxis()->SetTitleSize(24);
   hframe__46->GetYaxis()->SetTitleOffset(2.8);
   hframe__46->GetYaxis()->SetTitleFont(43);
   hframe__46->GetZaxis()->SetLabelFont(43);
   hframe__46->GetZaxis()->SetLabelSize(24);
   hframe__46->GetZaxis()->SetTitleOffset(1.1);
   hframe__46->GetZaxis()->SetTitleFont(43);
   hframe__46->Draw("sameaxis");
   c_cross_section_variations_dispersion_1->Modified();
   c_cross_section_variations_dispersion->cd();
  
// ------------>Primitives in pad: c_cross_section_variations_dispersion_2
   c_cross_section_variations_dispersion_2 = new TPad("c_cross_section_variations_dispersion_2", "c_cross_section_variations_dispersion_2",0.3383333,0.501,0.6616667,0.999);
   c_cross_section_variations_dispersion_2->Draw();
   c_cross_section_variations_dispersion_2->cd();
   c_cross_section_variations_dispersion_2->Range(-8.324548,-0.3994083,6.810994,2.795858);
   c_cross_section_variations_dispersion_2->SetFillColor(10);
   c_cross_section_variations_dispersion_2->SetBorderMode(0);
   c_cross_section_variations_dispersion_2->SetBorderSize(2);
   c_cross_section_variations_dispersion_2->SetTickx(1);
   c_cross_section_variations_dispersion_2->SetTicky(1);
   c_cross_section_variations_dispersion_2->SetLeftMargin(0.135);
   c_cross_section_variations_dispersion_2->SetRightMargin(0.035);
   c_cross_section_variations_dispersion_2->SetTopMargin(0.03);
   c_cross_section_variations_dispersion_2->SetBottomMargin(0.125);
   c_cross_section_variations_dispersion_2->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_2->SetFrameBorderMode(0);
   c_cross_section_variations_dispersion_2->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_2->SetFrameBorderMode(0);
   
   TH1F *hframe__47 = new TH1F("hframe__47","",1000,-6.28125,6.28125);
   hframe__47->SetMinimum(0);
   hframe__47->SetMaximum(2.7);
   hframe__47->SetDirectory(0);
   hframe__47->SetStats(0);
   hframe__47->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__47->GetXaxis()->SetNdivisions(506);
   hframe__47->GetXaxis()->SetLabelFont(43);
   hframe__47->GetXaxis()->SetLabelSize(24);
   hframe__47->GetXaxis()->SetTitleSize(24);
   hframe__47->GetXaxis()->SetTitleOffset(2.3);
   hframe__47->GetXaxis()->SetTitleFont(43);
   hframe__47->GetYaxis()->SetTitle("Entries");
   hframe__47->GetYaxis()->SetNdivisions(506);
   hframe__47->GetYaxis()->SetLabelFont(43);
   hframe__47->GetYaxis()->SetLabelSize(24);
   hframe__47->GetYaxis()->SetTitleSize(24);
   hframe__47->GetYaxis()->SetTitleOffset(2.8);
   hframe__47->GetYaxis()->SetTitleFont(43);
   hframe__47->GetZaxis()->SetLabelFont(43);
   hframe__47->GetZaxis()->SetLabelSize(24);
   hframe__47->GetZaxis()->SetTitleOffset(1.1);
   hframe__47->GetZaxis()->SetTitleFont(43);
   hframe__47->Draw(" ");
   
   TH1D *syst_sigma_long_bkg_shift_dispersion = new TH1D("syst_sigma_long_bkg_shift_dispersion","",1000,-75,75);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(439,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(441,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(474,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(481,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(483,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(488,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(490,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(491,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(494,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(496,2);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(499,2);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(505,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(508,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(509,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(516,1);
   syst_sigma_long_bkg_shift_dispersion->SetBinContent(534,1);
   syst_sigma_long_bkg_shift_dispersion->SetEntries(18);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift_dispersion->SetFillColor(ci);
   syst_sigma_long_bkg_shift_dispersion->SetFillStyle(0);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift_dispersion->SetLineColor(ci);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift_dispersion->SetMarkerColor(ci);
   syst_sigma_long_bkg_shift_dispersion->SetMarkerSize(1.1);
   syst_sigma_long_bkg_shift_dispersion->GetXaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift_dispersion->GetXaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift_dispersion->GetXaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift_dispersion->GetXaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift_dispersion->GetYaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift_dispersion->GetYaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift_dispersion->GetYaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift_dispersion->GetYaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift_dispersion->GetZaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift_dispersion->GetZaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift_dispersion->GetZaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift_dispersion->GetZaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift_dispersion->Draw("histsame");
      tex = new TLatex(0.195,0.895,"Mean = -1.364 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.195,0.82,"RMS = 3.386 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.905,0.885,"Bkg. #sigma_{long}^{2} cut");
tex->SetNDC();
   tex->SetTextAlign(32);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__48 = new TH1F("hframe__48","",1000,-6.28125,6.28125);
   hframe__48->SetMinimum(0);
   hframe__48->SetMaximum(2.7);
   hframe__48->SetDirectory(0);
   hframe__48->SetStats(0);
   hframe__48->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__48->GetXaxis()->SetNdivisions(506);
   hframe__48->GetXaxis()->SetLabelFont(43);
   hframe__48->GetXaxis()->SetLabelSize(24);
   hframe__48->GetXaxis()->SetTitleSize(24);
   hframe__48->GetXaxis()->SetTitleOffset(2.3);
   hframe__48->GetXaxis()->SetTitleFont(43);
   hframe__48->GetYaxis()->SetTitle("Entries");
   hframe__48->GetYaxis()->SetNdivisions(506);
   hframe__48->GetYaxis()->SetLabelFont(43);
   hframe__48->GetYaxis()->SetLabelSize(24);
   hframe__48->GetYaxis()->SetTitleSize(24);
   hframe__48->GetYaxis()->SetTitleOffset(2.8);
   hframe__48->GetYaxis()->SetTitleFont(43);
   hframe__48->GetZaxis()->SetLabelFont(43);
   hframe__48->GetZaxis()->SetLabelSize(24);
   hframe__48->GetZaxis()->SetTitleOffset(1.1);
   hframe__48->GetZaxis()->SetTitleFont(43);
   hframe__48->Draw("sameaxis");
   c_cross_section_variations_dispersion_2->Modified();
   c_cross_section_variations_dispersion->cd();
  
// ------------>Primitives in pad: c_cross_section_variations_dispersion_3
   c_cross_section_variations_dispersion_3 = new TPad("c_cross_section_variations_dispersion_3", "c_cross_section_variations_dispersion_3",0.6716667,0.501,0.995,0.999);
   c_cross_section_variations_dispersion_3->Draw();
   c_cross_section_variations_dispersion_3->cd();
   c_cross_section_variations_dispersion_3->Range(-1.615211,-1.198225,1.321536,8.387574);
   c_cross_section_variations_dispersion_3->SetFillColor(10);
   c_cross_section_variations_dispersion_3->SetBorderMode(0);
   c_cross_section_variations_dispersion_3->SetBorderSize(2);
   c_cross_section_variations_dispersion_3->SetTickx(1);
   c_cross_section_variations_dispersion_3->SetTicky(1);
   c_cross_section_variations_dispersion_3->SetLeftMargin(0.135);
   c_cross_section_variations_dispersion_3->SetRightMargin(0.035);
   c_cross_section_variations_dispersion_3->SetTopMargin(0.03);
   c_cross_section_variations_dispersion_3->SetBottomMargin(0.125);
   c_cross_section_variations_dispersion_3->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_3->SetFrameBorderMode(0);
   c_cross_section_variations_dispersion_3->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_3->SetFrameBorderMode(0);
   
   TH1F *hframe__49 = new TH1F("hframe__49","",1000,-1.21875,1.21875);
   hframe__49->SetMinimum(0);
   hframe__49->SetMaximum(8.1);
   hframe__49->SetDirectory(0);
   hframe__49->SetStats(0);
   hframe__49->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__49->GetXaxis()->SetNdivisions(506);
   hframe__49->GetXaxis()->SetLabelFont(43);
   hframe__49->GetXaxis()->SetLabelSize(24);
   hframe__49->GetXaxis()->SetTitleSize(24);
   hframe__49->GetXaxis()->SetTitleOffset(2.3);
   hframe__49->GetXaxis()->SetTitleFont(43);
   hframe__49->GetYaxis()->SetTitle("Entries");
   hframe__49->GetYaxis()->SetNdivisions(506);
   hframe__49->GetYaxis()->SetLabelFont(43);
   hframe__49->GetYaxis()->SetLabelSize(24);
   hframe__49->GetYaxis()->SetTitleSize(24);
   hframe__49->GetYaxis()->SetTitleOffset(2.8);
   hframe__49->GetYaxis()->SetTitleFont(43);
   hframe__49->GetZaxis()->SetLabelFont(43);
   hframe__49->GetZaxis()->SetLabelSize(24);
   hframe__49->GetZaxis()->SetTitleOffset(1.1);
   hframe__49->GetZaxis()->SetTitleFont(43);
   hframe__49->Draw(" ");
   
   TH1D *syst_gamma_jet_weight_dispersion = new TH1D("syst_gamma_jet_weight_dispersion","",1000,-75,75);
   syst_gamma_jet_weight_dispersion->SetBinContent(494,1);
   syst_gamma_jet_weight_dispersion->SetBinContent(495,1);
   syst_gamma_jet_weight_dispersion->SetBinContent(497,1);
   syst_gamma_jet_weight_dispersion->SetBinContent(498,1);
   syst_gamma_jet_weight_dispersion->SetBinContent(499,5);
   syst_gamma_jet_weight_dispersion->SetBinContent(502,6);
   syst_gamma_jet_weight_dispersion->SetBinContent(504,1);
   syst_gamma_jet_weight_dispersion->SetBinContent(506,1);
   syst_gamma_jet_weight_dispersion->SetBinContent(507,1);
   syst_gamma_jet_weight_dispersion->SetEntries(18);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight_dispersion->SetFillColor(ci);
   syst_gamma_jet_weight_dispersion->SetFillStyle(0);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight_dispersion->SetLineColor(ci);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight_dispersion->SetMarkerColor(ci);
   syst_gamma_jet_weight_dispersion->SetMarkerSize(1.1);
   syst_gamma_jet_weight_dispersion->GetXaxis()->SetLabelFont(42);
   syst_gamma_jet_weight_dispersion->GetXaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight_dispersion->GetXaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight_dispersion->GetXaxis()->SetTitleFont(42);
   syst_gamma_jet_weight_dispersion->GetYaxis()->SetLabelFont(42);
   syst_gamma_jet_weight_dispersion->GetYaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight_dispersion->GetYaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight_dispersion->GetYaxis()->SetTitleFont(42);
   syst_gamma_jet_weight_dispersion->GetZaxis()->SetLabelFont(42);
   syst_gamma_jet_weight_dispersion->GetZaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight_dispersion->GetZaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight_dispersion->GetZaxis()->SetTitleFont(42);
   syst_gamma_jet_weight_dispersion->Draw("histsame");
      tex = new TLatex(0.195,0.895,"Mean = -0.004 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.195,0.82,"RMS = 0.494 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.905,0.895,"MC signal amount");
tex->SetNDC();
   tex->SetTextAlign(32);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__50 = new TH1F("hframe__50","",1000,-1.21875,1.21875);
   hframe__50->SetMinimum(0);
   hframe__50->SetMaximum(8.1);
   hframe__50->SetDirectory(0);
   hframe__50->SetStats(0);
   hframe__50->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__50->GetXaxis()->SetNdivisions(506);
   hframe__50->GetXaxis()->SetLabelFont(43);
   hframe__50->GetXaxis()->SetLabelSize(24);
   hframe__50->GetXaxis()->SetTitleSize(24);
   hframe__50->GetXaxis()->SetTitleOffset(2.3);
   hframe__50->GetXaxis()->SetTitleFont(43);
   hframe__50->GetYaxis()->SetTitle("Entries");
   hframe__50->GetYaxis()->SetNdivisions(506);
   hframe__50->GetYaxis()->SetLabelFont(43);
   hframe__50->GetYaxis()->SetLabelSize(24);
   hframe__50->GetYaxis()->SetTitleSize(24);
   hframe__50->GetYaxis()->SetTitleOffset(2.8);
   hframe__50->GetYaxis()->SetTitleFont(43);
   hframe__50->GetZaxis()->SetLabelFont(43);
   hframe__50->GetZaxis()->SetLabelSize(24);
   hframe__50->GetZaxis()->SetTitleOffset(1.1);
   hframe__50->GetZaxis()->SetTitleFont(43);
   hframe__50->Draw("sameaxis");
   c_cross_section_variations_dispersion_3->Modified();
   c_cross_section_variations_dispersion->cd();
  
// ------------>Primitives in pad: c_cross_section_variations_dispersion_4
   c_cross_section_variations_dispersion_4 = new TPad("c_cross_section_variations_dispersion_4", "c_cross_section_variations_dispersion_4",0.005,0.001,0.3283333,0.499);
   c_cross_section_variations_dispersion_4->Draw();
   c_cross_section_variations_dispersion_4->cd();
   c_cross_section_variations_dispersion_4->Range(-19.75527,-0.3994083,16.1634,2.795858);
   c_cross_section_variations_dispersion_4->SetFillColor(10);
   c_cross_section_variations_dispersion_4->SetBorderMode(0);
   c_cross_section_variations_dispersion_4->SetBorderSize(2);
   c_cross_section_variations_dispersion_4->SetTickx(1);
   c_cross_section_variations_dispersion_4->SetTicky(1);
   c_cross_section_variations_dispersion_4->SetLeftMargin(0.135);
   c_cross_section_variations_dispersion_4->SetRightMargin(0.035);
   c_cross_section_variations_dispersion_4->SetTopMargin(0.03);
   c_cross_section_variations_dispersion_4->SetBottomMargin(0.125);
   c_cross_section_variations_dispersion_4->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_4->SetFrameBorderMode(0);
   c_cross_section_variations_dispersion_4->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_4->SetFrameBorderMode(0);
   
   TH1F *hframe__51 = new TH1F("hframe__51","",1000,-14.90625,14.90625);
   hframe__51->SetMinimum(0);
   hframe__51->SetMaximum(2.7);
   hframe__51->SetDirectory(0);
   hframe__51->SetStats(0);
   hframe__51->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__51->GetXaxis()->SetNdivisions(506);
   hframe__51->GetXaxis()->SetLabelFont(43);
   hframe__51->GetXaxis()->SetLabelSize(24);
   hframe__51->GetXaxis()->SetTitleSize(24);
   hframe__51->GetXaxis()->SetTitleOffset(2.3);
   hframe__51->GetXaxis()->SetTitleFont(43);
   hframe__51->GetYaxis()->SetTitle("Entries");
   hframe__51->GetYaxis()->SetNdivisions(506);
   hframe__51->GetYaxis()->SetLabelFont(43);
   hframe__51->GetYaxis()->SetLabelSize(24);
   hframe__51->GetYaxis()->SetTitleSize(24);
   hframe__51->GetYaxis()->SetTitleOffset(2.8);
   hframe__51->GetYaxis()->SetTitleFont(43);
   hframe__51->GetZaxis()->SetLabelFont(43);
   hframe__51->GetZaxis()->SetLabelSize(24);
   hframe__51->GetZaxis()->SetTitleOffset(1.1);
   hframe__51->GetZaxis()->SetTitleFont(43);
   hframe__51->Draw(" ");
   
   TH1D *syst_no_smearing_dispersion = new TH1D("syst_no_smearing_dispersion","",1000,-75,75);
   syst_no_smearing_dispersion->SetBinContent(440,1);
   syst_no_smearing_dispersion->SetBinContent(441,1);
   syst_no_smearing_dispersion->SetBinContent(446,2);
   syst_no_smearing_dispersion->SetBinContent(458,1);
   syst_no_smearing_dispersion->SetBinContent(464,1);
   syst_no_smearing_dispersion->SetBinContent(467,1);
   syst_no_smearing_dispersion->SetBinContent(500,1);
   syst_no_smearing_dispersion->SetBinContent(580,1);
   syst_no_smearing_dispersion->SetEntries(9);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_dispersion->SetFillColor(ci);
   syst_no_smearing_dispersion->SetFillStyle(0);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_dispersion->SetLineColor(ci);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_dispersion->SetMarkerColor(ci);
   syst_no_smearing_dispersion->SetMarkerSize(1.1);
   syst_no_smearing_dispersion->GetXaxis()->SetLabelFont(42);
   syst_no_smearing_dispersion->GetXaxis()->SetLabelSize(0.035);
   syst_no_smearing_dispersion->GetXaxis()->SetTitleSize(0.035);
   syst_no_smearing_dispersion->GetXaxis()->SetTitleFont(42);
   syst_no_smearing_dispersion->GetYaxis()->SetLabelFont(42);
   syst_no_smearing_dispersion->GetYaxis()->SetLabelSize(0.035);
   syst_no_smearing_dispersion->GetYaxis()->SetTitleSize(0.035);
   syst_no_smearing_dispersion->GetYaxis()->SetTitleFont(42);
   syst_no_smearing_dispersion->GetZaxis()->SetLabelFont(42);
   syst_no_smearing_dispersion->GetZaxis()->SetLabelSize(0.035);
   syst_no_smearing_dispersion->GetZaxis()->SetTitleSize(0.035);
   syst_no_smearing_dispersion->GetZaxis()->SetTitleFont(42);
   syst_no_smearing_dispersion->Draw("histsame");
      tex = new TLatex(0.195,0.895,"Mean = -4.341 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.195,0.82,"RMS = 6.353 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.905,0.895,"No MC tuning");
tex->SetNDC();
   tex->SetTextAlign(32);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__52 = new TH1F("hframe__52","",1000,-14.90625,14.90625);
   hframe__52->SetMinimum(0);
   hframe__52->SetMaximum(2.7);
   hframe__52->SetDirectory(0);
   hframe__52->SetStats(0);
   hframe__52->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__52->GetXaxis()->SetNdivisions(506);
   hframe__52->GetXaxis()->SetLabelFont(43);
   hframe__52->GetXaxis()->SetLabelSize(24);
   hframe__52->GetXaxis()->SetTitleSize(24);
   hframe__52->GetXaxis()->SetTitleOffset(2.3);
   hframe__52->GetXaxis()->SetTitleFont(43);
   hframe__52->GetYaxis()->SetTitle("Entries");
   hframe__52->GetYaxis()->SetNdivisions(506);
   hframe__52->GetYaxis()->SetLabelFont(43);
   hframe__52->GetYaxis()->SetLabelSize(24);
   hframe__52->GetYaxis()->SetTitleSize(24);
   hframe__52->GetYaxis()->SetTitleOffset(2.8);
   hframe__52->GetYaxis()->SetTitleFont(43);
   hframe__52->GetZaxis()->SetLabelFont(43);
   hframe__52->GetZaxis()->SetLabelSize(24);
   hframe__52->GetZaxis()->SetTitleOffset(1.1);
   hframe__52->GetZaxis()->SetTitleFont(43);
   hframe__52->Draw("sameaxis");
   c_cross_section_variations_dispersion_4->Modified();
   c_cross_section_variations_dispersion->cd();
  
// ------------>Primitives in pad: c_cross_section_variations_dispersion_5
   c_cross_section_variations_dispersion_5 = new TPad("c_cross_section_variations_dispersion_5", "c_cross_section_variations_dispersion_5",0.3383333,0.001,0.6616667,0.499);
   c_cross_section_variations_dispersion_5->Draw();
   c_cross_section_variations_dispersion_5->cd();
   c_cross_section_variations_dispersion_5->Range(-9.815512,-0.3994083,8.030874,2.795858);
   c_cross_section_variations_dispersion_5->SetFillColor(10);
   c_cross_section_variations_dispersion_5->SetBorderMode(0);
   c_cross_section_variations_dispersion_5->SetBorderSize(2);
   c_cross_section_variations_dispersion_5->SetTickx(1);
   c_cross_section_variations_dispersion_5->SetTicky(1);
   c_cross_section_variations_dispersion_5->SetLeftMargin(0.135);
   c_cross_section_variations_dispersion_5->SetRightMargin(0.035);
   c_cross_section_variations_dispersion_5->SetTopMargin(0.03);
   c_cross_section_variations_dispersion_5->SetBottomMargin(0.125);
   c_cross_section_variations_dispersion_5->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_5->SetFrameBorderMode(0);
   c_cross_section_variations_dispersion_5->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_5->SetFrameBorderMode(0);
   
   TH1F *hframe__53 = new TH1F("hframe__53","",1000,-7.40625,7.40625);
   hframe__53->SetMinimum(0);
   hframe__53->SetMaximum(2.7);
   hframe__53->SetDirectory(0);
   hframe__53->SetStats(0);
   hframe__53->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__53->GetXaxis()->SetNdivisions(506);
   hframe__53->GetXaxis()->SetLabelFont(43);
   hframe__53->GetXaxis()->SetLabelSize(24);
   hframe__53->GetXaxis()->SetTitleSize(24);
   hframe__53->GetXaxis()->SetTitleOffset(2.3);
   hframe__53->GetXaxis()->SetTitleFont(43);
   hframe__53->GetYaxis()->SetTitle("Entries");
   hframe__53->GetYaxis()->SetNdivisions(506);
   hframe__53->GetYaxis()->SetLabelFont(43);
   hframe__53->GetYaxis()->SetLabelSize(24);
   hframe__53->GetYaxis()->SetTitleSize(24);
   hframe__53->GetYaxis()->SetTitleOffset(2.8);
   hframe__53->GetYaxis()->SetTitleFont(43);
   hframe__53->GetZaxis()->SetLabelFont(43);
   hframe__53->GetZaxis()->SetLabelSize(24);
   hframe__53->GetZaxis()->SetTitleOffset(1.1);
   hframe__53->GetZaxis()->SetTitleFont(43);
   hframe__53->Draw(" ");
   
   TH1D *syst_CPV_dispersion = new TH1D("syst_CPV_dispersion","",1000,-75,75);
   syst_CPV_dispersion->SetBinContent(476,1);
   syst_CPV_dispersion->SetBinContent(479,2);
   syst_CPV_dispersion->SetBinContent(492,1);
   syst_CPV_dispersion->SetBinContent(494,1);
   syst_CPV_dispersion->SetBinContent(495,1);
   syst_CPV_dispersion->SetBinContent(497,1);
   syst_CPV_dispersion->SetBinContent(501,1);
   syst_CPV_dispersion->SetBinContent(504,1);
   syst_CPV_dispersion->SetBinContent(510,1);
   syst_CPV_dispersion->SetBinContent(511,1);
   syst_CPV_dispersion->SetBinContent(513,1);
   syst_CPV_dispersion->SetBinContent(519,1);
   syst_CPV_dispersion->SetBinContent(522,1);
   syst_CPV_dispersion->SetBinContent(524,1);
   syst_CPV_dispersion->SetBinContent(527,1);
   syst_CPV_dispersion->SetBinContent(539,1);
   syst_CPV_dispersion->SetBinContent(540,1);
   syst_CPV_dispersion->SetEntries(18);

   ci = TColor::GetColor("#cc6666");
   syst_CPV_dispersion->SetFillColor(ci);
   syst_CPV_dispersion->SetFillStyle(0);

   ci = TColor::GetColor("#cc6666");
   syst_CPV_dispersion->SetLineColor(ci);

   ci = TColor::GetColor("#cc6666");
   syst_CPV_dispersion->SetMarkerColor(ci);
   syst_CPV_dispersion->SetMarkerSize(1.1);
   syst_CPV_dispersion->GetXaxis()->SetLabelFont(42);
   syst_CPV_dispersion->GetXaxis()->SetLabelSize(0.035);
   syst_CPV_dispersion->GetXaxis()->SetTitleSize(0.035);
   syst_CPV_dispersion->GetXaxis()->SetTitleFont(42);
   syst_CPV_dispersion->GetYaxis()->SetLabelFont(42);
   syst_CPV_dispersion->GetYaxis()->SetLabelSize(0.035);
   syst_CPV_dispersion->GetYaxis()->SetTitleSize(0.035);
   syst_CPV_dispersion->GetYaxis()->SetTitleFont(42);
   syst_CPV_dispersion->GetZaxis()->SetLabelFont(42);
   syst_CPV_dispersion->GetZaxis()->SetLabelSize(0.035);
   syst_CPV_dispersion->GetZaxis()->SetTitleSize(0.035);
   syst_CPV_dispersion->GetZaxis()->SetTitleFont(42);
   syst_CPV_dispersion->Draw("histsame");
      tex = new TLatex(0.195,0.895,"Mean = 0.948 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.195,0.82,"RMS = 2.832 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.905,0.895,"CPV");
tex->SetNDC();
   tex->SetTextAlign(32);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__54 = new TH1F("hframe__54","",1000,-7.40625,7.40625);
   hframe__54->SetMinimum(0);
   hframe__54->SetMaximum(2.7);
   hframe__54->SetDirectory(0);
   hframe__54->SetStats(0);
   hframe__54->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__54->GetXaxis()->SetNdivisions(506);
   hframe__54->GetXaxis()->SetLabelFont(43);
   hframe__54->GetXaxis()->SetLabelSize(24);
   hframe__54->GetXaxis()->SetTitleSize(24);
   hframe__54->GetXaxis()->SetTitleOffset(2.3);
   hframe__54->GetXaxis()->SetTitleFont(43);
   hframe__54->GetYaxis()->SetTitle("Entries");
   hframe__54->GetYaxis()->SetNdivisions(506);
   hframe__54->GetYaxis()->SetLabelFont(43);
   hframe__54->GetYaxis()->SetLabelSize(24);
   hframe__54->GetYaxis()->SetTitleSize(24);
   hframe__54->GetYaxis()->SetTitleOffset(2.8);
   hframe__54->GetYaxis()->SetTitleFont(43);
   hframe__54->GetZaxis()->SetLabelFont(43);
   hframe__54->GetZaxis()->SetLabelSize(24);
   hframe__54->GetZaxis()->SetTitleOffset(1.1);
   hframe__54->GetZaxis()->SetTitleFont(43);
   hframe__54->Draw("sameaxis");
   c_cross_section_variations_dispersion_5->Modified();
   c_cross_section_variations_dispersion->cd();
  
// ------------>Primitives in pad: c_cross_section_variations_dispersion_6
   c_cross_section_variations_dispersion_6 = new TPad("c_cross_section_variations_dispersion_6", "c_cross_section_variations_dispersion_6",0.6716667,0.001,0.995,0.499);
   c_cross_section_variations_dispersion_6->Draw();
   c_cross_section_variations_dispersion_6->cd();
   c_cross_section_variations_dispersion_6->Range(-34.41642,-0.5991124,28.15889,4.193787);
   c_cross_section_variations_dispersion_6->SetFillColor(10);
   c_cross_section_variations_dispersion_6->SetBorderMode(0);
   c_cross_section_variations_dispersion_6->SetBorderSize(2);
   c_cross_section_variations_dispersion_6->SetTickx(1);
   c_cross_section_variations_dispersion_6->SetTicky(1);
   c_cross_section_variations_dispersion_6->SetLeftMargin(0.135);
   c_cross_section_variations_dispersion_6->SetRightMargin(0.035);
   c_cross_section_variations_dispersion_6->SetTopMargin(0.03);
   c_cross_section_variations_dispersion_6->SetBottomMargin(0.125);
   c_cross_section_variations_dispersion_6->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_6->SetFrameBorderMode(0);
   c_cross_section_variations_dispersion_6->SetFrameFillColor(0);
   c_cross_section_variations_dispersion_6->SetFrameBorderMode(0);
   
   TH1F *hframe__55 = new TH1F("hframe__55","",1000,-25.96875,25.96875);
   hframe__55->SetMinimum(0);
   hframe__55->SetMaximum(4.05);
   hframe__55->SetDirectory(0);
   hframe__55->SetStats(0);
   hframe__55->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__55->GetXaxis()->SetNdivisions(506);
   hframe__55->GetXaxis()->SetLabelFont(43);
   hframe__55->GetXaxis()->SetLabelSize(24);
   hframe__55->GetXaxis()->SetTitleSize(24);
   hframe__55->GetXaxis()->SetTitleOffset(2.3);
   hframe__55->GetXaxis()->SetTitleFont(43);
   hframe__55->GetYaxis()->SetTitle("Entries");
   hframe__55->GetYaxis()->SetNdivisions(506);
   hframe__55->GetYaxis()->SetLabelFont(43);
   hframe__55->GetYaxis()->SetLabelSize(24);
   hframe__55->GetYaxis()->SetTitleSize(24);
   hframe__55->GetYaxis()->SetTitleOffset(2.8);
   hframe__55->GetYaxis()->SetTitleFont(43);
   hframe__55->GetZaxis()->SetLabelFont(43);
   hframe__55->GetZaxis()->SetLabelSize(24);
   hframe__55->GetZaxis()->SetTitleOffset(1.1);
   hframe__55->GetZaxis()->SetTitleFont(43);
   hframe__55->Draw(" ");
   
   TH1D *syst_combined_iso_prob_dispersion = new TH1D("syst_combined_iso_prob_dispersion","",1000,-75,75);
   syst_combined_iso_prob_dispersion->SetBinContent(288,1);
   syst_combined_iso_prob_dispersion->SetBinContent(303,1);
   syst_combined_iso_prob_dispersion->SetBinContent(309,1);
   syst_combined_iso_prob_dispersion->SetBinContent(319,1);
   syst_combined_iso_prob_dispersion->SetBinContent(320,1);
   syst_combined_iso_prob_dispersion->SetBinContent(332,1);
   syst_combined_iso_prob_dispersion->SetBinContent(334,1);
   syst_combined_iso_prob_dispersion->SetBinContent(344,1);
   syst_combined_iso_prob_dispersion->SetBinContent(350,1);
   syst_combined_iso_prob_dispersion->SetBinContent(353,1);
   syst_combined_iso_prob_dispersion->SetBinContent(354,1);
   syst_combined_iso_prob_dispersion->SetBinContent(360,1);
   syst_combined_iso_prob_dispersion->SetBinContent(367,1);
   syst_combined_iso_prob_dispersion->SetBinContent(369,1);
   syst_combined_iso_prob_dispersion->SetBinContent(372,1);
   syst_combined_iso_prob_dispersion->SetBinContent(374,2);
   syst_combined_iso_prob_dispersion->SetBinContent(392,2);
   syst_combined_iso_prob_dispersion->SetBinContent(394,1);
   syst_combined_iso_prob_dispersion->SetBinContent(395,1);
   syst_combined_iso_prob_dispersion->SetBinContent(396,1);
   syst_combined_iso_prob_dispersion->SetBinContent(397,1);
   syst_combined_iso_prob_dispersion->SetBinContent(415,1);
   syst_combined_iso_prob_dispersion->SetBinContent(416,1);
   syst_combined_iso_prob_dispersion->SetBinContent(438,1);
   syst_combined_iso_prob_dispersion->SetBinContent(442,1);
   syst_combined_iso_prob_dispersion->SetBinContent(458,1);
   syst_combined_iso_prob_dispersion->SetBinContent(472,1);
   syst_combined_iso_prob_dispersion->SetBinContent(475,1);
   syst_combined_iso_prob_dispersion->SetBinContent(520,1);
   syst_combined_iso_prob_dispersion->SetBinContent(531,1);
   syst_combined_iso_prob_dispersion->SetBinContent(539,2);
   syst_combined_iso_prob_dispersion->SetBinContent(545,1);
   syst_combined_iso_prob_dispersion->SetBinContent(546,1);
   syst_combined_iso_prob_dispersion->SetBinContent(547,1);
   syst_combined_iso_prob_dispersion->SetBinContent(550,1);
   syst_combined_iso_prob_dispersion->SetBinContent(553,1);
   syst_combined_iso_prob_dispersion->SetBinContent(556,2);
   syst_combined_iso_prob_dispersion->SetBinContent(559,1);
   syst_combined_iso_prob_dispersion->SetBinContent(560,1);
   syst_combined_iso_prob_dispersion->SetBinContent(563,1);
   syst_combined_iso_prob_dispersion->SetBinContent(567,1);
   syst_combined_iso_prob_dispersion->SetBinContent(568,1);
   syst_combined_iso_prob_dispersion->SetBinContent(569,3);
   syst_combined_iso_prob_dispersion->SetBinContent(572,1);
   syst_combined_iso_prob_dispersion->SetBinContent(573,1);
   syst_combined_iso_prob_dispersion->SetBinContent(574,2);
   syst_combined_iso_prob_dispersion->SetBinContent(577,1);
   syst_combined_iso_prob_dispersion->SetBinContent(580,1);
   syst_combined_iso_prob_dispersion->SetBinContent(585,1);
   syst_combined_iso_prob_dispersion->SetBinContent(586,1);
   syst_combined_iso_prob_dispersion->SetBinContent(589,2);
   syst_combined_iso_prob_dispersion->SetBinContent(590,1);
   syst_combined_iso_prob_dispersion->SetBinContent(602,1);
   syst_combined_iso_prob_dispersion->SetBinContent(634,1);
   syst_combined_iso_prob_dispersion->SetBinContent(639,1);
   syst_combined_iso_prob_dispersion->SetEntries(63);

   ci = TColor::GetColor("#ff9900");
   syst_combined_iso_prob_dispersion->SetFillColor(ci);
   syst_combined_iso_prob_dispersion->SetFillStyle(0);

   ci = TColor::GetColor("#ff9900");
   syst_combined_iso_prob_dispersion->SetLineColor(ci);

   ci = TColor::GetColor("#ff9900");
   syst_combined_iso_prob_dispersion->SetMarkerColor(ci);
   syst_combined_iso_prob_dispersion->SetMarkerSize(1.1);
   syst_combined_iso_prob_dispersion->GetXaxis()->SetLabelFont(42);
   syst_combined_iso_prob_dispersion->GetXaxis()->SetLabelSize(0.035);
   syst_combined_iso_prob_dispersion->GetXaxis()->SetTitleSize(0.035);
   syst_combined_iso_prob_dispersion->GetXaxis()->SetTitleFont(42);
   syst_combined_iso_prob_dispersion->GetYaxis()->SetLabelFont(42);
   syst_combined_iso_prob_dispersion->GetYaxis()->SetLabelSize(0.035);
   syst_combined_iso_prob_dispersion->GetYaxis()->SetTitleSize(0.035);
   syst_combined_iso_prob_dispersion->GetYaxis()->SetTitleFont(42);
   syst_combined_iso_prob_dispersion->GetZaxis()->SetLabelFont(42);
   syst_combined_iso_prob_dispersion->GetZaxis()->SetLabelSize(0.035);
   syst_combined_iso_prob_dispersion->GetZaxis()->SetTitleSize(0.035);
   syst_combined_iso_prob_dispersion->GetZaxis()->SetTitleFont(42);
   syst_combined_iso_prob_dispersion->Draw("histsame");
      tex = new TLatex(0.195,0.895,"Mean = -3.474 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.195,0.82,"RMS = 15.469 %");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.905,0.895,"Iso. probability");
tex->SetNDC();
   tex->SetTextAlign(32);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__56 = new TH1F("hframe__56","",1000,-25.96875,25.96875);
   hframe__56->SetMinimum(0);
   hframe__56->SetMaximum(4.05);
   hframe__56->SetDirectory(0);
   hframe__56->SetStats(0);
   hframe__56->GetXaxis()->SetTitle("Relative difference (%)");
   hframe__56->GetXaxis()->SetNdivisions(506);
   hframe__56->GetXaxis()->SetLabelFont(43);
   hframe__56->GetXaxis()->SetLabelSize(24);
   hframe__56->GetXaxis()->SetTitleSize(24);
   hframe__56->GetXaxis()->SetTitleOffset(2.3);
   hframe__56->GetXaxis()->SetTitleFont(43);
   hframe__56->GetYaxis()->SetTitle("Entries");
   hframe__56->GetYaxis()->SetNdivisions(506);
   hframe__56->GetYaxis()->SetLabelFont(43);
   hframe__56->GetYaxis()->SetLabelSize(24);
   hframe__56->GetYaxis()->SetTitleSize(24);
   hframe__56->GetYaxis()->SetTitleOffset(2.8);
   hframe__56->GetYaxis()->SetTitleFont(43);
   hframe__56->GetZaxis()->SetLabelFont(43);
   hframe__56->GetZaxis()->SetLabelSize(24);
   hframe__56->GetZaxis()->SetTitleOffset(1.1);
   hframe__56->GetZaxis()->SetTitleFont(43);
   hframe__56->Draw("sameaxis");
   c_cross_section_variations_dispersion_6->Modified();
   c_cross_section_variations_dispersion->cd();
   c_cross_section_variations_dispersion->Modified();
   c_cross_section_variations_dispersion->cd();
   c_cross_section_variations_dispersion->SetSelected(c_cross_section_variations_dispersion);
}
