{
//=========Macro generated from canvas: c_total_syst/
//=========  (Wed May 29 06:56:12 2019) by ROOT version5.34/30
   TCanvas *c_total_syst = new TCanvas("c_total_syst", "",0,0,800,600);
   gStyle->SetOptStat(0);
   c_total_syst->SetHighLightColor(2);
   c_total_syst->Range(0.1703107,-6.77713,62.3107,49.23221);
   c_total_syst->SetFillColor(0);
   c_total_syst->SetBorderMode(0);
   c_total_syst->SetBorderSize(2);
   c_total_syst->SetTickx(1);
   c_total_syst->SetTicky(1);
   c_total_syst->SetLeftMargin(0.126);
   c_total_syst->SetRightMargin(0.005);
   c_total_syst->SetTopMargin(0.022);
   c_total_syst->SetBottomMargin(0.121);
   c_total_syst->SetFrameBorderMode(0);
   c_total_syst->SetFrameBorderMode(0);
   
   TH1F *hframe__57 = new TH1F("hframe__57","",1000,8,62);
   hframe__57->SetMinimum(0);
   hframe__57->SetMaximum(48);
   hframe__57->SetDirectory(0);
   hframe__57->SetStats(0);
   hframe__57->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__57->GetXaxis()->SetNdivisions(506);
   hframe__57->GetXaxis()->SetLabelFont(43);
   hframe__57->GetXaxis()->SetLabelSize(25.84615);
   hframe__57->GetXaxis()->SetTitleSize(28);
   hframe__57->GetXaxis()->SetTitleOffset(1.1);
   hframe__57->GetXaxis()->SetTitleFont(43);
   hframe__57->GetYaxis()->SetTitle("Cross Section Systematic Uncertainty (%)");
   hframe__57->GetYaxis()->SetNdivisions(505);
   hframe__57->GetYaxis()->SetLabelFont(43);
   hframe__57->GetYaxis()->SetLabelSize(25.84615);
   hframe__57->GetYaxis()->SetTitleSize(28);
   hframe__57->GetYaxis()->SetTitleOffset(1.26);
   hframe__57->GetYaxis()->SetTitleFont(43);
   hframe__57->GetZaxis()->SetLabelFont(43);
   hframe__57->GetZaxis()->SetLabelSize(25.84615);
   hframe__57->GetZaxis()->SetTitleOffset(1.1);
   hframe__57->GetZaxis()->SetTitleFont(43);
   hframe__57->Draw(" ");
   Double_t xAxis17[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_CPV = new TH1D("syst_CPV","",9, xAxis17);
   syst_CPV->SetBinContent(1,2.248346);
   syst_CPV->SetBinContent(2,2.37761);
   syst_CPV->SetBinContent(3,2.506875);
   syst_CPV->SetBinContent(4,2.636139);
   syst_CPV->SetBinContent(5,2.765403);
   syst_CPV->SetBinContent(6,2.991616);
   syst_CPV->SetBinContent(7,3.314776);
   syst_CPV->SetBinContent(8,3.799518);
   syst_CPV->SetBinContent(9,4.769);
   syst_CPV->SetEntries(18);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#cc6666");
   syst_CPV->SetFillColor(ci);
   syst_CPV->SetFillStyle(0);

   ci = TColor::GetColor("#cc6666");
   syst_CPV->SetLineColor(ci);
   syst_CPV->SetLineWidth(2);

   ci = TColor::GetColor("#cc6666");
   syst_CPV->SetMarkerColor(ci);
   syst_CPV->SetMarkerStyle(27);
   syst_CPV->SetMarkerSize(1.54);
   syst_CPV->GetXaxis()->SetLabelFont(42);
   syst_CPV->GetXaxis()->SetLabelSize(0.035);
   syst_CPV->GetXaxis()->SetTitleSize(0.035);
   syst_CPV->GetXaxis()->SetTitleFont(42);
   syst_CPV->GetYaxis()->SetLabelFont(42);
   syst_CPV->GetYaxis()->SetLabelSize(0.035);
   syst_CPV->GetYaxis()->SetTitleSize(0.035);
   syst_CPV->GetYaxis()->SetTitleFont(42);
   syst_CPV->GetZaxis()->SetLabelFont(42);
   syst_CPV->GetZaxis()->SetLabelSize(0.035);
   syst_CPV->GetZaxis()->SetTitleSize(0.035);
   syst_CPV->GetZaxis()->SetTitleFont(42);
   syst_CPV->Draw("CPsame");
   Double_t xAxis18[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_no_smearing_final = new TH1D("syst_no_smearing_final","",9, xAxis18);
   syst_no_smearing_final->SetBinContent(1,5.999826);
   syst_no_smearing_final->SetBinContent(2,5.518244);
   syst_no_smearing_final->SetBinContent(3,5.036662);
   syst_no_smearing_final->SetBinContent(4,4.55508);
   syst_no_smearing_final->SetBinContent(5,4.273079);
   syst_no_smearing_final->SetBinContent(6,4.273079);
   syst_no_smearing_final->SetBinContent(7,4.273079);
   syst_no_smearing_final->SetBinContent(8,4.273079);
   syst_no_smearing_final->SetBinContent(9,4.273079);
   syst_no_smearing_final->SetEntries(18);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_final->SetFillColor(ci);
   syst_no_smearing_final->SetFillStyle(0);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_final->SetLineColor(ci);
   syst_no_smearing_final->SetLineWidth(2);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_final->SetMarkerColor(ci);
   syst_no_smearing_final->SetMarkerStyle(27);
   syst_no_smearing_final->SetMarkerSize(1.54);
   syst_no_smearing_final->GetXaxis()->SetLabelFont(42);
   syst_no_smearing_final->GetXaxis()->SetLabelSize(0.035);
   syst_no_smearing_final->GetXaxis()->SetTitleSize(0.035);
   syst_no_smearing_final->GetXaxis()->SetTitleFont(42);
   syst_no_smearing_final->GetYaxis()->SetLabelFont(42);
   syst_no_smearing_final->GetYaxis()->SetLabelSize(0.035);
   syst_no_smearing_final->GetYaxis()->SetTitleSize(0.035);
   syst_no_smearing_final->GetYaxis()->SetTitleFont(42);
   syst_no_smearing_final->GetZaxis()->SetLabelFont(42);
   syst_no_smearing_final->GetZaxis()->SetLabelSize(0.035);
   syst_no_smearing_final->GetZaxis()->SetTitleSize(0.035);
   syst_no_smearing_final->GetZaxis()->SetTitleFont(42);
   syst_no_smearing_final->Draw("CPsame");
   Double_t xAxis19[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_sigma_long_sig_shift = new TH1D("syst_sigma_long_sig_shift","",9, xAxis19);
   syst_sigma_long_sig_shift->SetBinContent(1,3.041768);
   syst_sigma_long_sig_shift->SetBinContent(2,3.519513);
   syst_sigma_long_sig_shift->SetBinContent(3,3.983612);
   syst_sigma_long_sig_shift->SetBinContent(4,4.434456);
   syst_sigma_long_sig_shift->SetBinContent(5,4.872422);
   syst_sigma_long_sig_shift->SetBinContent(6,5.608978);
   syst_sigma_long_sig_shift->SetBinContent(7,6.598471);
   syst_sigma_long_sig_shift->SetBinContent(8,7.95458);
   syst_sigma_long_sig_shift->SetBinContent(9,10.26225);
   syst_sigma_long_sig_shift->SetEntries(18);

   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift->SetFillColor(ci);
   syst_sigma_long_sig_shift->SetFillStyle(0);

   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift->SetLineColor(ci);
   syst_sigma_long_sig_shift->SetLineWidth(2);

   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift->SetMarkerColor(ci);
   syst_sigma_long_sig_shift->SetMarkerStyle(24);
   syst_sigma_long_sig_shift->SetMarkerSize(1.1);
   syst_sigma_long_sig_shift->GetXaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift->GetXaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift->GetXaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift->GetXaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift->GetYaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift->GetYaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift->GetYaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift->GetYaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift->GetZaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift->GetZaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift->GetZaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift->GetZaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift->Draw("CPsame");
   Double_t xAxis20[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_nlm = new TH1D("syst_nlm","",9, xAxis20);
   syst_nlm->SetBinContent(1,2);
   syst_nlm->SetBinContent(2,2);
   syst_nlm->SetBinContent(3,2);
   syst_nlm->SetBinContent(4,2);
   syst_nlm->SetBinContent(5,2);
   syst_nlm->SetBinContent(6,2);
   syst_nlm->SetBinContent(7,2);
   syst_nlm->SetBinContent(8,2);
   syst_nlm->SetBinContent(9,2);
   syst_nlm->SetEntries(9);

   ci = TColor::GetColor("#999999");
   syst_nlm->SetFillColor(ci);
   syst_nlm->SetFillStyle(0);

   ci = TColor::GetColor("#999999");
   syst_nlm->SetLineColor(ci);
   syst_nlm->SetLineWidth(2);

   ci = TColor::GetColor("#999999");
   syst_nlm->SetMarkerColor(ci);
   syst_nlm->SetMarkerStyle(24);
   syst_nlm->SetMarkerSize(1.1);
   syst_nlm->GetXaxis()->SetLabelFont(42);
   syst_nlm->GetXaxis()->SetLabelSize(0.035);
   syst_nlm->GetXaxis()->SetTitleSize(0.035);
   syst_nlm->GetXaxis()->SetTitleFont(42);
   syst_nlm->GetYaxis()->SetLabelFont(42);
   syst_nlm->GetYaxis()->SetLabelSize(0.035);
   syst_nlm->GetYaxis()->SetTitleSize(0.035);
   syst_nlm->GetYaxis()->SetTitleFont(42);
   syst_nlm->GetZaxis()->SetLabelFont(42);
   syst_nlm->GetZaxis()->SetLabelSize(0.035);
   syst_nlm->GetZaxis()->SetTitleSize(0.035);
   syst_nlm->GetZaxis()->SetTitleFont(42);
   syst_nlm->Draw("CPsame");
   Double_t xAxis21[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_sigma_long_bkg_shift = new TH1D("syst_sigma_long_bkg_shift","",9, xAxis21);
   syst_sigma_long_bkg_shift->SetBinContent(1,2.143132);
   syst_sigma_long_bkg_shift->SetBinContent(2,2.143132);
   syst_sigma_long_bkg_shift->SetBinContent(3,2.143132);
   syst_sigma_long_bkg_shift->SetBinContent(4,2.143132);
   syst_sigma_long_bkg_shift->SetBinContent(5,2.143132);
   syst_sigma_long_bkg_shift->SetBinContent(6,2.143132);
   syst_sigma_long_bkg_shift->SetBinContent(7,2.143132);
   syst_sigma_long_bkg_shift->SetBinContent(8,2.143132);
   syst_sigma_long_bkg_shift->SetBinContent(9,2.143132);
   syst_sigma_long_bkg_shift->SetEntries(18);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift->SetFillColor(ci);
   syst_sigma_long_bkg_shift->SetFillStyle(0);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift->SetLineColor(ci);
   syst_sigma_long_bkg_shift->SetLineWidth(2);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift->SetMarkerColor(ci);
   syst_sigma_long_bkg_shift->SetMarkerStyle(25);
   syst_sigma_long_bkg_shift->SetMarkerSize(1.1);
   syst_sigma_long_bkg_shift->GetXaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift->GetXaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift->GetXaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift->GetXaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift->GetYaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift->GetYaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift->GetYaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift->GetYaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift->GetZaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift->GetZaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift->GetZaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift->GetZaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift->Draw("CPsame");
   Double_t xAxis22[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_combined_iso_prob = new TH1D("syst_combined_iso_prob","",9, xAxis22);
   syst_combined_iso_prob->SetBinContent(1,21.12044);
   syst_combined_iso_prob->SetBinContent(2,18.89137);
   syst_combined_iso_prob->SetBinContent(3,16.66231);
   syst_combined_iso_prob->SetBinContent(4,14.43324);
   syst_combined_iso_prob->SetBinContent(5,13.09109);
   syst_combined_iso_prob->SetBinContent(6,13.09109);
   syst_combined_iso_prob->SetBinContent(7,13.09109);
   syst_combined_iso_prob->SetBinContent(8,13.09109);
   syst_combined_iso_prob->SetBinContent(9,13.09109);
   syst_combined_iso_prob->SetEntries(18);

   ci = TColor::GetColor("#ff9900");
   syst_combined_iso_prob->SetFillColor(ci);
   syst_combined_iso_prob->SetFillStyle(0);

   ci = TColor::GetColor("#ff9900");
   syst_combined_iso_prob->SetLineColor(ci);
   syst_combined_iso_prob->SetLineWidth(2);

   ci = TColor::GetColor("#ff9900");
   syst_combined_iso_prob->SetMarkerColor(ci);
   syst_combined_iso_prob->SetMarkerStyle(25);
   syst_combined_iso_prob->SetMarkerSize(1.1);
   syst_combined_iso_prob->GetXaxis()->SetLabelFont(42);
   syst_combined_iso_prob->GetXaxis()->SetLabelSize(0.035);
   syst_combined_iso_prob->GetXaxis()->SetTitleSize(0.035);
   syst_combined_iso_prob->GetXaxis()->SetTitleFont(42);
   syst_combined_iso_prob->GetYaxis()->SetLabelFont(42);
   syst_combined_iso_prob->GetYaxis()->SetLabelSize(0.035);
   syst_combined_iso_prob->GetYaxis()->SetTitleSize(0.035);
   syst_combined_iso_prob->GetYaxis()->SetTitleFont(42);
   syst_combined_iso_prob->GetZaxis()->SetLabelFont(42);
   syst_combined_iso_prob->GetZaxis()->SetLabelSize(0.035);
   syst_combined_iso_prob->GetZaxis()->SetTitleSize(0.035);
   syst_combined_iso_prob->GetZaxis()->SetTitleFont(42);
   syst_combined_iso_prob->Draw("CPsame");
   Double_t xAxis23[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_gamma_jet_weight = new TH1D("syst_gamma_jet_weight","",9, xAxis23);
   syst_gamma_jet_weight->SetBinContent(1,0.1559379);
   syst_gamma_jet_weight->SetBinContent(2,0.1797684);
   syst_gamma_jet_weight->SetBinContent(3,0.2035989);
   syst_gamma_jet_weight->SetBinContent(4,0.2274294);
   syst_gamma_jet_weight->SetBinContent(5,0.2512599);
   syst_gamma_jet_weight->SetBinContent(6,0.2929633);
   syst_gamma_jet_weight->SetBinContent(7,0.3525396);
   syst_gamma_jet_weight->SetBinContent(8,0.441904);
   syst_gamma_jet_weight->SetBinContent(9,0.6206329);
   syst_gamma_jet_weight->SetEntries(18);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight->SetFillColor(ci);
   syst_gamma_jet_weight->SetFillStyle(0);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight->SetLineColor(ci);
   syst_gamma_jet_weight->SetLineWidth(2);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight->SetMarkerColor(ci);
   syst_gamma_jet_weight->SetMarkerStyle(28);
   syst_gamma_jet_weight->SetMarkerSize(1.32);
   syst_gamma_jet_weight->GetXaxis()->SetLabelFont(42);
   syst_gamma_jet_weight->GetXaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight->GetXaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight->GetXaxis()->SetTitleFont(42);
   syst_gamma_jet_weight->GetYaxis()->SetLabelFont(42);
   syst_gamma_jet_weight->GetYaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight->GetYaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight->GetYaxis()->SetTitleFont(42);
   syst_gamma_jet_weight->GetZaxis()->SetLabelFont(42);
   syst_gamma_jet_weight->GetZaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight->GetZaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight->GetZaxis()->SetTitleFont(42);
   syst_gamma_jet_weight->Draw("CPsame");
   Double_t xAxis24[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_nonlinscaling = new TH1D("syst_nonlinscaling","",9, xAxis24);
   syst_nonlinscaling->SetBinContent(1,3.3);
   syst_nonlinscaling->SetBinContent(2,3.3);
   syst_nonlinscaling->SetBinContent(3,3.3);
   syst_nonlinscaling->SetBinContent(4,3.3);
   syst_nonlinscaling->SetBinContent(5,3.3);
   syst_nonlinscaling->SetBinContent(6,3.3);
   syst_nonlinscaling->SetBinContent(7,3.3);
   syst_nonlinscaling->SetBinContent(8,3.3);
   syst_nonlinscaling->SetBinContent(9,3.3);
   syst_nonlinscaling->SetEntries(9);

   ci = TColor::GetColor("#ffcc00");
   syst_nonlinscaling->SetFillColor(ci);
   syst_nonlinscaling->SetFillStyle(0);

   ci = TColor::GetColor("#ffcc00");
   syst_nonlinscaling->SetLineColor(ci);
   syst_nonlinscaling->SetLineWidth(2);

   ci = TColor::GetColor("#ffcc00");
   syst_nonlinscaling->SetMarkerColor(ci);
   syst_nonlinscaling->SetMarkerStyle(28);
   syst_nonlinscaling->SetMarkerSize(1.32);
   syst_nonlinscaling->GetXaxis()->SetLabelFont(42);
   syst_nonlinscaling->GetXaxis()->SetLabelSize(0.035);
   syst_nonlinscaling->GetXaxis()->SetTitleSize(0.035);
   syst_nonlinscaling->GetXaxis()->SetTitleFont(42);
   syst_nonlinscaling->GetYaxis()->SetLabelFont(42);
   syst_nonlinscaling->GetYaxis()->SetLabelSize(0.035);
   syst_nonlinscaling->GetYaxis()->SetTitleSize(0.035);
   syst_nonlinscaling->GetYaxis()->SetTitleFont(42);
   syst_nonlinscaling->GetZaxis()->SetLabelFont(42);
   syst_nonlinscaling->GetZaxis()->SetLabelSize(0.035);
   syst_nonlinscaling->GetZaxis()->SetTitleSize(0.035);
   syst_nonlinscaling->GetZaxis()->SetTitleFont(42);
   syst_nonlinscaling->Draw("CPsame");
   Double_t xAxis25[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_mat_budg = new TH1D("syst_mat_budg","",9, xAxis25);
   syst_mat_budg->SetBinContent(1,2.1);
   syst_mat_budg->SetBinContent(2,2.1);
   syst_mat_budg->SetBinContent(3,2.1);
   syst_mat_budg->SetBinContent(4,2.1);
   syst_mat_budg->SetBinContent(5,2.1);
   syst_mat_budg->SetBinContent(6,2.1);
   syst_mat_budg->SetBinContent(7,2.1);
   syst_mat_budg->SetBinContent(8,2.1);
   syst_mat_budg->SetBinContent(9,2.1);
   syst_mat_budg->SetEntries(9);

   ci = TColor::GetColor("#339966");
   syst_mat_budg->SetFillColor(ci);
   syst_mat_budg->SetFillStyle(0);

   ci = TColor::GetColor("#339966");
   syst_mat_budg->SetLineColor(ci);
   syst_mat_budg->SetLineWidth(2);

   ci = TColor::GetColor("#339966");
   syst_mat_budg->SetMarkerColor(ci);
   syst_mat_budg->SetMarkerStyle(24);
   syst_mat_budg->SetMarkerSize(1.1);
   syst_mat_budg->GetXaxis()->SetLabelFont(42);
   syst_mat_budg->GetXaxis()->SetLabelSize(0.035);
   syst_mat_budg->GetXaxis()->SetTitleSize(0.035);
   syst_mat_budg->GetXaxis()->SetTitleFont(42);
   syst_mat_budg->GetYaxis()->SetLabelFont(42);
   syst_mat_budg->GetYaxis()->SetLabelSize(0.035);
   syst_mat_budg->GetYaxis()->SetTitleSize(0.035);
   syst_mat_budg->GetYaxis()->SetTitleFont(42);
   syst_mat_budg->GetZaxis()->SetLabelFont(42);
   syst_mat_budg->GetZaxis()->SetLabelSize(0.035);
   syst_mat_budg->GetZaxis()->SetTitleSize(0.035);
   syst_mat_budg->GetZaxis()->SetTitleFont(42);
   syst_mat_budg->Draw("CPsame");
   Double_t xAxis26[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_gam_bias = new TH1D("syst_gam_bias","",9, xAxis26);
   syst_gam_bias->SetBinContent(1,2);
   syst_gam_bias->SetBinContent(2,2);
   syst_gam_bias->SetBinContent(3,2);
   syst_gam_bias->SetBinContent(4,2);
   syst_gam_bias->SetBinContent(5,2);
   syst_gam_bias->SetBinContent(6,2);
   syst_gam_bias->SetBinContent(7,2);
   syst_gam_bias->SetBinContent(8,2);
   syst_gam_bias->SetBinContent(9,2);
   syst_gam_bias->SetEntries(9);

   ci = TColor::GetColor("#ff0033");
   syst_gam_bias->SetFillColor(ci);
   syst_gam_bias->SetFillStyle(0);

   ci = TColor::GetColor("#ff0033");
   syst_gam_bias->SetLineColor(ci);
   syst_gam_bias->SetLineWidth(2);

   ci = TColor::GetColor("#ff0033");
   syst_gam_bias->SetMarkerColor(ci);
   syst_gam_bias->SetMarkerStyle(27);
   syst_gam_bias->SetMarkerSize(1.54);
   syst_gam_bias->GetXaxis()->SetLabelFont(42);
   syst_gam_bias->GetXaxis()->SetLabelSize(0.035);
   syst_gam_bias->GetXaxis()->SetTitleSize(0.035);
   syst_gam_bias->GetXaxis()->SetTitleFont(42);
   syst_gam_bias->GetYaxis()->SetLabelFont(42);
   syst_gam_bias->GetYaxis()->SetLabelSize(0.035);
   syst_gam_bias->GetYaxis()->SetTitleSize(0.035);
   syst_gam_bias->GetYaxis()->SetTitleFont(42);
   syst_gam_bias->GetZaxis()->SetLabelFont(42);
   syst_gam_bias->GetZaxis()->SetLabelSize(0.035);
   syst_gam_bias->GetZaxis()->SetTitleSize(0.035);
   syst_gam_bias->GetZaxis()->SetTitleFont(42);
   syst_gam_bias->Draw("CPsame");
   Double_t xAxis27[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_eff_stability = new TH1D("syst_eff_stability","",9, xAxis27);
   syst_eff_stability->SetBinContent(1,5.1);
   syst_eff_stability->SetBinContent(2,5.1);
   syst_eff_stability->SetBinContent(3,5.1);
   syst_eff_stability->SetBinContent(4,5.1);
   syst_eff_stability->SetBinContent(5,5.1);
   syst_eff_stability->SetBinContent(6,5.1);
   syst_eff_stability->SetBinContent(7,5.1);
   syst_eff_stability->SetBinContent(8,5.1);
   syst_eff_stability->SetBinContent(9,5.1);
   syst_eff_stability->SetEntries(9);

   ci = TColor::GetColor("#996633");
   syst_eff_stability->SetFillColor(ci);
   syst_eff_stability->SetFillStyle(0);

   ci = TColor::GetColor("#996633");
   syst_eff_stability->SetLineColor(ci);
   syst_eff_stability->SetLineWidth(2);

   ci = TColor::GetColor("#996633");
   syst_eff_stability->SetMarkerColor(ci);
   syst_eff_stability->SetMarkerStyle(27);
   syst_eff_stability->SetMarkerSize(1.54);
   syst_eff_stability->GetXaxis()->SetLabelFont(42);
   syst_eff_stability->GetXaxis()->SetLabelSize(0.035);
   syst_eff_stability->GetXaxis()->SetTitleSize(0.035);
   syst_eff_stability->GetXaxis()->SetTitleFont(42);
   syst_eff_stability->GetYaxis()->SetLabelFont(42);
   syst_eff_stability->GetYaxis()->SetLabelSize(0.035);
   syst_eff_stability->GetYaxis()->SetTitleSize(0.035);
   syst_eff_stability->GetYaxis()->SetTitleFont(42);
   syst_eff_stability->GetZaxis()->SetLabelFont(42);
   syst_eff_stability->GetZaxis()->SetLabelSize(0.035);
   syst_eff_stability->GetZaxis()->SetTitleSize(0.035);
   syst_eff_stability->GetZaxis()->SetTitleFont(42);
   syst_eff_stability->Draw("CPsame");
   Double_t xAxis28[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *cross_section_syst_total = new TH1D("cross_section_syst_total","",9, xAxis28);
   cross_section_syst_total->SetBinContent(1,23.45859);
   cross_section_syst_total->SetBinContent(2,21.43152);
   cross_section_syst_total->SetBinContent(3,19.47045);
   cross_section_syst_total->SetBinContent(4,17.59646);
   cross_section_syst_total->SetBinContent(5,16.58282);
   cross_section_syst_total->SetBinContent(6,16.85334);
   cross_section_syst_total->SetBinContent(7,17.2682);
   cross_section_syst_total->SetBinContent(8,17.92891);
   cross_section_syst_total->SetBinContent(9,19.28681);
   cross_section_syst_total->SetEntries(9);
   cross_section_syst_total->SetFillColor(1);
   cross_section_syst_total->SetFillStyle(0);
   cross_section_syst_total->SetLineWidth(2);
   cross_section_syst_total->SetMarkerStyle(24);
   cross_section_syst_total->SetMarkerSize(1.1);
   cross_section_syst_total->GetXaxis()->SetLabelFont(42);
   cross_section_syst_total->GetXaxis()->SetLabelSize(0.035);
   cross_section_syst_total->GetXaxis()->SetTitleSize(0.035);
   cross_section_syst_total->GetXaxis()->SetTitleFont(42);
   cross_section_syst_total->GetYaxis()->SetLabelFont(42);
   cross_section_syst_total->GetYaxis()->SetLabelSize(0.035);
   cross_section_syst_total->GetYaxis()->SetTitleSize(0.035);
   cross_section_syst_total->GetYaxis()->SetTitleFont(42);
   cross_section_syst_total->GetZaxis()->SetLabelFont(42);
   cross_section_syst_total->GetZaxis()->SetLabelSize(0.035);
   cross_section_syst_total->GetZaxis()->SetTitleSize(0.035);
   cross_section_syst_total->GetZaxis()->SetTitleFont(42);
   cross_section_syst_total->Draw("CPsame");
   
   TLegend *leg = new TLegend(-2.353437e-185,-2.353437e-185,-2.353437e-185,-2.353437e-185,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(23);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("syst_CPV","Charged particle veto","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("syst_no_smearing_final","No MC tuning","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("syst_sigma_long_sig_shift","Signal #sigma_{long}^{2} cut","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("syst_nlm","Number of local max.","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("syst_sigma_long_bkg_shift","Background #sigma_{long}^{2} cut","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("syst_combined_iso_prob","Isolation probability","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("syst_gamma_jet_weight","MC signal amount","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("syst_nonlinscaling","Energy scale","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("syst_gam_bias","MC #gamma enhancement bias","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("syst_eff_stability","Trigger stability","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("syst_mat_budg","Material budget","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("cross_section_syst_total","Total syst. unc.","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.177,0.888,"ALICE, pp #sqrt{#it{s}} = 7 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(28);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__58 = new TH1F("hframe__58","",1000,8,62);
   hframe__58->SetMinimum(0);
   hframe__58->SetMaximum(48);
   hframe__58->SetDirectory(0);
   hframe__58->SetStats(0);
   hframe__58->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__58->GetXaxis()->SetNdivisions(506);
   hframe__58->GetXaxis()->SetLabelFont(43);
   hframe__58->GetXaxis()->SetLabelSize(25.84615);
   hframe__58->GetXaxis()->SetTitleSize(28);
   hframe__58->GetXaxis()->SetTitleOffset(1.1);
   hframe__58->GetXaxis()->SetTitleFont(43);
   hframe__58->GetYaxis()->SetTitle("Cross Section Systematic Uncertainty (%)");
   hframe__58->GetYaxis()->SetNdivisions(505);
   hframe__58->GetYaxis()->SetLabelFont(43);
   hframe__58->GetYaxis()->SetLabelSize(25.84615);
   hframe__58->GetYaxis()->SetTitleSize(28);
   hframe__58->GetYaxis()->SetTitleOffset(1.26);
   hframe__58->GetYaxis()->SetTitleFont(43);
   hframe__58->GetZaxis()->SetLabelFont(43);
   hframe__58->GetZaxis()->SetLabelSize(25.84615);
   hframe__58->GetZaxis()->SetTitleOffset(1.1);
   hframe__58->GetZaxis()->SetTitleFont(43);
   hframe__58->Draw("sameaxis");
   c_total_syst->Modified();
   c_total_syst->cd();
   c_total_syst->SetSelected(c_total_syst);
}
