{
//=========Macro generated from canvas: c_cross_section_variations_to_std/SumPtUE
//=========  (Wed May 29 06:56:07 2019) by ROOT version5.34/30
   TCanvas *c_cross_section_variations_to_std = new TCanvas("c_cross_section_variations_to_std", "SumPtUE",0,64,1200,1200);
   gStyle->SetOptStat(0);
   c_cross_section_variations_to_std->SetHighLightColor(2);
   c_cross_section_variations_to_std->Range(0,0,1,1);
   c_cross_section_variations_to_std->SetFillColor(10);
   c_cross_section_variations_to_std->SetBorderMode(0);
   c_cross_section_variations_to_std->SetBorderSize(2);
   c_cross_section_variations_to_std->SetTickx(1);
   c_cross_section_variations_to_std->SetTicky(1);
   c_cross_section_variations_to_std->SetLeftMargin(0.126);
   c_cross_section_variations_to_std->SetRightMargin(0.005);
   c_cross_section_variations_to_std->SetTopMargin(0.017);
   c_cross_section_variations_to_std->SetBottomMargin(0.089);
   c_cross_section_variations_to_std->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_cross_section_variations_to_std_TOP_pad
   TPad *c_cross_section_variations_to_std_TOP_pad = new TPad("c_cross_section_variations_to_std_TOP_pad", "c_cross_section_variations_to_std_TOP_pad",0,0.5,1,1);
   c_cross_section_variations_to_std_TOP_pad->Draw();
   c_cross_section_variations_to_std_TOP_pad->cd();
   c_cross_section_variations_to_std_TOP_pad->Range(0,0,1,1);
   c_cross_section_variations_to_std_TOP_pad->SetFillColor(0);
   c_cross_section_variations_to_std_TOP_pad->SetBorderMode(0);
   c_cross_section_variations_to_std_TOP_pad->SetBorderSize(2);
   c_cross_section_variations_to_std_TOP_pad->SetTickx(1);
   c_cross_section_variations_to_std_TOP_pad->SetTicky(1);
   c_cross_section_variations_to_std_TOP_pad->SetLeftMargin(0.18);
   c_cross_section_variations_to_std_TOP_pad->SetRightMargin(0.01);
   c_cross_section_variations_to_std_TOP_pad->SetTopMargin(0.03);
   c_cross_section_variations_to_std_TOP_pad->SetBottomMargin(0.025);
   c_cross_section_variations_to_std_TOP_pad->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: cross_section_sigma_long_sig_shift_pad
   cross_section_sigma_long_sig_shift_pad = new TPad("cross_section_sigma_long_sig_shift_pad", "cross_section_sigma_long_sig_shift_pad",0,0.3,0.3333333,1);
   cross_section_sigma_long_sig_shift_pad->Draw();
   cross_section_sigma_long_sig_shift_pad->cd();
   cross_section_sigma_long_sig_shift_pad->Range(-4,-1.655154,62.66667,3.635851);
   cross_section_sigma_long_sig_shift_pad->SetFillColor(0);
   cross_section_sigma_long_sig_shift_pad->SetBorderMode(0);
   cross_section_sigma_long_sig_shift_pad->SetBorderSize(2);
   cross_section_sigma_long_sig_shift_pad->SetLogy();
   cross_section_sigma_long_sig_shift_pad->SetTickx(1);
   cross_section_sigma_long_sig_shift_pad->SetTicky(1);
   cross_section_sigma_long_sig_shift_pad->SetLeftMargin(0.18);
   cross_section_sigma_long_sig_shift_pad->SetRightMargin(0.01);
   cross_section_sigma_long_sig_shift_pad->SetTopMargin(0.03);
   cross_section_sigma_long_sig_shift_pad->SetBottomMargin(0.025);
   cross_section_sigma_long_sig_shift_pad->SetFrameBorderMode(0);
   cross_section_sigma_long_sig_shift_pad->SetFrameBorderMode(0);
   
   TH1F *hframe__1 = new TH1F("hframe__1","",1000,8,62);
   hframe__1->SetMinimum(0.03);
   hframe__1->SetMaximum(3000);
   hframe__1->SetDirectory(0);
   hframe__1->SetStats(0);
   hframe__1->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__1->GetXaxis()->SetNdivisions(506);
   hframe__1->GetXaxis()->SetLabelFont(43);
   hframe__1->GetXaxis()->SetLabelOffset(999);
   hframe__1->GetXaxis()->SetLabelSize(0);
   hframe__1->GetXaxis()->SetTitleSize(18);
   hframe__1->GetXaxis()->SetTitleOffset(4);
   hframe__1->GetXaxis()->SetTitleFont(43);
   hframe__1->GetYaxis()->SetTitle("d^{2}#sigma/d#it{p}_{T}d#it{#eta} (nb GeV^{-1}#it{c})");
   hframe__1->GetYaxis()->SetNdivisions(506);
   hframe__1->GetYaxis()->SetLabelFont(43);
   hframe__1->GetYaxis()->SetLabelSize(18);
   hframe__1->GetYaxis()->SetTitleSize(18);
   hframe__1->GetYaxis()->SetTitleOffset(5.5);
   hframe__1->GetYaxis()->SetTitleFont(43);
   hframe__1->GetZaxis()->SetLabelFont(43);
   hframe__1->GetZaxis()->SetLabelSize(18);
   hframe__1->GetZaxis()->SetTitleOffset(1.1);
   hframe__1->GetZaxis()->SetTitleFont(43);
   hframe__1->Draw(" ");
   
   TGraphErrors *gre = new TGraphErrors(9);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetFillStyle(0);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,32.1326);
   gre->SetPointError(0,1,6.4177);
   gre->SetPoint(1,13,17.8523);
   gre->SetPointError(1,1,3.68763);
   gre->SetPoint(2,15,12.4859);
   gre->SetPointError(2,1,1.52171);
   gre->SetPoint(3,17,5.75182);
   gre->SetPointError(3,1,0.915476);
   gre->SetPoint(4,19,4.81785);
   gre->SetPointError(4,1,0.732516);
   gre->SetPoint(5,22.5,2.09243);
   gre->SetPointError(5,2.5,0.315706);
   gre->SetPoint(6,27.5,0.794539);
   gre->SetPointError(6,2.5,0.200054);
   gre->SetPoint(7,35,0.306897);
   gre->SetPointError(7,5,0.0931315);
   gre->SetPoint(8,50,0.0751043);
   gre->SetPointError(8,10,0.03028);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","Graph",100,5,65);
   Graph_Graph1->SetMinimum(0.04034187);
   Graph_Graph1->SetMaximum(42.40085);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);
   Graph_Graph1->GetXaxis()->SetNdivisions(506);
   Graph_Graph1->GetXaxis()->SetLabelFont(43);
   Graph_Graph1->GetXaxis()->SetLabelSize(18);
   Graph_Graph1->GetXaxis()->SetTitleSize(18);
   Graph_Graph1->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph1->GetXaxis()->SetTitleFont(43);
   Graph_Graph1->GetYaxis()->SetNdivisions(506);
   Graph_Graph1->GetYaxis()->SetLabelFont(43);
   Graph_Graph1->GetYaxis()->SetLabelSize(18);
   Graph_Graph1->GetYaxis()->SetTitleSize(18);
   Graph_Graph1->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph1->GetYaxis()->SetTitleFont(43);
   Graph_Graph1->GetZaxis()->SetLabelFont(43);
   Graph_Graph1->GetZaxis()->SetLabelSize(18);
   Graph_Graph1->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph1->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph1);
   
   gre->Draw("ep");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph1");
   gre->SetTitle("Graph");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#cccc33");
   gre->SetFillColor(ci);
   gre->SetFillStyle(0);

   ci = TColor::GetColor("#cccc33");
   gre->SetLineColor(ci);

   ci = TColor::GetColor("#cccc33");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,31.0868);
   gre->SetPointError(0,1,6.26029);
   gre->SetPoint(1,13,18.4185);
   gre->SetPointError(1,1,3.56482);
   gre->SetPoint(2,15,11.7925);
   gre->SetPointError(2,1,1.4782);
   gre->SetPoint(3,17,5.58154);
   gre->SetPointError(3,1,0.926439);
   gre->SetPoint(4,19,4.64867);
   gre->SetPointError(4,1,0.710266);
   gre->SetPoint(5,22.5,2.08649);
   gre->SetPointError(5,2.5,0.308304);
   gre->SetPoint(6,27.5,0.897624);
   gre->SetPointError(6,2.5,0.178834);
   gre->SetPoint(7,35,0.341919);
   gre->SetPointError(7,5,0.08711);
   gre->SetPoint(8,50,0.0803398);
   gre->SetPointError(8,10,0.0282627);
   
   TH1F *Graph_Graph2 = new TH1F("Graph_Graph2","Graph",100,5,65);
   Graph_Graph2->SetMinimum(0.04686939);
   Graph_Graph2->SetMaximum(41.07659);
   Graph_Graph2->SetDirectory(0);
   Graph_Graph2->SetStats(0);
   Graph_Graph2->GetXaxis()->SetNdivisions(506);
   Graph_Graph2->GetXaxis()->SetLabelFont(43);
   Graph_Graph2->GetXaxis()->SetLabelSize(18);
   Graph_Graph2->GetXaxis()->SetTitleSize(18);
   Graph_Graph2->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph2->GetXaxis()->SetTitleFont(43);
   Graph_Graph2->GetYaxis()->SetNdivisions(506);
   Graph_Graph2->GetYaxis()->SetLabelFont(43);
   Graph_Graph2->GetYaxis()->SetLabelSize(18);
   Graph_Graph2->GetYaxis()->SetTitleSize(18);
   Graph_Graph2->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph2->GetYaxis()->SetTitleFont(43);
   Graph_Graph2->GetZaxis()->SetLabelFont(43);
   Graph_Graph2->GetZaxis()->SetLabelSize(18);
   Graph_Graph2->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph2->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph2);
   
   gre->Draw("ep");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph2");
   gre->SetTitle("Graph");

   ci = TColor::GetColor("#99cc99");
   gre->SetFillColor(ci);
   gre->SetFillStyle(0);

   ci = TColor::GetColor("#99cc99");
   gre->SetLineColor(ci);

   ci = TColor::GetColor("#99cc99");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,33.1853);
   gre->SetPointError(0,1,6.67089);
   gre->SetPoint(1,13,17.8261);
   gre->SetPointError(1,1,3.89694);
   gre->SetPoint(2,15,12.8927);
   gre->SetPointError(2,1,1.62572);
   gre->SetPoint(3,17,5.67653);
   gre->SetPointError(3,1,1.03483);
   gre->SetPoint(4,19,5.19521);
   gre->SetPointError(4,1,0.848291);
   gre->SetPoint(5,22.5,1.99068);
   gre->SetPointError(5,2.5,0.392867);
   gre->SetPoint(6,27.5,0.879148);
   gre->SetPointError(6,2.5,0.263672);
   gre->SetPoint(7,35,0.281196);
   gre->SetPointError(7,5,0.108994);
   gre->SetPoint(8,50,0.073574);
   gre->SetPointError(8,10,0.0373904);
   
   TH1F *Graph_Graph3 = new TH1F("Graph_Graph3","Graph",100,5,65);
   Graph_Graph3->SetMinimum(0.03256524);
   Graph_Graph3->SetMaximum(43.83819);
   Graph_Graph3->SetDirectory(0);
   Graph_Graph3->SetStats(0);
   Graph_Graph3->GetXaxis()->SetNdivisions(506);
   Graph_Graph3->GetXaxis()->SetLabelFont(43);
   Graph_Graph3->GetXaxis()->SetLabelSize(18);
   Graph_Graph3->GetXaxis()->SetTitleSize(18);
   Graph_Graph3->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph3->GetXaxis()->SetTitleFont(43);
   Graph_Graph3->GetYaxis()->SetNdivisions(506);
   Graph_Graph3->GetYaxis()->SetLabelFont(43);
   Graph_Graph3->GetYaxis()->SetLabelSize(18);
   Graph_Graph3->GetYaxis()->SetTitleSize(18);
   Graph_Graph3->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph3->GetYaxis()->SetTitleFont(43);
   Graph_Graph3->GetZaxis()->SetLabelFont(43);
   Graph_Graph3->GetZaxis()->SetLabelSize(18);
   Graph_Graph3->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph3->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph3);
   
   gre->Draw("ep");
   
   TLegend *leg = new TLegend(0.235,0.7,0.635,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(16);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("Graph0","Standard sig. #sigma_{long}^{2} cut","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("Graph1","Sig. #sigma_{long}^{2} cut lowered","lep");

   ci = TColor::GetColor("#cccc33");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#cccc33");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("Graph2","Sig. #sigma_{long}^{2} cut raised","lep");

   ci = TColor::GetColor("#99cc99");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#99cc99");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   leg->Draw();
   TLatex *   tex = new TLatex(0.245,0.87,"Signal #sigma_{long}^{2} cut variation");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(18);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__2 = new TH1F("hframe__2","",1000,8,62);
   hframe__2->SetMinimum(0.03);
   hframe__2->SetMaximum(3000);
   hframe__2->SetDirectory(0);
   hframe__2->SetStats(0);
   hframe__2->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__2->GetXaxis()->SetNdivisions(506);
   hframe__2->GetXaxis()->SetLabelFont(43);
   hframe__2->GetXaxis()->SetLabelOffset(999);
   hframe__2->GetXaxis()->SetLabelSize(0);
   hframe__2->GetXaxis()->SetTitleSize(18);
   hframe__2->GetXaxis()->SetTitleOffset(4);
   hframe__2->GetXaxis()->SetTitleFont(43);
   hframe__2->GetYaxis()->SetTitle("d^{2}#sigma/d#it{p}_{T}d#it{#eta} (nb GeV^{-1}#it{c})");
   hframe__2->GetYaxis()->SetNdivisions(506);
   hframe__2->GetYaxis()->SetLabelFont(43);
   hframe__2->GetYaxis()->SetLabelSize(18);
   hframe__2->GetYaxis()->SetTitleSize(18);
   hframe__2->GetYaxis()->SetTitleOffset(5.5);
   hframe__2->GetYaxis()->SetTitleFont(43);
   hframe__2->GetZaxis()->SetLabelFont(43);
   hframe__2->GetZaxis()->SetLabelSize(18);
   hframe__2->GetZaxis()->SetTitleOffset(1.1);
   hframe__2->GetZaxis()->SetTitleFont(43);
   hframe__2->Draw("sameaxis");
   cross_section_sigma_long_sig_shift_pad->Modified();
   c_cross_section_variations_to_std_TOP_pad->cd();
  
// ------------>Primitives in pad: syst_sigma_long_sig_shift_pad
   syst_sigma_long_sig_shift_pad = new TPad("syst_sigma_long_sig_shift_pad", "syst_sigma_long_sig_shift_pad",0,0,0.3333333,0.3);
   syst_sigma_long_sig_shift_pad->Draw();
   syst_sigma_long_sig_shift_pad->cd();
   syst_sigma_long_sig_shift_pad->Range(-4,-27.48005,62.66667,17.56922);
   syst_sigma_long_sig_shift_pad->SetFillColor(0);
   syst_sigma_long_sig_shift_pad->SetBorderMode(0);
   syst_sigma_long_sig_shift_pad->SetBorderSize(2);
   syst_sigma_long_sig_shift_pad->SetTickx(1);
   syst_sigma_long_sig_shift_pad->SetTicky(1);
   syst_sigma_long_sig_shift_pad->SetLeftMargin(0.18);
   syst_sigma_long_sig_shift_pad->SetRightMargin(0.01);
   syst_sigma_long_sig_shift_pad->SetTopMargin(0.03);
   syst_sigma_long_sig_shift_pad->SetBottomMargin(0.25);
   syst_sigma_long_sig_shift_pad->SetFrameBorderMode(0);
   syst_sigma_long_sig_shift_pad->SetFrameBorderMode(0);
   
   TH1F *hframe__3 = new TH1F("hframe__3","",1000,8,62);
   hframe__3->SetMinimum(-16.21774);
   hframe__3->SetMaximum(16.21774);
   hframe__3->SetDirectory(0);
   hframe__3->SetStats(0);
   hframe__3->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__3->GetXaxis()->SetNdivisions(506);
   hframe__3->GetXaxis()->SetLabelFont(43);
   hframe__3->GetXaxis()->SetLabelSize(18);
   hframe__3->GetXaxis()->SetTitleSize(18);
   hframe__3->GetXaxis()->SetTickLength(0.07);
   hframe__3->GetXaxis()->SetTitleOffset(7.5);
   hframe__3->GetXaxis()->SetTitleFont(43);
   hframe__3->GetYaxis()->SetTitle("Rel. diff. (%)");
   hframe__3->GetYaxis()->SetNdivisions(506);
   hframe__3->GetYaxis()->SetLabelFont(43);
   hframe__3->GetYaxis()->SetLabelSize(18);
   hframe__3->GetYaxis()->SetTitleSize(18);
   hframe__3->GetYaxis()->SetTitleOffset(5.5);
   hframe__3->GetYaxis()->SetTitleFont(43);
   hframe__3->GetZaxis()->SetLabelFont(43);
   hframe__3->GetZaxis()->SetLabelSize(18);
   hframe__3->GetZaxis()->SetTitleOffset(1.1);
   hframe__3->GetZaxis()->SetTitleFont(43);
   hframe__3->Draw(" ");
   TLine *line = new TLine(0.18,0.61,0.99,0.61);
   line->SetLineStyle(3);
   line->Draw();
   Double_t xAxis1[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_sigma_long_sig_shift_min = new TH1D("syst_sigma_long_sig_shift_min","",9, xAxis1);
   syst_sigma_long_sig_shift_min->SetBinContent(1,-3.254639);
   syst_sigma_long_sig_shift_min->SetBinContent(2,3.17158);
   syst_sigma_long_sig_shift_min->SetBinContent(3,-5.553464);
   syst_sigma_long_sig_shift_min->SetBinContent(4,-2.960454);
   syst_sigma_long_sig_shift_min->SetBinContent(5,-3.511525);
   syst_sigma_long_sig_shift_min->SetBinContent(6,-0.2838805);
   syst_sigma_long_sig_shift_min->SetBinContent(7,12.97419);
   syst_sigma_long_sig_shift_min->SetBinContent(8,11.41165);
   syst_sigma_long_sig_shift_min->SetBinContent(9,6.970972);
   syst_sigma_long_sig_shift_min->SetBinError(1,4.300302);
   syst_sigma_long_sig_shift_min->SetBinError(2,5.490772);
   syst_sigma_long_sig_shift_min->SetBinError(3,2.810819);
   syst_sigma_long_sig_shift_min->SetBinError(4,2.349515);
   syst_sigma_long_sig_shift_min->SetBinError(5,3.625441);
   syst_sigma_long_sig_shift_min->SetBinError(6,3.239075);
   syst_sigma_long_sig_shift_min->SetBinError(7,13.07963);
   syst_sigma_long_sig_shift_min->SetBinError(8,12.3905);
   syst_sigma_long_sig_shift_min->SetBinError(9,15.699);
   syst_sigma_long_sig_shift_min->SetEntries(0.5476139);

   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift_min->SetFillColor(ci);
   syst_sigma_long_sig_shift_min->SetFillStyle(0);

   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift_min->SetLineColor(ci);

   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift_min->SetMarkerColor(ci);
   syst_sigma_long_sig_shift_min->SetMarkerSize(1.1);
   syst_sigma_long_sig_shift_min->GetXaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift_min->GetXaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift_min->GetXaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift_min->GetXaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift_min->GetYaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift_min->GetYaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift_min->GetYaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift_min->GetYaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift_min->GetZaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift_min->GetZaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift_min->GetZaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift_min->GetZaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift_min->Draw("hist][same");
   Double_t xAxis2[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_sigma_long_sig_shift_max = new TH1D("syst_sigma_long_sig_shift_max","",9, xAxis2);
   syst_sigma_long_sig_shift_max->SetBinContent(1,3.276112);
   syst_sigma_long_sig_shift_max->SetBinContent(2,-0.1467598);
   syst_sigma_long_sig_shift_max->SetBinContent(3,3.258075);
   syst_sigma_long_sig_shift_max->SetBinContent(4,-1.308977);
   syst_sigma_long_sig_shift_max->SetBinContent(5,7.832539);
   syst_sigma_long_sig_shift_max->SetBinContent(6,-4.862767);
   syst_sigma_long_sig_shift_max->SetBinContent(7,10.64882);
   syst_sigma_long_sig_shift_max->SetBinContent(8,-8.374471);
   syst_sigma_long_sig_shift_max->SetBinContent(9,-2.037566);
   syst_sigma_long_sig_shift_max->SetBinError(1,5.811248);
   syst_sigma_long_sig_shift_max->SetBinError(2,7.04732);
   syst_sigma_long_sig_shift_max->SetBinError(3,4.712673);
   syst_sigma_long_sig_shift_max->SetBinError(4,8.27497);
   syst_sigma_long_sig_shift_max->SetBinError(5,9.475266);
   syst_sigma_long_sig_shift_max->SetBinError(6,10.59213);
   syst_sigma_long_sig_shift_max->SetBinError(7,23.65702);
   syst_sigma_long_sig_shift_max->SetBinError(8,16.64151);
   syst_sigma_long_sig_shift_max->SetBinError(9,28.59355);
   syst_sigma_long_sig_shift_max->SetEntries(0.03380878);

   ci = TColor::GetColor("#99cc99");
   syst_sigma_long_sig_shift_max->SetFillColor(ci);
   syst_sigma_long_sig_shift_max->SetFillStyle(0);

   ci = TColor::GetColor("#99cc99");
   syst_sigma_long_sig_shift_max->SetLineColor(ci);

   ci = TColor::GetColor("#99cc99");
   syst_sigma_long_sig_shift_max->SetMarkerColor(ci);
   syst_sigma_long_sig_shift_max->SetMarkerSize(1.1);
   syst_sigma_long_sig_shift_max->GetXaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift_max->GetXaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift_max->GetXaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift_max->GetXaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift_max->GetYaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift_max->GetYaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift_max->GetYaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift_max->GetYaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift_max->GetZaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift_max->GetZaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift_max->GetZaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift_max->GetZaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift_max->Draw("hist][same");
   
   TH1F *hframe__4 = new TH1F("hframe__4","",1000,8,62);
   hframe__4->SetMinimum(-16.21774);
   hframe__4->SetMaximum(16.21774);
   hframe__4->SetDirectory(0);
   hframe__4->SetStats(0);
   hframe__4->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__4->GetXaxis()->SetNdivisions(506);
   hframe__4->GetXaxis()->SetLabelFont(43);
   hframe__4->GetXaxis()->SetLabelSize(18);
   hframe__4->GetXaxis()->SetTitleSize(18);
   hframe__4->GetXaxis()->SetTickLength(0.07);
   hframe__4->GetXaxis()->SetTitleOffset(7.5);
   hframe__4->GetXaxis()->SetTitleFont(43);
   hframe__4->GetYaxis()->SetTitle("Rel. diff. (%)");
   hframe__4->GetYaxis()->SetNdivisions(506);
   hframe__4->GetYaxis()->SetLabelFont(43);
   hframe__4->GetYaxis()->SetLabelSize(18);
   hframe__4->GetYaxis()->SetTitleSize(18);
   hframe__4->GetYaxis()->SetTitleOffset(5.5);
   hframe__4->GetYaxis()->SetTitleFont(43);
   hframe__4->GetZaxis()->SetLabelFont(43);
   hframe__4->GetZaxis()->SetLabelSize(18);
   hframe__4->GetZaxis()->SetTitleOffset(1.1);
   hframe__4->GetZaxis()->SetTitleFont(43);
   hframe__4->Draw("sameaxis");
   syst_sigma_long_sig_shift_pad->Modified();
   c_cross_section_variations_to_std_TOP_pad->cd();
  
// ------------>Primitives in pad: cross_section_sigma_long_bkg_shift_pad
   cross_section_sigma_long_bkg_shift_pad = new TPad("cross_section_sigma_long_bkg_shift_pad", "cross_section_sigma_long_bkg_shift_pad",0.3333333,0.3,0.6666667,1);
   cross_section_sigma_long_bkg_shift_pad->Draw();
   cross_section_sigma_long_bkg_shift_pad->cd();
   cross_section_sigma_long_bkg_shift_pad->Range(-4,-1.655154,62.66667,3.635851);
   cross_section_sigma_long_bkg_shift_pad->SetFillColor(0);
   cross_section_sigma_long_bkg_shift_pad->SetBorderMode(0);
   cross_section_sigma_long_bkg_shift_pad->SetBorderSize(2);
   cross_section_sigma_long_bkg_shift_pad->SetLogy();
   cross_section_sigma_long_bkg_shift_pad->SetTickx(1);
   cross_section_sigma_long_bkg_shift_pad->SetTicky(1);
   cross_section_sigma_long_bkg_shift_pad->SetLeftMargin(0.18);
   cross_section_sigma_long_bkg_shift_pad->SetRightMargin(0.01);
   cross_section_sigma_long_bkg_shift_pad->SetTopMargin(0.03);
   cross_section_sigma_long_bkg_shift_pad->SetBottomMargin(0.025);
   cross_section_sigma_long_bkg_shift_pad->SetFrameBorderMode(0);
   cross_section_sigma_long_bkg_shift_pad->SetFrameBorderMode(0);
   
   TH1F *hframe__5 = new TH1F("hframe__5","",1000,8,62);
   hframe__5->SetMinimum(0.03);
   hframe__5->SetMaximum(3000);
   hframe__5->SetDirectory(0);
   hframe__5->SetStats(0);
   hframe__5->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__5->GetXaxis()->SetNdivisions(506);
   hframe__5->GetXaxis()->SetLabelFont(43);
   hframe__5->GetXaxis()->SetLabelOffset(999);
   hframe__5->GetXaxis()->SetLabelSize(0);
   hframe__5->GetXaxis()->SetTitleSize(18);
   hframe__5->GetXaxis()->SetTitleOffset(7.5);
   hframe__5->GetXaxis()->SetTitleFont(43);
   hframe__5->GetYaxis()->SetTitle("d^{2}#sigma/d#it{p}_{T}d#it{#eta} (nb GeV^{-1}#it{c})");
   hframe__5->GetYaxis()->SetNdivisions(506);
   hframe__5->GetYaxis()->SetLabelFont(43);
   hframe__5->GetYaxis()->SetLabelSize(18);
   hframe__5->GetYaxis()->SetTitleSize(18);
   hframe__5->GetYaxis()->SetTitleOffset(5.5);
   hframe__5->GetYaxis()->SetTitleFont(43);
   hframe__5->GetZaxis()->SetLabelFont(43);
   hframe__5->GetZaxis()->SetLabelSize(18);
   hframe__5->GetZaxis()->SetTitleOffset(1.1);
   hframe__5->GetZaxis()->SetTitleFont(43);
   hframe__5->Draw(" ");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetFillStyle(0);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,32.1326);
   gre->SetPointError(0,1,6.4177);
   gre->SetPoint(1,13,17.8523);
   gre->SetPointError(1,1,3.68763);
   gre->SetPoint(2,15,12.4859);
   gre->SetPointError(2,1,1.52171);
   gre->SetPoint(3,17,5.75182);
   gre->SetPointError(3,1,0.915476);
   gre->SetPoint(4,19,4.81785);
   gre->SetPointError(4,1,0.732516);
   gre->SetPoint(5,22.5,2.09243);
   gre->SetPointError(5,2.5,0.315706);
   gre->SetPoint(6,27.5,0.794539);
   gre->SetPointError(6,2.5,0.200054);
   gre->SetPoint(7,35,0.306897);
   gre->SetPointError(7,5,0.0931315);
   gre->SetPoint(8,50,0.0751043);
   gre->SetPointError(8,10,0.03028);
   
   TH1F *Graph_Graph_Graph14 = new TH1F("Graph_Graph_Graph14","Graph",100,5,65);
   Graph_Graph_Graph14->SetMinimum(0.04034187);
   Graph_Graph_Graph14->SetMaximum(42.40085);
   Graph_Graph_Graph14->SetDirectory(0);
   Graph_Graph_Graph14->SetStats(0);
   Graph_Graph_Graph14->GetXaxis()->SetNdivisions(506);
   Graph_Graph_Graph14->GetXaxis()->SetLabelFont(43);
   Graph_Graph_Graph14->GetXaxis()->SetLabelSize(18);
   Graph_Graph_Graph14->GetXaxis()->SetTitleSize(18);
   Graph_Graph_Graph14->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph_Graph14->GetXaxis()->SetTitleFont(43);
   Graph_Graph_Graph14->GetYaxis()->SetNdivisions(506);
   Graph_Graph_Graph14->GetYaxis()->SetLabelFont(43);
   Graph_Graph_Graph14->GetYaxis()->SetLabelSize(18);
   Graph_Graph_Graph14->GetYaxis()->SetTitleSize(18);
   Graph_Graph_Graph14->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph_Graph14->GetYaxis()->SetTitleFont(43);
   Graph_Graph_Graph14->GetZaxis()->SetLabelFont(43);
   Graph_Graph_Graph14->GetZaxis()->SetLabelSize(18);
   Graph_Graph_Graph14->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph_Graph14->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph_Graph14);
   
   gre->Draw("ep");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");

   ci = TColor::GetColor("#9966cc");
   gre->SetFillColor(ci);
   gre->SetFillStyle(0);

   ci = TColor::GetColor("#9966cc");
   gre->SetLineColor(ci);

   ci = TColor::GetColor("#9966cc");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,31.9061);
   gre->SetPointError(0,1,6.40297);
   gre->SetPoint(1,13,17.6779);
   gre->SetPointError(1,1,3.67735);
   gre->SetPoint(2,15,12.2841);
   gre->SetPointError(2,1,1.51367);
   gre->SetPoint(3,17,5.71148);
   gre->SetPointError(3,1,0.909219);
   gre->SetPoint(4,19,4.67796);
   gre->SetPointError(4,1,0.730126);
   gre->SetPoint(5,22.5,2.08922);
   gre->SetPointError(5,2.5,0.308865);
   gre->SetPoint(6,27.5,0.763407);
   gre->SetPointError(6,2.5,0.193303);
   gre->SetPoint(7,35,0.322497);
   gre->SetPointError(7,5,0.0852944);
   gre->SetPoint(8,50,0.0731388);
   gre->SetPointError(8,10,0.0289014);
   
   TH1F *Graph_Graph5 = new TH1F("Graph_Graph5","Graph",100,5,65);
   Graph_Graph5->SetMinimum(0.03981366);
   Graph_Graph5->SetMaximum(42.13555);
   Graph_Graph5->SetDirectory(0);
   Graph_Graph5->SetStats(0);
   Graph_Graph5->GetXaxis()->SetNdivisions(506);
   Graph_Graph5->GetXaxis()->SetLabelFont(43);
   Graph_Graph5->GetXaxis()->SetLabelSize(18);
   Graph_Graph5->GetXaxis()->SetTitleSize(18);
   Graph_Graph5->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph5->GetXaxis()->SetTitleFont(43);
   Graph_Graph5->GetYaxis()->SetNdivisions(506);
   Graph_Graph5->GetYaxis()->SetLabelFont(43);
   Graph_Graph5->GetYaxis()->SetLabelSize(18);
   Graph_Graph5->GetYaxis()->SetTitleSize(18);
   Graph_Graph5->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph5->GetYaxis()->SetTitleFont(43);
   Graph_Graph5->GetZaxis()->SetLabelFont(43);
   Graph_Graph5->GetZaxis()->SetLabelSize(18);
   Graph_Graph5->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph5->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph5);
   
   gre->Draw("ep");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph1");
   gre->SetTitle("Graph");

   ci = TColor::GetColor("#ff9933");
   gre->SetFillColor(ci);
   gre->SetFillStyle(0);

   ci = TColor::GetColor("#ff9933");
   gre->SetLineColor(ci);

   ci = TColor::GetColor("#ff9933");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,31.6655);
   gre->SetPointError(0,1,6.47281);
   gre->SetPoint(1,13,18.2761);
   gre->SetPointError(1,1,3.69816);
   gre->SetPoint(2,15,12.4597);
   gre->SetPointError(2,1,1.53789);
   gre->SetPoint(3,17,5.81709);
   gre->SetPointError(3,1,0.927043);
   gre->SetPoint(4,19,4.88184);
   gre->SetPointError(4,1,0.744688);
   gre->SetPoint(5,22.5,2.10734);
   gre->SetPointError(5,2.5,0.32784);
   gre->SetPoint(6,27.5,0.721655);
   gre->SetPointError(6,2.5,0.223923);
   gre->SetPoint(7,35,0.27945);
   gre->SetPointError(7,5,0.102202);
   gre->SetPoint(8,50,0.0737406);
   gre->SetPointError(8,10,0.0313735);
   
   TH1F *Graph_Graph6 = new TH1F("Graph_Graph6","Graph",100,5,65);
   Graph_Graph6->SetMinimum(0.03813039);
   Graph_Graph6->SetMaximum(41.9479);
   Graph_Graph6->SetDirectory(0);
   Graph_Graph6->SetStats(0);
   Graph_Graph6->GetXaxis()->SetNdivisions(506);
   Graph_Graph6->GetXaxis()->SetLabelFont(43);
   Graph_Graph6->GetXaxis()->SetLabelSize(18);
   Graph_Graph6->GetXaxis()->SetTitleSize(18);
   Graph_Graph6->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph6->GetXaxis()->SetTitleFont(43);
   Graph_Graph6->GetYaxis()->SetNdivisions(506);
   Graph_Graph6->GetYaxis()->SetLabelFont(43);
   Graph_Graph6->GetYaxis()->SetLabelSize(18);
   Graph_Graph6->GetYaxis()->SetTitleSize(18);
   Graph_Graph6->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph6->GetYaxis()->SetTitleFont(43);
   Graph_Graph6->GetZaxis()->SetLabelFont(43);
   Graph_Graph6->GetZaxis()->SetLabelSize(18);
   Graph_Graph6->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph6->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph6);
   
   gre->Draw("ep");
   
   leg = new TLegend(0.235,0.7,0.635,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(16);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("Graph0","Standard bkg. #sigma_{long}^{2} cuts","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("Graph0","Bkg. #sigma_{long}^{2} cuts #minus gap","lep");

   ci = TColor::GetColor("#9966cc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#9966cc");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("Graph1","Bkg. #sigma_{long}^{2} cuts + gap","lep");

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#ff9933");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   leg->Draw();
      tex = new TLatex(0.245,0.87,"Background #sigma_{long}^{2} cut variation");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(18);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__6 = new TH1F("hframe__6","",1000,8,62);
   hframe__6->SetMinimum(0.03);
   hframe__6->SetMaximum(3000);
   hframe__6->SetDirectory(0);
   hframe__6->SetStats(0);
   hframe__6->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__6->GetXaxis()->SetNdivisions(506);
   hframe__6->GetXaxis()->SetLabelFont(43);
   hframe__6->GetXaxis()->SetLabelOffset(999);
   hframe__6->GetXaxis()->SetLabelSize(0);
   hframe__6->GetXaxis()->SetTitleSize(18);
   hframe__6->GetXaxis()->SetTitleOffset(7.5);
   hframe__6->GetXaxis()->SetTitleFont(43);
   hframe__6->GetYaxis()->SetTitle("d^{2}#sigma/d#it{p}_{T}d#it{#eta} (nb GeV^{-1}#it{c})");
   hframe__6->GetYaxis()->SetNdivisions(506);
   hframe__6->GetYaxis()->SetLabelFont(43);
   hframe__6->GetYaxis()->SetLabelSize(18);
   hframe__6->GetYaxis()->SetTitleSize(18);
   hframe__6->GetYaxis()->SetTitleOffset(5.5);
   hframe__6->GetYaxis()->SetTitleFont(43);
   hframe__6->GetZaxis()->SetLabelFont(43);
   hframe__6->GetZaxis()->SetLabelSize(18);
   hframe__6->GetZaxis()->SetTitleOffset(1.1);
   hframe__6->GetZaxis()->SetTitleFont(43);
   hframe__6->Draw("sameaxis");
   cross_section_sigma_long_bkg_shift_pad->Modified();
   c_cross_section_variations_to_std_TOP_pad->cd();
  
// ------------>Primitives in pad: syst_sigma_long_bkg_shift_pad
   syst_sigma_long_bkg_shift_pad = new TPad("syst_sigma_long_bkg_shift_pad", "syst_sigma_long_bkg_shift_pad",0.3333333,0,0.6666667,0.3);
   syst_sigma_long_bkg_shift_pad->Draw();
   syst_sigma_long_bkg_shift_pad->cd();
   syst_sigma_long_bkg_shift_pad->Range(-4,-19.42917,62.66667,12.42193);
   syst_sigma_long_bkg_shift_pad->SetFillColor(0);
   syst_sigma_long_bkg_shift_pad->SetBorderMode(0);
   syst_sigma_long_bkg_shift_pad->SetBorderSize(2);
   syst_sigma_long_bkg_shift_pad->SetTickx(1);
   syst_sigma_long_bkg_shift_pad->SetTicky(1);
   syst_sigma_long_bkg_shift_pad->SetLeftMargin(0.18);
   syst_sigma_long_bkg_shift_pad->SetRightMargin(0.01);
   syst_sigma_long_bkg_shift_pad->SetTopMargin(0.03);
   syst_sigma_long_bkg_shift_pad->SetBottomMargin(0.25);
   syst_sigma_long_bkg_shift_pad->SetFrameBorderMode(0);
   syst_sigma_long_bkg_shift_pad->SetFrameBorderMode(0);
   
   TH1F *hframe__7 = new TH1F("hframe__7","",1000,8,62);
   hframe__7->SetMinimum(-11.4664);
   hframe__7->SetMaximum(11.4664);
   hframe__7->SetDirectory(0);
   hframe__7->SetStats(0);
   hframe__7->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__7->GetXaxis()->SetNdivisions(506);
   hframe__7->GetXaxis()->SetLabelFont(43);
   hframe__7->GetXaxis()->SetLabelSize(18);
   hframe__7->GetXaxis()->SetTitleSize(18);
   hframe__7->GetXaxis()->SetTickLength(0.07);
   hframe__7->GetXaxis()->SetTitleOffset(7.5);
   hframe__7->GetXaxis()->SetTitleFont(43);
   hframe__7->GetYaxis()->SetTitle("Rel. diff. (%)");
   hframe__7->GetYaxis()->SetNdivisions(506);
   hframe__7->GetYaxis()->SetLabelFont(43);
   hframe__7->GetYaxis()->SetLabelSize(18);
   hframe__7->GetYaxis()->SetTitleSize(18);
   hframe__7->GetYaxis()->SetTitleOffset(5.5);
   hframe__7->GetYaxis()->SetTitleFont(43);
   hframe__7->GetZaxis()->SetLabelFont(43);
   hframe__7->GetZaxis()->SetLabelSize(18);
   hframe__7->GetZaxis()->SetTitleOffset(1.1);
   hframe__7->GetZaxis()->SetTitleFont(43);
   hframe__7->Draw(" ");
   line = new TLine(0.18,0.61,0.99,0.61);
   line->SetLineStyle(3);
   line->Draw();
   Double_t xAxis3[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_sigma_long_bkg_shift_min = new TH1D("syst_sigma_long_bkg_shift_min","",9, xAxis3);
   syst_sigma_long_bkg_shift_min->SetBinContent(1,-0.7048916);
   syst_sigma_long_bkg_shift_min->SetBinContent(2,-0.9769049);
   syst_sigma_long_bkg_shift_min->SetBinContent(3,-1.616223);
   syst_sigma_long_bkg_shift_min->SetBinContent(4,-0.7013432);
   syst_sigma_long_bkg_shift_min->SetBinContent(5,-2.903577);
   syst_sigma_long_bkg_shift_min->SetBinContent(6,-0.1534101);
   syst_sigma_long_bkg_shift_min->SetBinContent(7,-3.918247);
   syst_sigma_long_bkg_shift_min->SetBinContent(8,5.083139);
   syst_sigma_long_bkg_shift_min->SetBinContent(9,-2.617027);
   syst_sigma_long_bkg_shift_min->SetBinError(1,1.350211);
   syst_sigma_long_bkg_shift_min->SetBinError(2,1.539455);
   syst_sigma_long_bkg_shift_min->SetBinError(3,1.24644);
   syst_sigma_long_bkg_shift_min->SetBinError(4,1.847988);
   syst_sigma_long_bkg_shift_min->SetBinError(5,1.270217);
   syst_sigma_long_bkg_shift_min->SetBinError(6,3.119209);
   syst_sigma_long_bkg_shift_min->SetBinError(7,6.304142);
   syst_sigma_long_bkg_shift_min->SetBinError(8,12.88174);
   syst_sigma_long_bkg_shift_min->SetBinError(9,11.75519);
   syst_sigma_long_bkg_shift_min->SetEntries(8.508486);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift_min->SetFillColor(ci);
   syst_sigma_long_bkg_shift_min->SetFillStyle(0);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift_min->SetLineColor(ci);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift_min->SetMarkerColor(ci);
   syst_sigma_long_bkg_shift_min->SetMarkerSize(1.1);
   syst_sigma_long_bkg_shift_min->GetXaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift_min->GetXaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift_min->GetXaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift_min->GetXaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift_min->GetYaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift_min->GetYaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift_min->GetYaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift_min->GetYaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift_min->GetZaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift_min->GetZaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift_min->GetZaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift_min->GetZaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift_min->Draw("hist][same");
   Double_t xAxis4[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_sigma_long_bkg_shift_max = new TH1D("syst_sigma_long_bkg_shift_max","",9, xAxis4);
   syst_sigma_long_bkg_shift_max->SetBinContent(1,-1.453664);
   syst_sigma_long_bkg_shift_max->SetBinContent(2,2.373924);
   syst_sigma_long_bkg_shift_max->SetBinContent(3,-0.2098367);
   syst_sigma_long_bkg_shift_max->SetBinContent(4,1.134771);
   syst_sigma_long_bkg_shift_max->SetBinContent(5,1.328186);
   syst_sigma_long_bkg_shift_max->SetBinContent(6,0.7125686);
   syst_sigma_long_bkg_shift_max->SetBinContent(7,-9.173118);
   syst_sigma_long_bkg_shift_max->SetBinContent(8,-8.943391);
   syst_sigma_long_bkg_shift_max->SetBinContent(9,-1.815742);
   syst_sigma_long_bkg_shift_max->SetBinError(1,2.568267);
   syst_sigma_long_bkg_shift_max->SetBinError(2,1.521731);
   syst_sigma_long_bkg_shift_max->SetBinError(3,1.778048);
   syst_sigma_long_bkg_shift_max->SetBinError(4,2.560391);
   syst_sigma_long_bkg_shift_max->SetBinError(5,2.812707);
   syst_sigma_long_bkg_shift_max->SetBinError(6,4.25182);
   syst_sigma_long_bkg_shift_max->SetBinError(7,11.20537);
   syst_sigma_long_bkg_shift_max->SetBinError(8,12.12853);
   syst_sigma_long_bkg_shift_max->SetBinError(9,10.70726);
   syst_sigma_long_bkg_shift_max->SetEntries(16.0463);

   ci = TColor::GetColor("#ff9933");
   syst_sigma_long_bkg_shift_max->SetFillColor(ci);
   syst_sigma_long_bkg_shift_max->SetFillStyle(0);

   ci = TColor::GetColor("#ff9933");
   syst_sigma_long_bkg_shift_max->SetLineColor(ci);

   ci = TColor::GetColor("#ff9933");
   syst_sigma_long_bkg_shift_max->SetMarkerColor(ci);
   syst_sigma_long_bkg_shift_max->SetMarkerSize(1.1);
   syst_sigma_long_bkg_shift_max->GetXaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift_max->GetXaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift_max->GetXaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift_max->GetXaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift_max->GetYaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift_max->GetYaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift_max->GetYaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift_max->GetYaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift_max->GetZaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift_max->GetZaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift_max->GetZaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift_max->GetZaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift_max->Draw("hist][same");
   
   TH1F *hframe__8 = new TH1F("hframe__8","",1000,8,62);
   hframe__8->SetMinimum(-11.4664);
   hframe__8->SetMaximum(11.4664);
   hframe__8->SetDirectory(0);
   hframe__8->SetStats(0);
   hframe__8->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__8->GetXaxis()->SetNdivisions(506);
   hframe__8->GetXaxis()->SetLabelFont(43);
   hframe__8->GetXaxis()->SetLabelSize(18);
   hframe__8->GetXaxis()->SetTitleSize(18);
   hframe__8->GetXaxis()->SetTickLength(0.07);
   hframe__8->GetXaxis()->SetTitleOffset(7.5);
   hframe__8->GetXaxis()->SetTitleFont(43);
   hframe__8->GetYaxis()->SetTitle("Rel. diff. (%)");
   hframe__8->GetYaxis()->SetNdivisions(506);
   hframe__8->GetYaxis()->SetLabelFont(43);
   hframe__8->GetYaxis()->SetLabelSize(18);
   hframe__8->GetYaxis()->SetTitleSize(18);
   hframe__8->GetYaxis()->SetTitleOffset(5.5);
   hframe__8->GetYaxis()->SetTitleFont(43);
   hframe__8->GetZaxis()->SetLabelFont(43);
   hframe__8->GetZaxis()->SetLabelSize(18);
   hframe__8->GetZaxis()->SetTitleOffset(1.1);
   hframe__8->GetZaxis()->SetTitleFont(43);
   hframe__8->Draw("sameaxis");
   syst_sigma_long_bkg_shift_pad->Modified();
   c_cross_section_variations_to_std_TOP_pad->cd();
  
// ------------>Primitives in pad: cross_section_gamma_jet_weight_pad
   cross_section_gamma_jet_weight_pad = new TPad("cross_section_gamma_jet_weight_pad", "cross_section_gamma_jet_weight_pad",0.6666667,0.3,1,1);
   cross_section_gamma_jet_weight_pad->Draw();
   cross_section_gamma_jet_weight_pad->cd();
   cross_section_gamma_jet_weight_pad->Range(-4,-1.655154,62.66667,3.635851);
   cross_section_gamma_jet_weight_pad->SetFillColor(0);
   cross_section_gamma_jet_weight_pad->SetBorderMode(0);
   cross_section_gamma_jet_weight_pad->SetBorderSize(2);
   cross_section_gamma_jet_weight_pad->SetLogy();
   cross_section_gamma_jet_weight_pad->SetTickx(1);
   cross_section_gamma_jet_weight_pad->SetTicky(1);
   cross_section_gamma_jet_weight_pad->SetLeftMargin(0.18);
   cross_section_gamma_jet_weight_pad->SetRightMargin(0.01);
   cross_section_gamma_jet_weight_pad->SetTopMargin(0.03);
   cross_section_gamma_jet_weight_pad->SetBottomMargin(0.025);
   cross_section_gamma_jet_weight_pad->SetFrameBorderMode(0);
   cross_section_gamma_jet_weight_pad->SetFrameBorderMode(0);
   
   TH1F *hframe__9 = new TH1F("hframe__9","",1000,8,62);
   hframe__9->SetMinimum(0.03);
   hframe__9->SetMaximum(3000);
   hframe__9->SetDirectory(0);
   hframe__9->SetStats(0);
   hframe__9->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__9->GetXaxis()->SetNdivisions(506);
   hframe__9->GetXaxis()->SetLabelFont(43);
   hframe__9->GetXaxis()->SetLabelOffset(999);
   hframe__9->GetXaxis()->SetLabelSize(0);
   hframe__9->GetXaxis()->SetTitleSize(18);
   hframe__9->GetXaxis()->SetTitleOffset(7.5);
   hframe__9->GetXaxis()->SetTitleFont(43);
   hframe__9->GetYaxis()->SetTitle("d^{2}#sigma/d#it{p}_{T}d#it{#eta} (nb GeV^{-1}#it{c})");
   hframe__9->GetYaxis()->SetNdivisions(506);
   hframe__9->GetYaxis()->SetLabelFont(43);
   hframe__9->GetYaxis()->SetLabelSize(18);
   hframe__9->GetYaxis()->SetTitleSize(18);
   hframe__9->GetYaxis()->SetTitleOffset(5.5);
   hframe__9->GetYaxis()->SetTitleFont(43);
   hframe__9->GetZaxis()->SetLabelFont(43);
   hframe__9->GetZaxis()->SetLabelSize(18);
   hframe__9->GetZaxis()->SetTitleOffset(1.1);
   hframe__9->GetZaxis()->SetTitleFont(43);
   hframe__9->Draw(" ");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetFillStyle(0);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,32.1326);
   gre->SetPointError(0,1,6.4177);
   gre->SetPoint(1,13,17.8523);
   gre->SetPointError(1,1,3.68763);
   gre->SetPoint(2,15,12.4859);
   gre->SetPointError(2,1,1.52171);
   gre->SetPoint(3,17,5.75182);
   gre->SetPointError(3,1,0.915476);
   gre->SetPoint(4,19,4.81785);
   gre->SetPointError(4,1,0.732516);
   gre->SetPoint(5,22.5,2.09243);
   gre->SetPointError(5,2.5,0.315706);
   gre->SetPoint(6,27.5,0.794539);
   gre->SetPointError(6,2.5,0.200054);
   gre->SetPoint(7,35,0.306897);
   gre->SetPointError(7,5,0.0931315);
   gre->SetPoint(8,50,0.0751043);
   gre->SetPointError(8,10,0.03028);
   
   TH1F *Graph_Graph_Graph_Graph147 = new TH1F("Graph_Graph_Graph_Graph147","Graph",100,5,65);
   Graph_Graph_Graph_Graph147->SetMinimum(0.04034187);
   Graph_Graph_Graph_Graph147->SetMaximum(42.40085);
   Graph_Graph_Graph_Graph147->SetDirectory(0);
   Graph_Graph_Graph_Graph147->SetStats(0);
   Graph_Graph_Graph_Graph147->GetXaxis()->SetNdivisions(506);
   Graph_Graph_Graph_Graph147->GetXaxis()->SetLabelFont(43);
   Graph_Graph_Graph_Graph147->GetXaxis()->SetLabelSize(18);
   Graph_Graph_Graph_Graph147->GetXaxis()->SetTitleSize(18);
   Graph_Graph_Graph_Graph147->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph_Graph_Graph147->GetXaxis()->SetTitleFont(43);
   Graph_Graph_Graph_Graph147->GetYaxis()->SetNdivisions(506);
   Graph_Graph_Graph_Graph147->GetYaxis()->SetLabelFont(43);
   Graph_Graph_Graph_Graph147->GetYaxis()->SetLabelSize(18);
   Graph_Graph_Graph_Graph147->GetYaxis()->SetTitleSize(18);
   Graph_Graph_Graph_Graph147->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph_Graph_Graph147->GetYaxis()->SetTitleFont(43);
   Graph_Graph_Graph_Graph147->GetZaxis()->SetLabelFont(43);
   Graph_Graph_Graph_Graph147->GetZaxis()->SetLabelSize(18);
   Graph_Graph_Graph_Graph147->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph_Graph_Graph147->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph_Graph_Graph147);
   
   gre->Draw("ep");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");

   ci = TColor::GetColor("#6699cc");
   gre->SetFillColor(ci);
   gre->SetFillStyle(0);

   ci = TColor::GetColor("#6699cc");
   gre->SetLineColor(ci);

   ci = TColor::GetColor("#6699cc");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,32.053);
   gre->SetPointError(0,1,6.41998);
   gre->SetPoint(1,13,17.8075);
   gre->SetPointError(1,1,3.69026);
   gre->SetPoint(2,15,12.4613);
   gre->SetPointError(2,1,1.52178);
   gre->SetPoint(3,17,5.73778);
   gre->SetPointError(3,1,0.915975);
   gre->SetPoint(4,19,4.80776);
   gre->SetPointError(4,1,0.733113);
   gre->SetPoint(5,22.5,2.08614);
   gre->SetPointError(5,2.5,0.316087);
   gre->SetPoint(6,27.5,0.79012);
   gre->SetPointError(6,2.5,0.20075);
   gre->SetPoint(7,35,0.304351);
   gre->SetPointError(7,5,0.0936779);
   gre->SetPoint(8,50,0.0743926);
   gre->SetPointError(8,10,0.0305223);
   
   TH1F *Graph_Graph8 = new TH1F("Graph_Graph8","Graph",100,5,65);
   Graph_Graph8->SetMinimum(0.03948327);
   Graph_Graph8->SetMaximum(42.31589);
   Graph_Graph8->SetDirectory(0);
   Graph_Graph8->SetStats(0);
   Graph_Graph8->GetXaxis()->SetNdivisions(506);
   Graph_Graph8->GetXaxis()->SetLabelFont(43);
   Graph_Graph8->GetXaxis()->SetLabelSize(18);
   Graph_Graph8->GetXaxis()->SetTitleSize(18);
   Graph_Graph8->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph8->GetXaxis()->SetTitleFont(43);
   Graph_Graph8->GetYaxis()->SetNdivisions(506);
   Graph_Graph8->GetYaxis()->SetLabelFont(43);
   Graph_Graph8->GetYaxis()->SetLabelSize(18);
   Graph_Graph8->GetYaxis()->SetTitleSize(18);
   Graph_Graph8->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph8->GetYaxis()->SetTitleFont(43);
   Graph_Graph8->GetZaxis()->SetLabelFont(43);
   Graph_Graph8->GetZaxis()->SetLabelSize(18);
   Graph_Graph8->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph8->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph8);
   
   gre->Draw("ep");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph1");
   gre->SetTitle("Graph");

   ci = TColor::GetColor("#cc0066");
   gre->SetFillColor(ci);
   gre->SetFillStyle(0);

   ci = TColor::GetColor("#cc0066");
   gre->SetLineColor(ci);

   ci = TColor::GetColor("#cc0066");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,32.2121);
   gre->SetPointError(0,1,6.41544);
   gre->SetPoint(1,13,17.8971);
   gre->SetPointError(1,1,3.68502);
   gre->SetPoint(2,15,12.5104);
   gre->SetPointError(2,1,1.52165);
   gre->SetPoint(3,17,5.76578);
   gre->SetPointError(3,1,0.914983);
   gre->SetPoint(4,19,4.82787);
   gre->SetPointError(4,1,0.731927);
   gre->SetPoint(5,22.5,2.09865);
   gre->SetPointError(5,2.5,0.315331);
   gre->SetPoint(6,27.5,0.798883);
   gre->SetPointError(6,2.5,0.199373);
   gre->SetPoint(7,35,0.30938);
   gre->SetPointError(7,5,0.0926015);
   gre->SetPoint(8,50,0.0757927);
   gre->SetPointError(8,10,0.0300469);
   
   TH1F *Graph_Graph9 = new TH1F("Graph_Graph9","Graph",100,5,65);
   Graph_Graph9->SetMinimum(0.04117122);
   Graph_Graph9->SetMaximum(42.48572);
   Graph_Graph9->SetDirectory(0);
   Graph_Graph9->SetStats(0);
   Graph_Graph9->GetXaxis()->SetNdivisions(506);
   Graph_Graph9->GetXaxis()->SetLabelFont(43);
   Graph_Graph9->GetXaxis()->SetLabelSize(18);
   Graph_Graph9->GetXaxis()->SetTitleSize(18);
   Graph_Graph9->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph9->GetXaxis()->SetTitleFont(43);
   Graph_Graph9->GetYaxis()->SetNdivisions(506);
   Graph_Graph9->GetYaxis()->SetLabelFont(43);
   Graph_Graph9->GetYaxis()->SetLabelSize(18);
   Graph_Graph9->GetYaxis()->SetTitleSize(18);
   Graph_Graph9->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph9->GetYaxis()->SetTitleFont(43);
   Graph_Graph9->GetZaxis()->SetLabelFont(43);
   Graph_Graph9->GetZaxis()->SetLabelSize(18);
   Graph_Graph9->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph9->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph9);
   
   gre->Draw("ep");
   
   leg = new TLegend(0.235,0.7,0.635,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(16);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("Graph0","Standard mixing ratio","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("Graph0","Less signal","lep");

   ci = TColor::GetColor("#6699cc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#6699cc");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("Graph1","More signal","lep");

   ci = TColor::GetColor("#cc0066");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#cc0066");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   leg->Draw();
      tex = new TLatex(0.245,0.87,"MC signal amount variation");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(18);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__10 = new TH1F("hframe__10","",1000,8,62);
   hframe__10->SetMinimum(0.03);
   hframe__10->SetMaximum(3000);
   hframe__10->SetDirectory(0);
   hframe__10->SetStats(0);
   hframe__10->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__10->GetXaxis()->SetNdivisions(506);
   hframe__10->GetXaxis()->SetLabelFont(43);
   hframe__10->GetXaxis()->SetLabelOffset(999);
   hframe__10->GetXaxis()->SetLabelSize(0);
   hframe__10->GetXaxis()->SetTitleSize(18);
   hframe__10->GetXaxis()->SetTitleOffset(7.5);
   hframe__10->GetXaxis()->SetTitleFont(43);
   hframe__10->GetYaxis()->SetTitle("d^{2}#sigma/d#it{p}_{T}d#it{#eta} (nb GeV^{-1}#it{c})");
   hframe__10->GetYaxis()->SetNdivisions(506);
   hframe__10->GetYaxis()->SetLabelFont(43);
   hframe__10->GetYaxis()->SetLabelSize(18);
   hframe__10->GetYaxis()->SetTitleSize(18);
   hframe__10->GetYaxis()->SetTitleOffset(5.5);
   hframe__10->GetYaxis()->SetTitleFont(43);
   hframe__10->GetZaxis()->SetLabelFont(43);
   hframe__10->GetZaxis()->SetLabelSize(18);
   hframe__10->GetZaxis()->SetTitleOffset(1.1);
   hframe__10->GetZaxis()->SetTitleFont(43);
   hframe__10->Draw("sameaxis");
   cross_section_gamma_jet_weight_pad->Modified();
   c_cross_section_variations_to_std_TOP_pad->cd();
  
// ------------>Primitives in pad: syst_gamma_jet_weight_pad
   syst_gamma_jet_weight_pad = new TPad("syst_gamma_jet_weight_pad", "syst_gamma_jet_weight_pad",0.6666667,0,1,0.3);
   syst_gamma_jet_weight_pad->Draw();
   syst_gamma_jet_weight_pad->cd();
   syst_gamma_jet_weight_pad->Range(-4,-2.007102,62.66667,1.283229);
   syst_gamma_jet_weight_pad->SetFillColor(0);
   syst_gamma_jet_weight_pad->SetBorderMode(0);
   syst_gamma_jet_weight_pad->SetBorderSize(2);
   syst_gamma_jet_weight_pad->SetTickx(1);
   syst_gamma_jet_weight_pad->SetTicky(1);
   syst_gamma_jet_weight_pad->SetLeftMargin(0.18);
   syst_gamma_jet_weight_pad->SetRightMargin(0.01);
   syst_gamma_jet_weight_pad->SetTopMargin(0.03);
   syst_gamma_jet_weight_pad->SetBottomMargin(0.25);
   syst_gamma_jet_weight_pad->SetFrameBorderMode(0);
   syst_gamma_jet_weight_pad->SetFrameBorderMode(0);
   
   TH1F *hframe__11 = new TH1F("hframe__11","",1000,8,62);
   hframe__11->SetMinimum(-1.184519);
   hframe__11->SetMaximum(1.184519);
   hframe__11->SetDirectory(0);
   hframe__11->SetStats(0);
   hframe__11->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__11->GetXaxis()->SetNdivisions(506);
   hframe__11->GetXaxis()->SetLabelFont(43);
   hframe__11->GetXaxis()->SetLabelSize(18);
   hframe__11->GetXaxis()->SetTitleSize(18);
   hframe__11->GetXaxis()->SetTickLength(0.07);
   hframe__11->GetXaxis()->SetTitleOffset(7.5);
   hframe__11->GetXaxis()->SetTitleFont(43);
   hframe__11->GetYaxis()->SetTitle("Rel. diff. (%)");
   hframe__11->GetYaxis()->SetNdivisions(506);
   hframe__11->GetYaxis()->SetLabelFont(43);
   hframe__11->GetYaxis()->SetLabelSize(18);
   hframe__11->GetYaxis()->SetTitleSize(18);
   hframe__11->GetYaxis()->SetTitleOffset(5.5);
   hframe__11->GetYaxis()->SetTitleFont(43);
   hframe__11->GetZaxis()->SetLabelFont(43);
   hframe__11->GetZaxis()->SetLabelSize(18);
   hframe__11->GetZaxis()->SetTitleOffset(1.1);
   hframe__11->GetZaxis()->SetTitleFont(43);
   hframe__11->Draw(" ");
   line = new TLine(0.18,0.61,0.99,0.61);
   line->SetLineStyle(3);
   line->Draw();
   Double_t xAxis5[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_gamma_jet_weight_min = new TH1D("syst_gamma_jet_weight_min","",9, xAxis5);
   syst_gamma_jet_weight_min->SetBinContent(1,-0.2477235);
   syst_gamma_jet_weight_min->SetBinContent(2,-0.2509481);
   syst_gamma_jet_weight_min->SetBinContent(3,-0.1970222);
   syst_gamma_jet_weight_min->SetBinContent(4,-0.2440967);
   syst_gamma_jet_weight_min->SetBinContent(5,-0.2094295);
   syst_gamma_jet_weight_min->SetBinContent(6,-0.3006074);
   syst_gamma_jet_weight_min->SetBinContent(7,-0.5561716);
   syst_gamma_jet_weight_min->SetBinContent(8,-0.8295943);
   syst_gamma_jet_weight_min->SetBinContent(9,-0.9476155);
   syst_gamma_jet_weight_min->SetBinError(1,0.5288027);
   syst_gamma_jet_weight_min->SetBinError(2,0.7765901);
   syst_gamma_jet_weight_min->SetBinError(3,0.1141719);
   syst_gamma_jet_weight_min->SetBinError(4,0.5228587);
   syst_gamma_jet_weight_min->SetBinError(5,0.6118531);
   syst_gamma_jet_weight_min->SetBinError(6,0.7378542);
   syst_gamma_jet_weight_min->SetBinError(7,2.08569);
   syst_gamma_jet_weight_min->SetBinError(8,3.254871);
   syst_gamma_jet_weight_min->SetBinError(9,5.047501);
   syst_gamma_jet_weight_min->SetEntries(3.783209);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight_min->SetFillColor(ci);
   syst_gamma_jet_weight_min->SetFillStyle(0);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight_min->SetLineColor(ci);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight_min->SetMarkerColor(ci);
   syst_gamma_jet_weight_min->SetMarkerSize(1.1);
   syst_gamma_jet_weight_min->GetXaxis()->SetLabelFont(42);
   syst_gamma_jet_weight_min->GetXaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight_min->GetXaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight_min->GetXaxis()->SetTitleFont(42);
   syst_gamma_jet_weight_min->GetYaxis()->SetLabelFont(42);
   syst_gamma_jet_weight_min->GetYaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight_min->GetYaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight_min->GetYaxis()->SetTitleFont(42);
   syst_gamma_jet_weight_min->GetZaxis()->SetLabelFont(42);
   syst_gamma_jet_weight_min->GetZaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight_min->GetZaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight_min->GetZaxis()->SetTitleFont(42);
   syst_gamma_jet_weight_min->Draw("hist][same");
   Double_t xAxis6[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_gamma_jet_weight_max = new TH1D("syst_gamma_jet_weight_max","",9, xAxis6);
   syst_gamma_jet_weight_max->SetBinContent(1,0.2474123);
   syst_gamma_jet_weight_max->SetBinContent(2,0.2509481);
   syst_gamma_jet_weight_max->SetBinContent(3,0.1962213);
   syst_gamma_jet_weight_max->SetBinContent(4,0.2427058);
   syst_gamma_jet_weight_max->SetBinContent(5,0.2079766);
   syst_gamma_jet_weight_max->SetBinContent(6,0.297262);
   syst_gamma_jet_weight_max->SetBinContent(7,0.5467321);
   syst_gamma_jet_weight_max->SetBinContent(8,0.8090662);
   syst_gamma_jet_weight_max->SetBinContent(9,0.916592);
   syst_gamma_jet_weight_max->SetBinError(1,0.5336013);
   syst_gamma_jet_weight_max->SetBinError(2,0.7807005);
   syst_gamma_jet_weight_max->SetBinError(3,0.111044);
   syst_gamma_jet_weight_max->SetBinError(4,0.524963);
   syst_gamma_jet_weight_max->SetBinError(5,0.6116783);
   syst_gamma_jet_weight_max->SetBinError(6,0.7387223);
   syst_gamma_jet_weight_max->SetBinError(7,2.091613);
   syst_gamma_jet_weight_max->SetBinError(8,3.268168);
   syst_gamma_jet_weight_max->SetBinError(9,5.052094);
   syst_gamma_jet_weight_max->SetEntries(0.3233398);

   ci = TColor::GetColor("#cc0066");
   syst_gamma_jet_weight_max->SetFillColor(ci);
   syst_gamma_jet_weight_max->SetFillStyle(0);

   ci = TColor::GetColor("#cc0066");
   syst_gamma_jet_weight_max->SetLineColor(ci);

   ci = TColor::GetColor("#cc0066");
   syst_gamma_jet_weight_max->SetMarkerColor(ci);
   syst_gamma_jet_weight_max->SetMarkerSize(1.1);
   syst_gamma_jet_weight_max->GetXaxis()->SetLabelFont(42);
   syst_gamma_jet_weight_max->GetXaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight_max->GetXaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight_max->GetXaxis()->SetTitleFont(42);
   syst_gamma_jet_weight_max->GetYaxis()->SetLabelFont(42);
   syst_gamma_jet_weight_max->GetYaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight_max->GetYaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight_max->GetYaxis()->SetTitleFont(42);
   syst_gamma_jet_weight_max->GetZaxis()->SetLabelFont(42);
   syst_gamma_jet_weight_max->GetZaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight_max->GetZaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight_max->GetZaxis()->SetTitleFont(42);
   syst_gamma_jet_weight_max->Draw("hist][same");
   
   TH1F *hframe__12 = new TH1F("hframe__12","",1000,8,62);
   hframe__12->SetMinimum(-1.184519);
   hframe__12->SetMaximum(1.184519);
   hframe__12->SetDirectory(0);
   hframe__12->SetStats(0);
   hframe__12->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__12->GetXaxis()->SetNdivisions(506);
   hframe__12->GetXaxis()->SetLabelFont(43);
   hframe__12->GetXaxis()->SetLabelSize(18);
   hframe__12->GetXaxis()->SetTitleSize(18);
   hframe__12->GetXaxis()->SetTickLength(0.07);
   hframe__12->GetXaxis()->SetTitleOffset(7.5);
   hframe__12->GetXaxis()->SetTitleFont(43);
   hframe__12->GetYaxis()->SetTitle("Rel. diff. (%)");
   hframe__12->GetYaxis()->SetNdivisions(506);
   hframe__12->GetYaxis()->SetLabelFont(43);
   hframe__12->GetYaxis()->SetLabelSize(18);
   hframe__12->GetYaxis()->SetTitleSize(18);
   hframe__12->GetYaxis()->SetTitleOffset(5.5);
   hframe__12->GetYaxis()->SetTitleFont(43);
   hframe__12->GetZaxis()->SetLabelFont(43);
   hframe__12->GetZaxis()->SetLabelSize(18);
   hframe__12->GetZaxis()->SetTitleOffset(1.1);
   hframe__12->GetZaxis()->SetTitleFont(43);
   hframe__12->Draw("sameaxis");
   syst_gamma_jet_weight_pad->Modified();
   c_cross_section_variations_to_std_TOP_pad->cd();
   c_cross_section_variations_to_std_TOP_pad->Modified();
   c_cross_section_variations_to_std->cd();
  
// ------------>Primitives in pad: c_cross_section_variations_to_std_BOTTOM_pad
   c_cross_section_variations_to_std_BOTTOM_pad = new TPad("c_cross_section_variations_to_std_BOTTOM_pad", "c_cross_section_variations_to_std_BOTTOM_pad",0,0,1,0.5);
   c_cross_section_variations_to_std_BOTTOM_pad->Draw();
   c_cross_section_variations_to_std_BOTTOM_pad->cd();
   c_cross_section_variations_to_std_BOTTOM_pad->Range(0,0,1,1);
   c_cross_section_variations_to_std_BOTTOM_pad->SetFillColor(0);
   c_cross_section_variations_to_std_BOTTOM_pad->SetBorderMode(0);
   c_cross_section_variations_to_std_BOTTOM_pad->SetBorderSize(2);
   c_cross_section_variations_to_std_BOTTOM_pad->SetTickx(1);
   c_cross_section_variations_to_std_BOTTOM_pad->SetTicky(1);
   c_cross_section_variations_to_std_BOTTOM_pad->SetLeftMargin(0.18);
   c_cross_section_variations_to_std_BOTTOM_pad->SetRightMargin(0.01);
   c_cross_section_variations_to_std_BOTTOM_pad->SetTopMargin(0.03);
   c_cross_section_variations_to_std_BOTTOM_pad->SetBottomMargin(0.025);
   c_cross_section_variations_to_std_BOTTOM_pad->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: cross_section_no_smearing_pad
   cross_section_no_smearing_pad = new TPad("cross_section_no_smearing_pad", "cross_section_no_smearing_pad",0.1666667,0.3,0.5,1);
   cross_section_no_smearing_pad->Draw();
   cross_section_no_smearing_pad->cd();
   cross_section_no_smearing_pad->Range(-4,-1.655154,62.66667,3.635851);
   cross_section_no_smearing_pad->SetFillColor(0);
   cross_section_no_smearing_pad->SetBorderMode(0);
   cross_section_no_smearing_pad->SetBorderSize(2);
   cross_section_no_smearing_pad->SetLogy();
   cross_section_no_smearing_pad->SetTickx(1);
   cross_section_no_smearing_pad->SetTicky(1);
   cross_section_no_smearing_pad->SetLeftMargin(0.18);
   cross_section_no_smearing_pad->SetRightMargin(0.01);
   cross_section_no_smearing_pad->SetTopMargin(0.03);
   cross_section_no_smearing_pad->SetBottomMargin(0.025);
   cross_section_no_smearing_pad->SetFrameBorderMode(0);
   cross_section_no_smearing_pad->SetFrameBorderMode(0);
   
   TH1F *hframe__13 = new TH1F("hframe__13","",1000,8,62);
   hframe__13->SetMinimum(0.03);
   hframe__13->SetMaximum(3000);
   hframe__13->SetDirectory(0);
   hframe__13->SetStats(0);
   hframe__13->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__13->GetXaxis()->SetNdivisions(506);
   hframe__13->GetXaxis()->SetLabelFont(43);
   hframe__13->GetXaxis()->SetLabelOffset(999);
   hframe__13->GetXaxis()->SetLabelSize(0);
   hframe__13->GetXaxis()->SetTitleSize(18);
   hframe__13->GetXaxis()->SetTitleOffset(7.5);
   hframe__13->GetXaxis()->SetTitleFont(43);
   hframe__13->GetYaxis()->SetTitle("d^{2}#sigma/d#it{p}_{T}d#it{#eta} (nb GeV^{-1}#it{c})");
   hframe__13->GetYaxis()->SetNdivisions(506);
   hframe__13->GetYaxis()->SetLabelFont(43);
   hframe__13->GetYaxis()->SetLabelSize(18);
   hframe__13->GetYaxis()->SetTitleSize(18);
   hframe__13->GetYaxis()->SetTitleOffset(5.5);
   hframe__13->GetYaxis()->SetTitleFont(43);
   hframe__13->GetZaxis()->SetLabelFont(43);
   hframe__13->GetZaxis()->SetLabelSize(18);
   hframe__13->GetZaxis()->SetTitleOffset(1.1);
   hframe__13->GetZaxis()->SetTitleFont(43);
   hframe__13->Draw(" ");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetFillStyle(0);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,32.1326);
   gre->SetPointError(0,1,6.4177);
   gre->SetPoint(1,13,17.8523);
   gre->SetPointError(1,1,3.68763);
   gre->SetPoint(2,15,12.4859);
   gre->SetPointError(2,1,1.52171);
   gre->SetPoint(3,17,5.75182);
   gre->SetPointError(3,1,0.915476);
   gre->SetPoint(4,19,4.81785);
   gre->SetPointError(4,1,0.732516);
   gre->SetPoint(5,22.5,2.09243);
   gre->SetPointError(5,2.5,0.315706);
   gre->SetPoint(6,27.5,0.794539);
   gre->SetPointError(6,2.5,0.200054);
   gre->SetPoint(7,35,0.306897);
   gre->SetPointError(7,5,0.0931315);
   gre->SetPoint(8,50,0.0751043);
   gre->SetPointError(8,10,0.03028);
   
   TH1F *Graph_Graph_Graph_Graph_Graph14710 = new TH1F("Graph_Graph_Graph_Graph_Graph14710","Graph",100,5,65);
   Graph_Graph_Graph_Graph_Graph14710->SetMinimum(0.04034187);
   Graph_Graph_Graph_Graph_Graph14710->SetMaximum(42.40085);
   Graph_Graph_Graph_Graph_Graph14710->SetDirectory(0);
   Graph_Graph_Graph_Graph_Graph14710->SetStats(0);
   Graph_Graph_Graph_Graph_Graph14710->GetXaxis()->SetNdivisions(506);
   Graph_Graph_Graph_Graph_Graph14710->GetXaxis()->SetLabelFont(43);
   Graph_Graph_Graph_Graph_Graph14710->GetXaxis()->SetLabelSize(18);
   Graph_Graph_Graph_Graph_Graph14710->GetXaxis()->SetTitleSize(18);
   Graph_Graph_Graph_Graph_Graph14710->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph_Graph_Graph_Graph14710->GetXaxis()->SetTitleFont(43);
   Graph_Graph_Graph_Graph_Graph14710->GetYaxis()->SetNdivisions(506);
   Graph_Graph_Graph_Graph_Graph14710->GetYaxis()->SetLabelFont(43);
   Graph_Graph_Graph_Graph_Graph14710->GetYaxis()->SetLabelSize(18);
   Graph_Graph_Graph_Graph_Graph14710->GetYaxis()->SetTitleSize(18);
   Graph_Graph_Graph_Graph_Graph14710->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph_Graph_Graph_Graph14710->GetYaxis()->SetTitleFont(43);
   Graph_Graph_Graph_Graph_Graph14710->GetZaxis()->SetLabelFont(43);
   Graph_Graph_Graph_Graph_Graph14710->GetZaxis()->SetLabelSize(18);
   Graph_Graph_Graph_Graph_Graph14710->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph_Graph_Graph_Graph14710->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph_Graph_Graph_Graph14710);
   
   gre->Draw("ep");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");

   ci = TColor::GetColor("#66cc99");
   gre->SetFillColor(ci);
   gre->SetFillStyle(0);

   ci = TColor::GetColor("#66cc99");
   gre->SetLineColor(ci);

   ci = TColor::GetColor("#66cc99");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,35.9884);
   gre->SetPointError(0,1,6.36754);
   gre->SetPoint(1,13,16.8849);
   gre->SetPointError(1,1,3.68875);
   gre->SetPoint(2,15,12.4781);
   gre->SetPointError(2,1,1.51485);
   gre->SetPoint(3,17,5.46671);
   gre->SetPointError(3,1,0.847707);
   gre->SetPoint(4,19,4.42534);
   gre->SetPointError(4,1,0.678573);
   gre->SetPoint(5,22.5,1.90234);
   gre->SetPointError(5,2.5,0.296836);
   gre->SetPoint(6,27.5,0.730159);
   gre->SetPointError(6,2.5,0.193106);
   gre->SetPoint(7,35,0.279433);
   gre->SetPointError(7,5,0.0892603);
   gre->SetPoint(8,50,0.0703399);
   gre->SetPointError(8,10,0.0290035);
   
   TH1F *Graph_Graph11 = new TH1F("Graph_Graph11","Graph",100,5,65);
   Graph_Graph11->SetMinimum(0.03720276);
   Graph_Graph11->SetMaximum(46.5874);
   Graph_Graph11->SetDirectory(0);
   Graph_Graph11->SetStats(0);
   Graph_Graph11->GetXaxis()->SetNdivisions(506);
   Graph_Graph11->GetXaxis()->SetLabelFont(43);
   Graph_Graph11->GetXaxis()->SetLabelSize(18);
   Graph_Graph11->GetXaxis()->SetTitleSize(18);
   Graph_Graph11->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph11->GetXaxis()->SetTitleFont(43);
   Graph_Graph11->GetYaxis()->SetNdivisions(506);
   Graph_Graph11->GetYaxis()->SetLabelFont(43);
   Graph_Graph11->GetYaxis()->SetLabelSize(18);
   Graph_Graph11->GetYaxis()->SetTitleSize(18);
   Graph_Graph11->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph11->GetYaxis()->SetTitleFont(43);
   Graph_Graph11->GetZaxis()->SetLabelFont(43);
   Graph_Graph11->GetZaxis()->SetLabelSize(18);
   Graph_Graph11->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph11->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph11);
   
   gre->Draw("ep");
   
   leg = new TLegend(0.235,0.75,0.635,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(16);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("Graph0","Standard tuning","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("Graph0","No tuning applied","lep");

   ci = TColor::GetColor("#66cc99");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#66cc99");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   leg->Draw();
      tex = new TLatex(0.245,0.87,"No MC tuning");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(18);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__14 = new TH1F("hframe__14","",1000,8,62);
   hframe__14->SetMinimum(0.03);
   hframe__14->SetMaximum(3000);
   hframe__14->SetDirectory(0);
   hframe__14->SetStats(0);
   hframe__14->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__14->GetXaxis()->SetNdivisions(506);
   hframe__14->GetXaxis()->SetLabelFont(43);
   hframe__14->GetXaxis()->SetLabelOffset(999);
   hframe__14->GetXaxis()->SetLabelSize(0);
   hframe__14->GetXaxis()->SetTitleSize(18);
   hframe__14->GetXaxis()->SetTitleOffset(7.5);
   hframe__14->GetXaxis()->SetTitleFont(43);
   hframe__14->GetYaxis()->SetTitle("d^{2}#sigma/d#it{p}_{T}d#it{#eta} (nb GeV^{-1}#it{c})");
   hframe__14->GetYaxis()->SetNdivisions(506);
   hframe__14->GetYaxis()->SetLabelFont(43);
   hframe__14->GetYaxis()->SetLabelSize(18);
   hframe__14->GetYaxis()->SetTitleSize(18);
   hframe__14->GetYaxis()->SetTitleOffset(5.5);
   hframe__14->GetYaxis()->SetTitleFont(43);
   hframe__14->GetZaxis()->SetLabelFont(43);
   hframe__14->GetZaxis()->SetLabelSize(18);
   hframe__14->GetZaxis()->SetTitleOffset(1.1);
   hframe__14->GetZaxis()->SetTitleFont(43);
   hframe__14->Draw("sameaxis");
   cross_section_no_smearing_pad->Modified();
   c_cross_section_variations_to_std_BOTTOM_pad->cd();
  
// ------------>Primitives in pad: syst_no_smearing_pad
   syst_no_smearing_pad = new TPad("syst_no_smearing_pad", "syst_no_smearing_pad",0.1666667,0,0.5,0.3);
   syst_no_smearing_pad->Draw();
   syst_no_smearing_pad->cd();
   syst_no_smearing_pad->Range(-4,-25.41593,62.66667,16.24953);
   syst_no_smearing_pad->SetFillColor(0);
   syst_no_smearing_pad->SetBorderMode(0);
   syst_no_smearing_pad->SetBorderSize(2);
   syst_no_smearing_pad->SetTickx(1);
   syst_no_smearing_pad->SetTicky(1);
   syst_no_smearing_pad->SetLeftMargin(0.18);
   syst_no_smearing_pad->SetRightMargin(0.01);
   syst_no_smearing_pad->SetTopMargin(0.03);
   syst_no_smearing_pad->SetBottomMargin(0.25);
   syst_no_smearing_pad->SetFrameBorderMode(0);
   syst_no_smearing_pad->SetFrameBorderMode(0);
   
   TH1F *hframe__15 = new TH1F("hframe__15","",1000,8,62);
   hframe__15->SetMinimum(-14.99956);
   hframe__15->SetMaximum(14.99956);
   hframe__15->SetDirectory(0);
   hframe__15->SetStats(0);
   hframe__15->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__15->GetXaxis()->SetNdivisions(506);
   hframe__15->GetXaxis()->SetLabelFont(43);
   hframe__15->GetXaxis()->SetLabelSize(18);
   hframe__15->GetXaxis()->SetTitleSize(18);
   hframe__15->GetXaxis()->SetTickLength(0.07);
   hframe__15->GetXaxis()->SetTitleOffset(7.5);
   hframe__15->GetXaxis()->SetTitleFont(43);
   hframe__15->GetYaxis()->SetTitle("Rel. diff. (%)");
   hframe__15->GetYaxis()->SetNdivisions(506);
   hframe__15->GetYaxis()->SetLabelFont(43);
   hframe__15->GetYaxis()->SetLabelSize(18);
   hframe__15->GetYaxis()->SetTitleSize(18);
   hframe__15->GetYaxis()->SetTitleOffset(5.5);
   hframe__15->GetYaxis()->SetTitleFont(43);
   hframe__15->GetZaxis()->SetLabelFont(43);
   hframe__15->GetZaxis()->SetLabelSize(18);
   hframe__15->GetZaxis()->SetTitleOffset(1.1);
   hframe__15->GetZaxis()->SetTitleFont(43);
   hframe__15->Draw(" ");
   line = new TLine(0.18,0.61,0.99,0.61);
   line->SetLineStyle(3);
   line->Draw();
   Double_t xAxis7[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_no_smearing_std = new TH1D("syst_no_smearing_std","",9, xAxis7);
   syst_no_smearing_std->SetBinContent(1,11.99965);
   syst_no_smearing_std->SetBinContent(2,-5.41891);
   syst_no_smearing_std->SetBinContent(3,-0.06247047);
   syst_no_smearing_std->SetBinContent(4,-4.956866);
   syst_no_smearing_std->SetBinContent(5,-8.146995);
   syst_no_smearing_std->SetBinContent(6,-9.084653);
   syst_no_smearing_std->SetBinContent(7,-8.102812);
   syst_no_smearing_std->SetBinContent(8,-8.948931);
   syst_no_smearing_std->SetBinContent(9,-6.343711);
   syst_no_smearing_std->SetBinError(1,3.666837);
   syst_no_smearing_std->SetBinError(2,1.010847);
   syst_no_smearing_std->SetBinError(3,1.155237);
   syst_no_smearing_std->SetBinError(4,5.758417);
   syst_no_smearing_std->SetBinError(5,5.383695);
   syst_no_smearing_std->SetBinError(6,4.845844);
   syst_no_smearing_std->SetBinError(7,6.357762);
   syst_no_smearing_std->SetBinError(8,8.302028);
   syst_no_smearing_std->SetBinError(9,11.12117);
   syst_no_smearing_std->SetEntries(39.0657);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_std->SetFillColor(ci);
   syst_no_smearing_std->SetFillStyle(0);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_std->SetLineColor(ci);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_std->SetMarkerColor(ci);
   syst_no_smearing_std->SetMarkerSize(1.1);
   syst_no_smearing_std->GetXaxis()->SetLabelFont(42);
   syst_no_smearing_std->GetXaxis()->SetLabelSize(0.035);
   syst_no_smearing_std->GetXaxis()->SetTitleSize(0.035);
   syst_no_smearing_std->GetXaxis()->SetTitleFont(42);
   syst_no_smearing_std->GetYaxis()->SetLabelFont(42);
   syst_no_smearing_std->GetYaxis()->SetLabelSize(0.035);
   syst_no_smearing_std->GetYaxis()->SetTitleSize(0.035);
   syst_no_smearing_std->GetYaxis()->SetTitleFont(42);
   syst_no_smearing_std->GetZaxis()->SetLabelFont(42);
   syst_no_smearing_std->GetZaxis()->SetLabelSize(0.035);
   syst_no_smearing_std->GetZaxis()->SetTitleSize(0.035);
   syst_no_smearing_std->GetZaxis()->SetTitleFont(42);
   syst_no_smearing_std->Draw("hist][same");
   
   TH1F *hframe__16 = new TH1F("hframe__16","",1000,8,62);
   hframe__16->SetMinimum(-14.99956);
   hframe__16->SetMaximum(14.99956);
   hframe__16->SetDirectory(0);
   hframe__16->SetStats(0);
   hframe__16->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__16->GetXaxis()->SetNdivisions(506);
   hframe__16->GetXaxis()->SetLabelFont(43);
   hframe__16->GetXaxis()->SetLabelSize(18);
   hframe__16->GetXaxis()->SetTitleSize(18);
   hframe__16->GetXaxis()->SetTickLength(0.07);
   hframe__16->GetXaxis()->SetTitleOffset(7.5);
   hframe__16->GetXaxis()->SetTitleFont(43);
   hframe__16->GetYaxis()->SetTitle("Rel. diff. (%)");
   hframe__16->GetYaxis()->SetNdivisions(506);
   hframe__16->GetYaxis()->SetLabelFont(43);
   hframe__16->GetYaxis()->SetLabelSize(18);
   hframe__16->GetYaxis()->SetTitleSize(18);
   hframe__16->GetYaxis()->SetTitleOffset(5.5);
   hframe__16->GetYaxis()->SetTitleFont(43);
   hframe__16->GetZaxis()->SetLabelFont(43);
   hframe__16->GetZaxis()->SetLabelSize(18);
   hframe__16->GetZaxis()->SetTitleOffset(1.1);
   hframe__16->GetZaxis()->SetTitleFont(43);
   hframe__16->Draw("sameaxis");
   syst_no_smearing_pad->Modified();
   c_cross_section_variations_to_std_BOTTOM_pad->cd();
  
// ------------>Primitives in pad: cross_section_CPV_pad
   cross_section_CPV_pad = new TPad("cross_section_CPV_pad", "cross_section_CPV_pad",0.5,0.3,0.8333333,1);
   cross_section_CPV_pad->Draw();
   cross_section_CPV_pad->cd();
   cross_section_CPV_pad->Range(-4,-1.655154,62.66667,3.635851);
   cross_section_CPV_pad->SetFillColor(0);
   cross_section_CPV_pad->SetBorderMode(0);
   cross_section_CPV_pad->SetBorderSize(2);
   cross_section_CPV_pad->SetLogy();
   cross_section_CPV_pad->SetTickx(1);
   cross_section_CPV_pad->SetTicky(1);
   cross_section_CPV_pad->SetLeftMargin(0.18);
   cross_section_CPV_pad->SetRightMargin(0.01);
   cross_section_CPV_pad->SetTopMargin(0.03);
   cross_section_CPV_pad->SetBottomMargin(0.025);
   cross_section_CPV_pad->SetFrameBorderMode(0);
   cross_section_CPV_pad->SetFrameBorderMode(0);
   
   TH1F *hframe__17 = new TH1F("hframe__17","",1000,8,62);
   hframe__17->SetMinimum(0.03);
   hframe__17->SetMaximum(3000);
   hframe__17->SetDirectory(0);
   hframe__17->SetStats(0);
   hframe__17->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__17->GetXaxis()->SetNdivisions(506);
   hframe__17->GetXaxis()->SetLabelFont(43);
   hframe__17->GetXaxis()->SetLabelOffset(999);
   hframe__17->GetXaxis()->SetLabelSize(0);
   hframe__17->GetXaxis()->SetTitleSize(18);
   hframe__17->GetXaxis()->SetTitleOffset(7.5);
   hframe__17->GetXaxis()->SetTitleFont(43);
   hframe__17->GetYaxis()->SetTitle("d^{2}#sigma/d#it{p}_{T}d#it{#eta} (nb GeV^{-1}#it{c})");
   hframe__17->GetYaxis()->SetNdivisions(506);
   hframe__17->GetYaxis()->SetLabelFont(43);
   hframe__17->GetYaxis()->SetLabelSize(18);
   hframe__17->GetYaxis()->SetTitleSize(18);
   hframe__17->GetYaxis()->SetTitleOffset(5.5);
   hframe__17->GetYaxis()->SetTitleFont(43);
   hframe__17->GetZaxis()->SetLabelFont(43);
   hframe__17->GetZaxis()->SetLabelSize(18);
   hframe__17->GetZaxis()->SetTitleOffset(1.1);
   hframe__17->GetZaxis()->SetTitleFont(43);
   hframe__17->Draw(" ");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetFillStyle(0);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,32.1326);
   gre->SetPointError(0,1,6.4177);
   gre->SetPoint(1,13,17.8523);
   gre->SetPointError(1,1,3.68763);
   gre->SetPoint(2,15,12.4859);
   gre->SetPointError(2,1,1.52171);
   gre->SetPoint(3,17,5.75182);
   gre->SetPointError(3,1,0.915476);
   gre->SetPoint(4,19,4.81785);
   gre->SetPointError(4,1,0.732516);
   gre->SetPoint(5,22.5,2.09243);
   gre->SetPointError(5,2.5,0.315706);
   gre->SetPoint(6,27.5,0.794539);
   gre->SetPointError(6,2.5,0.200054);
   gre->SetPoint(7,35,0.306897);
   gre->SetPointError(7,5,0.0931315);
   gre->SetPoint(8,50,0.0751043);
   gre->SetPointError(8,10,0.03028);
   
   TH1F *Graph_Graph_Graph_Graph_Graph_Graph1471012 = new TH1F("Graph_Graph_Graph_Graph_Graph_Graph1471012","Graph",100,5,65);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->SetMinimum(0.04034187);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->SetMaximum(42.40085);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->SetDirectory(0);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->SetStats(0);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetXaxis()->SetNdivisions(506);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetXaxis()->SetLabelFont(43);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetXaxis()->SetLabelSize(18);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetXaxis()->SetTitleSize(18);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetXaxis()->SetTitleFont(43);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetYaxis()->SetNdivisions(506);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetYaxis()->SetLabelFont(43);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetYaxis()->SetLabelSize(18);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetYaxis()->SetTitleSize(18);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetYaxis()->SetTitleFont(43);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetZaxis()->SetLabelFont(43);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetZaxis()->SetLabelSize(18);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph_Graph_Graph_Graph_Graph1471012->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph_Graph_Graph_Graph_Graph1471012);
   
   gre->Draw("ep");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");

   ci = TColor::GetColor("#99cccc");
   gre->SetFillColor(ci);
   gre->SetFillStyle(0);

   ci = TColor::GetColor("#99cccc");
   gre->SetLineColor(ci);

   ci = TColor::GetColor("#99cccc");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,33.2536);
   gre->SetPointError(0,1,6.50737);
   gre->SetPoint(1,13,17.6318);
   gre->SetPointError(1,1,3.71573);
   gre->SetPoint(2,15,12.892);
   gre->SetPointError(2,1,1.54022);
   gre->SetPoint(3,17,5.70419);
   gre->SetPointError(3,1,0.911739);
   gre->SetPoint(4,19,4.84283);
   gre->SetPointError(4,1,0.727292);
   gre->SetPoint(5,22.5,2.14944);
   gre->SetPointError(5,2.5,0.319377);
   gre->SetPoint(6,27.5,0.790607);
   gre->SetPointError(6,2.5,0.20223);
   gre->SetPoint(7,35,0.31282);
   gre->SetPointError(7,5,0.0948554);
   gre->SetPoint(8,50,0.0743366);
   gre->SetPointError(8,10,0.030416);
   
   TH1F *Graph_Graph13 = new TH1F("Graph_Graph13","Graph",100,5,65);
   Graph_Graph13->SetMinimum(0.03952854);
   Graph_Graph13->SetMaximum(43.73267);
   Graph_Graph13->SetDirectory(0);
   Graph_Graph13->SetStats(0);
   Graph_Graph13->GetXaxis()->SetNdivisions(506);
   Graph_Graph13->GetXaxis()->SetLabelFont(43);
   Graph_Graph13->GetXaxis()->SetLabelSize(18);
   Graph_Graph13->GetXaxis()->SetTitleSize(18);
   Graph_Graph13->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph13->GetXaxis()->SetTitleFont(43);
   Graph_Graph13->GetYaxis()->SetNdivisions(506);
   Graph_Graph13->GetYaxis()->SetLabelFont(43);
   Graph_Graph13->GetYaxis()->SetLabelSize(18);
   Graph_Graph13->GetYaxis()->SetTitleSize(18);
   Graph_Graph13->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph13->GetYaxis()->SetTitleFont(43);
   Graph_Graph13->GetZaxis()->SetLabelFont(43);
   Graph_Graph13->GetZaxis()->SetLabelSize(18);
   Graph_Graph13->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph13->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph13);
   
   gre->Draw("ep");
   
   gre = new TGraphErrors(9);
   gre->SetName("Graph1");
   gre->SetTitle("Graph");

   ci = TColor::GetColor("#cc6666");
   gre->SetFillColor(ci);
   gre->SetFillStyle(0);

   ci = TColor::GetColor("#cc6666");
   gre->SetLineColor(ci);

   ci = TColor::GetColor("#cc6666");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.1);
   gre->SetPoint(0,11,31.1173);
   gre->SetPointError(0,1,6.43184);
   gre->SetPoint(1,13,17.28);
   gre->SetPointError(1,1,3.66857);
   gre->SetPoint(2,15,12.6763);
   gre->SetPointError(2,1,1.53121);
   gre->SetPoint(3,17,5.75463);
   gre->SetPointError(3,1,0.901798);
   gre->SetPoint(4,19,4.64128);
   gre->SetPointError(4,1,0.709536);
   gre->SetPoint(5,22.5,2.21545);
   gre->SetPointError(5,2.5,0.32208);
   gre->SetPoint(6,27.5,0.826329);
   gre->SetPointError(6,2.5,0.198831);
   gre->SetPoint(7,35,0.311366);
   gre->SetPointError(7,5,0.0926137);
   gre->SetPoint(8,50,0.0794938);
   gre->SetPointError(8,10,0.0284949);
   
   TH1F *Graph_Graph14 = new TH1F("Graph_Graph14","Graph",100,5,65);
   Graph_Graph14->SetMinimum(0.04589901);
   Graph_Graph14->SetMaximum(41.29895);
   Graph_Graph14->SetDirectory(0);
   Graph_Graph14->SetStats(0);
   Graph_Graph14->GetXaxis()->SetNdivisions(506);
   Graph_Graph14->GetXaxis()->SetLabelFont(43);
   Graph_Graph14->GetXaxis()->SetLabelSize(18);
   Graph_Graph14->GetXaxis()->SetTitleSize(18);
   Graph_Graph14->GetXaxis()->SetTitleOffset(7.5);
   Graph_Graph14->GetXaxis()->SetTitleFont(43);
   Graph_Graph14->GetYaxis()->SetNdivisions(506);
   Graph_Graph14->GetYaxis()->SetLabelFont(43);
   Graph_Graph14->GetYaxis()->SetLabelSize(18);
   Graph_Graph14->GetYaxis()->SetTitleSize(18);
   Graph_Graph14->GetYaxis()->SetTitleOffset(5.5);
   Graph_Graph14->GetYaxis()->SetTitleFont(43);
   Graph_Graph14->GetZaxis()->SetLabelFont(43);
   Graph_Graph14->GetZaxis()->SetLabelSize(18);
   Graph_Graph14->GetZaxis()->SetTitleOffset(1.1);
   Graph_Graph14->GetZaxis()->SetTitleFont(43);
   gre->SetHistogram(Graph_Graph14);
   
   gre->Draw("ep");
   
   leg = new TLegend(0.235,0.7,0.635,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(16);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("Graph0","Standard CPV","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("Graph0","Loose CPV","lep");

   ci = TColor::GetColor("#99cccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#99cccc");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("Graph1","Tight CPV","lep");

   ci = TColor::GetColor("#cc6666");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#cc6666");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.1);
   entry->SetTextFont(43);
   leg->Draw();
      tex = new TLatex(0.245,0.87,"Charged particle veto variation");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(18);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__18 = new TH1F("hframe__18","",1000,8,62);
   hframe__18->SetMinimum(0.03);
   hframe__18->SetMaximum(3000);
   hframe__18->SetDirectory(0);
   hframe__18->SetStats(0);
   hframe__18->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__18->GetXaxis()->SetNdivisions(506);
   hframe__18->GetXaxis()->SetLabelFont(43);
   hframe__18->GetXaxis()->SetLabelOffset(999);
   hframe__18->GetXaxis()->SetLabelSize(0);
   hframe__18->GetXaxis()->SetTitleSize(18);
   hframe__18->GetXaxis()->SetTitleOffset(7.5);
   hframe__18->GetXaxis()->SetTitleFont(43);
   hframe__18->GetYaxis()->SetTitle("d^{2}#sigma/d#it{p}_{T}d#it{#eta} (nb GeV^{-1}#it{c})");
   hframe__18->GetYaxis()->SetNdivisions(506);
   hframe__18->GetYaxis()->SetLabelFont(43);
   hframe__18->GetYaxis()->SetLabelSize(18);
   hframe__18->GetYaxis()->SetTitleSize(18);
   hframe__18->GetYaxis()->SetTitleOffset(5.5);
   hframe__18->GetYaxis()->SetTitleFont(43);
   hframe__18->GetZaxis()->SetLabelFont(43);
   hframe__18->GetZaxis()->SetLabelSize(18);
   hframe__18->GetZaxis()->SetTitleOffset(1.1);
   hframe__18->GetZaxis()->SetTitleFont(43);
   hframe__18->Draw("sameaxis");
   cross_section_CPV_pad->Modified();
   c_cross_section_variations_to_std_BOTTOM_pad->cd();
  
// ------------>Primitives in pad: syst_CPV_pad
   syst_CPV_pad = new TPad("syst_CPV_pad", "syst_CPV_pad",0.5,0,0.8333333,0.3);
   syst_CPV_pad->Draw();
   syst_CPV_pad->cd();
   syst_CPV_pad->Range(-4,-12.45266,62.66667,7.961537);
   syst_CPV_pad->SetFillColor(0);
   syst_CPV_pad->SetBorderMode(0);
   syst_CPV_pad->SetBorderSize(2);
   syst_CPV_pad->SetTickx(1);
   syst_CPV_pad->SetTicky(1);
   syst_CPV_pad->SetLeftMargin(0.18);
   syst_CPV_pad->SetRightMargin(0.01);
   syst_CPV_pad->SetTopMargin(0.03);
   syst_CPV_pad->SetBottomMargin(0.25);
   syst_CPV_pad->SetFrameBorderMode(0);
   syst_CPV_pad->SetFrameBorderMode(0);
   
   TH1F *hframe__19 = new TH1F("hframe__19","",1000,8,62);
   hframe__19->SetMinimum(-7.349111);
   hframe__19->SetMaximum(7.349111);
   hframe__19->SetDirectory(0);
   hframe__19->SetStats(0);
   hframe__19->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__19->GetXaxis()->SetNdivisions(506);
   hframe__19->GetXaxis()->SetLabelFont(43);
   hframe__19->GetXaxis()->SetLabelSize(18);
   hframe__19->GetXaxis()->SetTitleSize(18);
   hframe__19->GetXaxis()->SetTickLength(0.07);
   hframe__19->GetXaxis()->SetTitleOffset(7.5);
   hframe__19->GetXaxis()->SetTitleFont(43);
   hframe__19->GetYaxis()->SetTitle("Rel. diff. (%)");
   hframe__19->GetYaxis()->SetNdivisions(506);
   hframe__19->GetYaxis()->SetLabelFont(43);
   hframe__19->GetYaxis()->SetLabelSize(18);
   hframe__19->GetYaxis()->SetTitleSize(18);
   hframe__19->GetYaxis()->SetTitleOffset(5.5);
   hframe__19->GetYaxis()->SetTitleFont(43);
   hframe__19->GetZaxis()->SetLabelFont(43);
   hframe__19->GetZaxis()->SetLabelSize(18);
   hframe__19->GetZaxis()->SetTitleOffset(1.1);
   hframe__19->GetZaxis()->SetTitleFont(43);
   hframe__19->Draw(" ");
   line = new TLine(0.18,0.61,0.99,0.61);
   line->SetLineStyle(3);
   line->Draw();
   Double_t xAxis8[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_CPV_loose = new TH1D("syst_CPV_loose","",9, xAxis8);
   syst_CPV_loose->SetBinContent(1,3.488669);
   syst_CPV_loose->SetBinContent(2,-1.235135);
   syst_CPV_loose->SetBinContent(3,3.252469);
   syst_CPV_loose->SetBinContent(4,-0.8280857);
   syst_CPV_loose->SetBinContent(5,0.5184885);
   syst_CPV_loose->SetBinContent(6,2.724583);
   syst_CPV_loose->SetBinContent(7,-0.4948782);
   syst_CPV_loose->SetBinContent(8,1.929963);
   syst_CPV_loose->SetBinContent(9,-1.022178);
   syst_CPV_loose->SetBinError(1,3.39452);
   syst_CPV_loose->SetBinError(2,2.510211);
   syst_CPV_loose->SetBinError(3,1.927392);
   syst_CPV_loose->SetBinError(4,1.430787);
   syst_CPV_loose->SetBinError(5,1.823654);
   syst_CPV_loose->SetBinError(6,2.333686);
   syst_CPV_loose->SetBinError(7,3.703181);
   syst_CPV_loose->SetBinError(8,5.949176);
   syst_CPV_loose->SetBinError(9,3.763668);
   syst_CPV_loose->SetEntries(0.7262827);

   ci = TColor::GetColor("#99cccc");
   syst_CPV_loose->SetFillColor(ci);
   syst_CPV_loose->SetFillStyle(0);

   ci = TColor::GetColor("#99cccc");
   syst_CPV_loose->SetLineColor(ci);

   ci = TColor::GetColor("#99cccc");
   syst_CPV_loose->SetMarkerColor(ci);
   syst_CPV_loose->SetMarkerSize(1.1);
   syst_CPV_loose->GetXaxis()->SetLabelFont(42);
   syst_CPV_loose->GetXaxis()->SetLabelSize(0.035);
   syst_CPV_loose->GetXaxis()->SetTitleSize(0.035);
   syst_CPV_loose->GetXaxis()->SetTitleFont(42);
   syst_CPV_loose->GetYaxis()->SetLabelFont(42);
   syst_CPV_loose->GetYaxis()->SetLabelSize(0.035);
   syst_CPV_loose->GetYaxis()->SetTitleSize(0.035);
   syst_CPV_loose->GetYaxis()->SetTitleFont(42);
   syst_CPV_loose->GetZaxis()->SetLabelFont(42);
   syst_CPV_loose->GetZaxis()->SetLabelSize(0.035);
   syst_CPV_loose->GetZaxis()->SetTitleSize(0.035);
   syst_CPV_loose->GetZaxis()->SetTitleFont(42);
   syst_CPV_loose->Draw("hist][same");
   Double_t xAxis9[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_CPV_tight = new TH1D("syst_CPV_tight","",9, xAxis9);
   syst_CPV_tight->SetBinContent(1,-3.159719);
   syst_CPV_tight->SetBinContent(2,-3.205749);
   syst_CPV_tight->SetBinContent(3,1.52492);
   syst_CPV_tight->SetBinContent(4,0.0488541);
   syst_CPV_tight->SetBinContent(5,-3.664913);
   syst_CPV_tight->SetBinContent(6,5.879289);
   syst_CPV_tight->SetBinContent(7,4.001062);
   syst_CPV_tight->SetBinContent(8,1.456189);
   syst_CPV_tight->SetBinContent(9,5.844539);
   syst_CPV_tight->SetBinError(1,1.118152);
   syst_CPV_tight->SetBinError(2,2.134427);
   syst_CPV_tight->SetBinError(3,1.372067);
   syst_CPV_tight->SetBinError(4,2.742395);
   syst_CPV_tight->SetBinError(5,3.67976);
   syst_CPV_tight->SetBinError(6,3.096768);
   syst_CPV_tight->SetBinError(7,3.059548);
   syst_CPV_tight->SetBinError(8,3.271741);
   syst_CPV_tight->SetBinError(9,14.60479);
   syst_CPV_tight->SetEntries(0.2801437);

   ci = TColor::GetColor("#cc6666");
   syst_CPV_tight->SetFillColor(ci);
   syst_CPV_tight->SetFillStyle(0);

   ci = TColor::GetColor("#cc6666");
   syst_CPV_tight->SetLineColor(ci);

   ci = TColor::GetColor("#cc6666");
   syst_CPV_tight->SetMarkerColor(ci);
   syst_CPV_tight->SetMarkerSize(1.1);
   syst_CPV_tight->GetXaxis()->SetLabelFont(42);
   syst_CPV_tight->GetXaxis()->SetLabelSize(0.035);
   syst_CPV_tight->GetXaxis()->SetTitleSize(0.035);
   syst_CPV_tight->GetXaxis()->SetTitleFont(42);
   syst_CPV_tight->GetYaxis()->SetLabelFont(42);
   syst_CPV_tight->GetYaxis()->SetLabelSize(0.035);
   syst_CPV_tight->GetYaxis()->SetTitleSize(0.035);
   syst_CPV_tight->GetYaxis()->SetTitleFont(42);
   syst_CPV_tight->GetZaxis()->SetLabelFont(42);
   syst_CPV_tight->GetZaxis()->SetLabelSize(0.035);
   syst_CPV_tight->GetZaxis()->SetTitleSize(0.035);
   syst_CPV_tight->GetZaxis()->SetTitleFont(42);
   syst_CPV_tight->Draw("hist][same");
   
   TH1F *hframe__20 = new TH1F("hframe__20","",1000,8,62);
   hframe__20->SetMinimum(-7.349111);
   hframe__20->SetMaximum(7.349111);
   hframe__20->SetDirectory(0);
   hframe__20->SetStats(0);
   hframe__20->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__20->GetXaxis()->SetNdivisions(506);
   hframe__20->GetXaxis()->SetLabelFont(43);
   hframe__20->GetXaxis()->SetLabelSize(18);
   hframe__20->GetXaxis()->SetTitleSize(18);
   hframe__20->GetXaxis()->SetTickLength(0.07);
   hframe__20->GetXaxis()->SetTitleOffset(7.5);
   hframe__20->GetXaxis()->SetTitleFont(43);
   hframe__20->GetYaxis()->SetTitle("Rel. diff. (%)");
   hframe__20->GetYaxis()->SetNdivisions(506);
   hframe__20->GetYaxis()->SetLabelFont(43);
   hframe__20->GetYaxis()->SetLabelSize(18);
   hframe__20->GetYaxis()->SetTitleSize(18);
   hframe__20->GetYaxis()->SetTitleOffset(5.5);
   hframe__20->GetYaxis()->SetTitleFont(43);
   hframe__20->GetZaxis()->SetLabelFont(43);
   hframe__20->GetZaxis()->SetLabelSize(18);
   hframe__20->GetZaxis()->SetTitleOffset(1.1);
   hframe__20->GetZaxis()->SetTitleFont(43);
   hframe__20->Draw("sameaxis");
   syst_CPV_pad->Modified();
   c_cross_section_variations_to_std_BOTTOM_pad->cd();
   c_cross_section_variations_to_std_BOTTOM_pad->Modified();
   c_cross_section_variations_to_std->cd();
   c_cross_section_variations_to_std->Modified();
   c_cross_section_variations_to_std->cd();
   c_cross_section_variations_to_std->SetSelected(c_cross_section_variations_to_std);
}
