{
//=========Macro generated from canvas: c_cross_section_smoothing_check/c_cross_section_smoothing_check
//=========  (Tue May 28 17:30:25 2019) by ROOT version5.34/30
   TCanvas *c_cross_section_smoothing_check = new TCanvas("c_cross_section_smoothing_check", "c_cross_section_smoothing_check",0,22,1500,1000);
   gStyle->SetOptStat(0);
   c_cross_section_smoothing_check->SetHighLightColor(2);
   c_cross_section_smoothing_check->Range(0,0,1,1);
   c_cross_section_smoothing_check->SetFillColor(10);
   c_cross_section_smoothing_check->SetBorderMode(0);
   c_cross_section_smoothing_check->SetBorderSize(2);
   c_cross_section_smoothing_check->SetTickx(1);
   c_cross_section_smoothing_check->SetTicky(1);
   c_cross_section_smoothing_check->SetLeftMargin(0.135);
   c_cross_section_smoothing_check->SetRightMargin(0.035);
   c_cross_section_smoothing_check->SetTopMargin(0.03);
   c_cross_section_smoothing_check->SetBottomMargin(0.125);
   c_cross_section_smoothing_check->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: c_cross_section_smoothing_check_1
   TPad *c_cross_section_smoothing_check_1 = new TPad("c_cross_section_smoothing_check_1", "c_cross_section_smoothing_check_1",0.005,0.501,0.3283333,0.999);
   c_cross_section_smoothing_check_1->Draw();
   c_cross_section_smoothing_check_1->cd();
   c_cross_section_smoothing_check_1->Range(-0.7831331,-3.698225,64.27711,25.88757);
   c_cross_section_smoothing_check_1->SetFillColor(10);
   c_cross_section_smoothing_check_1->SetBorderMode(0);
   c_cross_section_smoothing_check_1->SetBorderSize(2);
   c_cross_section_smoothing_check_1->SetTickx(1);
   c_cross_section_smoothing_check_1->SetTicky(1);
   c_cross_section_smoothing_check_1->SetLeftMargin(0.135);
   c_cross_section_smoothing_check_1->SetRightMargin(0.035);
   c_cross_section_smoothing_check_1->SetTopMargin(0.03);
   c_cross_section_smoothing_check_1->SetBottomMargin(0.125);
   c_cross_section_smoothing_check_1->SetFrameFillColor(0);
   c_cross_section_smoothing_check_1->SetFrameBorderMode(0);
   c_cross_section_smoothing_check_1->SetFrameFillColor(0);
   c_cross_section_smoothing_check_1->SetFrameBorderMode(0);
   
   TH1F *hframe__57 = new TH1F("hframe__57","",1000,8,62);
   hframe__57->SetMinimum(0);
   hframe__57->SetMaximum(25);
   hframe__57->SetDirectory(0);
   hframe__57->SetStats(0);
   hframe__57->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__57->GetXaxis()->SetNdivisions(506);
   hframe__57->GetXaxis()->SetLabelFont(43);
   hframe__57->GetXaxis()->SetLabelSize(24);
   hframe__57->GetXaxis()->SetTitleSize(24);
   hframe__57->GetXaxis()->SetTitleOffset(2.3);
   hframe__57->GetXaxis()->SetTitleFont(43);
   hframe__57->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__57->GetYaxis()->SetNdivisions(506);
   hframe__57->GetYaxis()->SetLabelFont(43);
   hframe__57->GetYaxis()->SetLabelSize(24);
   hframe__57->GetYaxis()->SetTitleSize(24);
   hframe__57->GetYaxis()->SetTitleOffset(2.8);
   hframe__57->GetYaxis()->SetTitleFont(43);
   hframe__57->GetZaxis()->SetLabelFont(43);
   hframe__57->GetZaxis()->SetLabelSize(24);
   hframe__57->GetZaxis()->SetTitleOffset(1.1);
   hframe__57->GetZaxis()->SetTitleFont(43);
   hframe__57->Draw(" ");
   Double_t xAxis17[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_sigma_long_sig_shift = new TH1D("syst_sigma_long_sig_shift","",9, xAxis17);
   syst_sigma_long_sig_shift->SetBinContent(1,3.276112);
   syst_sigma_long_sig_shift->SetBinContent(2,3.17158);
   syst_sigma_long_sig_shift->SetBinContent(3,5.553464);
   syst_sigma_long_sig_shift->SetBinContent(4,2.960454);
   syst_sigma_long_sig_shift->SetBinContent(5,7.832539);
   syst_sigma_long_sig_shift->SetBinContent(6,4.862767);
   syst_sigma_long_sig_shift->SetBinContent(7,12.97419);
   syst_sigma_long_sig_shift->SetBinContent(8,11.41165);
   syst_sigma_long_sig_shift->SetBinContent(9,6.970972);
   syst_sigma_long_sig_shift->SetBinError(1,5.811248);
   syst_sigma_long_sig_shift->SetBinError(2,5.490772);
   syst_sigma_long_sig_shift->SetBinError(3,2.810819);
   syst_sigma_long_sig_shift->SetBinError(4,2.349515);
   syst_sigma_long_sig_shift->SetBinError(5,9.475266);
   syst_sigma_long_sig_shift->SetBinError(6,10.59213);
   syst_sigma_long_sig_shift->SetBinError(7,13.07963);
   syst_sigma_long_sig_shift->SetBinError(8,12.3905);
   syst_sigma_long_sig_shift->SetBinError(9,15.699);
   syst_sigma_long_sig_shift->SetEntries(9);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift->SetFillColor(ci);
   syst_sigma_long_sig_shift->SetFillStyle(0);

   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift->SetLineColor(ci);

   ci = TColor::GetColor("#cccc33");
   syst_sigma_long_sig_shift->SetMarkerColor(ci);
   syst_sigma_long_sig_shift->SetMarkerStyle(24);
   syst_sigma_long_sig_shift->SetMarkerSize(1.1);
   syst_sigma_long_sig_shift->GetXaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift->GetXaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift->GetXaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift->GetXaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift->GetYaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift->GetYaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift->GetYaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift->GetYaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift->GetZaxis()->SetLabelFont(42);
   syst_sigma_long_sig_shift->GetZaxis()->SetLabelSize(0.035);
   syst_sigma_long_sig_shift->GetZaxis()->SetTitleSize(0.035);
   syst_sigma_long_sig_shift->GetZaxis()->SetTitleFont(42);
   syst_sigma_long_sig_shift->Draw("CPsame");
   
   TLegend *leg = new TLegend(0.18,0.755,0.57,0.855,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(18);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("syst_sigma_long_sig_shift_fit_inv_exp_FULL","Inv. exp. fit (10, 60) GeV/#it{c}","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("NULL","#chi^{2}/ndf = 0.196","");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   leg->Draw();
   TLatex *   tex = new TLatex(0.19,0.885,"Signal #sigma_{long}^{2} cut");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__58 = new TH1F("hframe__58","",1000,8,62);
   hframe__58->SetMinimum(0);
   hframe__58->SetMaximum(25);
   hframe__58->SetDirectory(0);
   hframe__58->SetStats(0);
   hframe__58->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__58->GetXaxis()->SetNdivisions(506);
   hframe__58->GetXaxis()->SetLabelFont(43);
   hframe__58->GetXaxis()->SetLabelSize(24);
   hframe__58->GetXaxis()->SetTitleSize(24);
   hframe__58->GetXaxis()->SetTitleOffset(2.3);
   hframe__58->GetXaxis()->SetTitleFont(43);
   hframe__58->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__58->GetYaxis()->SetNdivisions(506);
   hframe__58->GetYaxis()->SetLabelFont(43);
   hframe__58->GetYaxis()->SetLabelSize(24);
   hframe__58->GetYaxis()->SetTitleSize(24);
   hframe__58->GetYaxis()->SetTitleOffset(2.8);
   hframe__58->GetYaxis()->SetTitleFont(43);
   hframe__58->GetZaxis()->SetLabelFont(43);
   hframe__58->GetZaxis()->SetLabelSize(24);
   hframe__58->GetZaxis()->SetTitleOffset(1.1);
   hframe__58->GetZaxis()->SetTitleFont(43);
   hframe__58->Draw("sameaxis");
   c_cross_section_smoothing_check_1->Modified();
   c_cross_section_smoothing_check->cd();
  
// ------------>Primitives in pad: c_cross_section_smoothing_check_2
   c_cross_section_smoothing_check_2 = new TPad("c_cross_section_smoothing_check_2", "c_cross_section_smoothing_check_2",0.3383333,0.501,0.6616667,0.999);
   c_cross_section_smoothing_check_2->Draw();
   c_cross_section_smoothing_check_2->cd();
   c_cross_section_smoothing_check_2->Range(-0.7831331,-2.95858,64.27711,20.71006);
   c_cross_section_smoothing_check_2->SetFillColor(10);
   c_cross_section_smoothing_check_2->SetBorderMode(0);
   c_cross_section_smoothing_check_2->SetBorderSize(2);
   c_cross_section_smoothing_check_2->SetTickx(1);
   c_cross_section_smoothing_check_2->SetTicky(1);
   c_cross_section_smoothing_check_2->SetLeftMargin(0.135);
   c_cross_section_smoothing_check_2->SetRightMargin(0.035);
   c_cross_section_smoothing_check_2->SetTopMargin(0.03);
   c_cross_section_smoothing_check_2->SetBottomMargin(0.125);
   c_cross_section_smoothing_check_2->SetFrameFillColor(0);
   c_cross_section_smoothing_check_2->SetFrameBorderMode(0);
   c_cross_section_smoothing_check_2->SetFrameFillColor(0);
   c_cross_section_smoothing_check_2->SetFrameBorderMode(0);
   
   TH1F *hframe__59 = new TH1F("hframe__59","",1000,8,62);
   hframe__59->SetMinimum(0);
   hframe__59->SetMaximum(20);
   hframe__59->SetDirectory(0);
   hframe__59->SetStats(0);
   hframe__59->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__59->GetXaxis()->SetNdivisions(506);
   hframe__59->GetXaxis()->SetLabelFont(43);
   hframe__59->GetXaxis()->SetLabelSize(24);
   hframe__59->GetXaxis()->SetTitleSize(24);
   hframe__59->GetXaxis()->SetTitleOffset(2.3);
   hframe__59->GetXaxis()->SetTitleFont(43);
   hframe__59->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__59->GetYaxis()->SetNdivisions(506);
   hframe__59->GetYaxis()->SetLabelFont(43);
   hframe__59->GetYaxis()->SetLabelSize(24);
   hframe__59->GetYaxis()->SetTitleSize(24);
   hframe__59->GetYaxis()->SetTitleOffset(2.8);
   hframe__59->GetYaxis()->SetTitleFont(43);
   hframe__59->GetZaxis()->SetLabelFont(43);
   hframe__59->GetZaxis()->SetLabelSize(24);
   hframe__59->GetZaxis()->SetTitleOffset(1.1);
   hframe__59->GetZaxis()->SetTitleFont(43);
   hframe__59->Draw(" ");
   Double_t xAxis18[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_sigma_long_bkg_shift = new TH1D("syst_sigma_long_bkg_shift","",9, xAxis18);
   syst_sigma_long_bkg_shift->SetBinContent(1,1.453664);
   syst_sigma_long_bkg_shift->SetBinContent(2,2.373924);
   syst_sigma_long_bkg_shift->SetBinContent(3,1.616223);
   syst_sigma_long_bkg_shift->SetBinContent(4,1.134771);
   syst_sigma_long_bkg_shift->SetBinContent(5,2.903577);
   syst_sigma_long_bkg_shift->SetBinContent(6,0.7125686);
   syst_sigma_long_bkg_shift->SetBinContent(7,9.173118);
   syst_sigma_long_bkg_shift->SetBinContent(8,8.943391);
   syst_sigma_long_bkg_shift->SetBinContent(9,2.617027);
   syst_sigma_long_bkg_shift->SetBinError(1,2.568267);
   syst_sigma_long_bkg_shift->SetBinError(2,1.521731);
   syst_sigma_long_bkg_shift->SetBinError(3,1.24644);
   syst_sigma_long_bkg_shift->SetBinError(4,2.560391);
   syst_sigma_long_bkg_shift->SetBinError(5,1.270217);
   syst_sigma_long_bkg_shift->SetBinError(6,4.25182);
   syst_sigma_long_bkg_shift->SetBinError(7,11.20537);
   syst_sigma_long_bkg_shift->SetBinError(8,12.12853);
   syst_sigma_long_bkg_shift->SetBinError(9,11.75519);
   syst_sigma_long_bkg_shift->SetEntries(9);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift->SetFillColor(ci);
   syst_sigma_long_bkg_shift->SetFillStyle(0);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift->SetLineColor(ci);

   ci = TColor::GetColor("#9966cc");
   syst_sigma_long_bkg_shift->SetMarkerColor(ci);
   syst_sigma_long_bkg_shift->SetMarkerStyle(24);
   syst_sigma_long_bkg_shift->SetMarkerSize(1.1);
   syst_sigma_long_bkg_shift->GetXaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift->GetXaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift->GetXaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift->GetXaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift->GetYaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift->GetYaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift->GetYaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift->GetYaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift->GetZaxis()->SetLabelFont(42);
   syst_sigma_long_bkg_shift->GetZaxis()->SetLabelSize(0.035);
   syst_sigma_long_bkg_shift->GetZaxis()->SetTitleSize(0.035);
   syst_sigma_long_bkg_shift->GetZaxis()->SetTitleFont(42);
   syst_sigma_long_bkg_shift->Draw("CPsame");
   
   leg = new TLegend(0.18,0.755,0.57,0.855,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(18);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("syst_sigma_long_bkg_shift_fit_cst","Const. fit (10, 60) GeV/#it{c}","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("NULL","#chi^{2}/ndf = 0.201","");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   leg->Draw();
      tex = new TLatex(0.19,0.885,"Bkg. #sigma_{long}^{2} cut");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__60 = new TH1F("hframe__60","",1000,8,62);
   hframe__60->SetMinimum(0);
   hframe__60->SetMaximum(20);
   hframe__60->SetDirectory(0);
   hframe__60->SetStats(0);
   hframe__60->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__60->GetXaxis()->SetNdivisions(506);
   hframe__60->GetXaxis()->SetLabelFont(43);
   hframe__60->GetXaxis()->SetLabelSize(24);
   hframe__60->GetXaxis()->SetTitleSize(24);
   hframe__60->GetXaxis()->SetTitleOffset(2.3);
   hframe__60->GetXaxis()->SetTitleFont(43);
   hframe__60->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__60->GetYaxis()->SetNdivisions(506);
   hframe__60->GetYaxis()->SetLabelFont(43);
   hframe__60->GetYaxis()->SetLabelSize(24);
   hframe__60->GetYaxis()->SetTitleSize(24);
   hframe__60->GetYaxis()->SetTitleOffset(2.8);
   hframe__60->GetYaxis()->SetTitleFont(43);
   hframe__60->GetZaxis()->SetLabelFont(43);
   hframe__60->GetZaxis()->SetLabelSize(24);
   hframe__60->GetZaxis()->SetTitleOffset(1.1);
   hframe__60->GetZaxis()->SetTitleFont(43);
   hframe__60->Draw("sameaxis");
   c_cross_section_smoothing_check_2->Modified();
   c_cross_section_smoothing_check->cd();
  
// ------------>Primitives in pad: c_cross_section_smoothing_check_3
   c_cross_section_smoothing_check_3 = new TPad("c_cross_section_smoothing_check_3", "c_cross_section_smoothing_check_3",0.6716667,0.501,0.995,0.999);
   c_cross_section_smoothing_check_3->Draw();
   c_cross_section_smoothing_check_3->cd();
   c_cross_section_smoothing_check_3->Range(-0.7831331,-0.295858,64.27711,2.071006);
   c_cross_section_smoothing_check_3->SetFillColor(10);
   c_cross_section_smoothing_check_3->SetBorderMode(0);
   c_cross_section_smoothing_check_3->SetBorderSize(2);
   c_cross_section_smoothing_check_3->SetTickx(1);
   c_cross_section_smoothing_check_3->SetTicky(1);
   c_cross_section_smoothing_check_3->SetLeftMargin(0.135);
   c_cross_section_smoothing_check_3->SetRightMargin(0.035);
   c_cross_section_smoothing_check_3->SetTopMargin(0.03);
   c_cross_section_smoothing_check_3->SetBottomMargin(0.125);
   c_cross_section_smoothing_check_3->SetFrameFillColor(0);
   c_cross_section_smoothing_check_3->SetFrameBorderMode(0);
   c_cross_section_smoothing_check_3->SetFrameFillColor(0);
   c_cross_section_smoothing_check_3->SetFrameBorderMode(0);
   
   TH1F *hframe__61 = new TH1F("hframe__61","",1000,8,62);
   hframe__61->SetMinimum(0);
   hframe__61->SetMaximum(2);
   hframe__61->SetDirectory(0);
   hframe__61->SetStats(0);
   hframe__61->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__61->GetXaxis()->SetNdivisions(506);
   hframe__61->GetXaxis()->SetLabelFont(43);
   hframe__61->GetXaxis()->SetLabelSize(24);
   hframe__61->GetXaxis()->SetTitleSize(24);
   hframe__61->GetXaxis()->SetTitleOffset(2.3);
   hframe__61->GetXaxis()->SetTitleFont(43);
   hframe__61->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__61->GetYaxis()->SetNdivisions(506);
   hframe__61->GetYaxis()->SetLabelFont(43);
   hframe__61->GetYaxis()->SetLabelSize(24);
   hframe__61->GetYaxis()->SetTitleSize(24);
   hframe__61->GetYaxis()->SetTitleOffset(2.8);
   hframe__61->GetYaxis()->SetTitleFont(43);
   hframe__61->GetZaxis()->SetLabelFont(43);
   hframe__61->GetZaxis()->SetLabelSize(24);
   hframe__61->GetZaxis()->SetTitleOffset(1.1);
   hframe__61->GetZaxis()->SetTitleFont(43);
   hframe__61->Draw(" ");
   Double_t xAxis19[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_gamma_jet_weight = new TH1D("syst_gamma_jet_weight","",9, xAxis19);
   syst_gamma_jet_weight->SetBinContent(1,0.2477235);
   syst_gamma_jet_weight->SetBinContent(2,0.2509481);
   syst_gamma_jet_weight->SetBinContent(3,0.1970222);
   syst_gamma_jet_weight->SetBinContent(4,0.2440967);
   syst_gamma_jet_weight->SetBinContent(5,0.2094295);
   syst_gamma_jet_weight->SetBinContent(6,0.3006074);
   syst_gamma_jet_weight->SetBinContent(7,0.5561716);
   syst_gamma_jet_weight->SetBinContent(8,0.8295943);
   syst_gamma_jet_weight->SetBinContent(9,0.9476155);
   syst_gamma_jet_weight->SetBinError(1,0.5288027);
   syst_gamma_jet_weight->SetBinError(2,0.7807005);
   syst_gamma_jet_weight->SetBinError(3,0.1141719);
   syst_gamma_jet_weight->SetBinError(4,0.5228587);
   syst_gamma_jet_weight->SetBinError(5,0.6118531);
   syst_gamma_jet_weight->SetBinError(6,0.7378542);
   syst_gamma_jet_weight->SetBinError(7,2.08569);
   syst_gamma_jet_weight->SetBinError(8,3.254871);
   syst_gamma_jet_weight->SetBinError(9,5.047501);
   syst_gamma_jet_weight->SetEntries(9);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight->SetFillColor(ci);
   syst_gamma_jet_weight->SetFillStyle(0);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight->SetLineColor(ci);

   ci = TColor::GetColor("#6699cc");
   syst_gamma_jet_weight->SetMarkerColor(ci);
   syst_gamma_jet_weight->SetMarkerStyle(24);
   syst_gamma_jet_weight->SetMarkerSize(1.1);
   syst_gamma_jet_weight->GetXaxis()->SetLabelFont(42);
   syst_gamma_jet_weight->GetXaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight->GetXaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight->GetXaxis()->SetTitleFont(42);
   syst_gamma_jet_weight->GetYaxis()->SetLabelFont(42);
   syst_gamma_jet_weight->GetYaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight->GetYaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight->GetYaxis()->SetTitleFont(42);
   syst_gamma_jet_weight->GetZaxis()->SetLabelFont(42);
   syst_gamma_jet_weight->GetZaxis()->SetLabelSize(0.035);
   syst_gamma_jet_weight->GetZaxis()->SetTitleSize(0.035);
   syst_gamma_jet_weight->GetZaxis()->SetTitleFont(42);
   syst_gamma_jet_weight->Draw("CPsame");
   
   leg = new TLegend(0.18,0.755,0.57,0.855,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(18);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("syst_gamma_jet_weight_fit_pol1","Lin. fit (10, 60) GeV/#it{c}","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("NULL","#chi^{2}/ndf = 0.011","");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   leg->Draw();
      tex = new TLatex(0.19,0.885,"MC signal amount");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__62 = new TH1F("hframe__62","",1000,8,62);
   hframe__62->SetMinimum(0);
   hframe__62->SetMaximum(2);
   hframe__62->SetDirectory(0);
   hframe__62->SetStats(0);
   hframe__62->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__62->GetXaxis()->SetNdivisions(506);
   hframe__62->GetXaxis()->SetLabelFont(43);
   hframe__62->GetXaxis()->SetLabelSize(24);
   hframe__62->GetXaxis()->SetTitleSize(24);
   hframe__62->GetXaxis()->SetTitleOffset(2.3);
   hframe__62->GetXaxis()->SetTitleFont(43);
   hframe__62->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__62->GetYaxis()->SetNdivisions(506);
   hframe__62->GetYaxis()->SetLabelFont(43);
   hframe__62->GetYaxis()->SetLabelSize(24);
   hframe__62->GetYaxis()->SetTitleSize(24);
   hframe__62->GetYaxis()->SetTitleOffset(2.8);
   hframe__62->GetYaxis()->SetTitleFont(43);
   hframe__62->GetZaxis()->SetLabelFont(43);
   hframe__62->GetZaxis()->SetLabelSize(24);
   hframe__62->GetZaxis()->SetTitleOffset(1.1);
   hframe__62->GetZaxis()->SetTitleFont(43);
   hframe__62->Draw("sameaxis");
   c_cross_section_smoothing_check_3->Modified();
   c_cross_section_smoothing_check->cd();
  
// ------------>Primitives in pad: c_cross_section_smoothing_check_4
   c_cross_section_smoothing_check_4 = new TPad("c_cross_section_smoothing_check_4", "c_cross_section_smoothing_check_4",0.005,0.001,0.3283333,0.499);
   c_cross_section_smoothing_check_4->Draw();
   c_cross_section_smoothing_check_4->cd();
   c_cross_section_smoothing_check_4->Range(-0.7831331,-1.47929,64.27711,10.35503);
   c_cross_section_smoothing_check_4->SetFillColor(10);
   c_cross_section_smoothing_check_4->SetBorderMode(0);
   c_cross_section_smoothing_check_4->SetBorderSize(2);
   c_cross_section_smoothing_check_4->SetTickx(1);
   c_cross_section_smoothing_check_4->SetTicky(1);
   c_cross_section_smoothing_check_4->SetLeftMargin(0.135);
   c_cross_section_smoothing_check_4->SetRightMargin(0.035);
   c_cross_section_smoothing_check_4->SetTopMargin(0.03);
   c_cross_section_smoothing_check_4->SetBottomMargin(0.125);
   c_cross_section_smoothing_check_4->SetFrameFillColor(0);
   c_cross_section_smoothing_check_4->SetFrameBorderMode(0);
   c_cross_section_smoothing_check_4->SetFrameFillColor(0);
   c_cross_section_smoothing_check_4->SetFrameBorderMode(0);
   
   TH1F *hframe__63 = new TH1F("hframe__63","",1000,8,62);
   hframe__63->SetMinimum(0);
   hframe__63->SetMaximum(10);
   hframe__63->SetDirectory(0);
   hframe__63->SetStats(0);
   hframe__63->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__63->GetXaxis()->SetNdivisions(506);
   hframe__63->GetXaxis()->SetLabelFont(43);
   hframe__63->GetXaxis()->SetLabelSize(24);
   hframe__63->GetXaxis()->SetTitleSize(24);
   hframe__63->GetXaxis()->SetTitleOffset(2.3);
   hframe__63->GetXaxis()->SetTitleFont(43);
   hframe__63->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__63->GetYaxis()->SetNdivisions(506);
   hframe__63->GetYaxis()->SetLabelFont(43);
   hframe__63->GetYaxis()->SetLabelSize(24);
   hframe__63->GetYaxis()->SetTitleSize(24);
   hframe__63->GetYaxis()->SetTitleOffset(2.8);
   hframe__63->GetYaxis()->SetTitleFont(43);
   hframe__63->GetZaxis()->SetLabelFont(43);
   hframe__63->GetZaxis()->SetLabelSize(24);
   hframe__63->GetZaxis()->SetTitleOffset(1.1);
   hframe__63->GetZaxis()->SetTitleFont(43);
   hframe__63->Draw(" ");
   Double_t xAxis20[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_no_smearing_final = new TH1D("syst_no_smearing_final","",9, xAxis20);
   syst_no_smearing_final->SetBinContent(1,5.999826);
   syst_no_smearing_final->SetBinContent(2,2.709455);
   syst_no_smearing_final->SetBinContent(3,0.03123523);
   syst_no_smearing_final->SetBinContent(4,2.478433);
   syst_no_smearing_final->SetBinContent(5,4.073498);
   syst_no_smearing_final->SetBinContent(6,4.542326);
   syst_no_smearing_final->SetBinContent(7,4.051406);
   syst_no_smearing_final->SetBinContent(8,4.474465);
   syst_no_smearing_final->SetBinContent(9,3.171856);
   syst_no_smearing_final->SetBinError(1,1.833419);
   syst_no_smearing_final->SetBinError(2,0.5054233);
   syst_no_smearing_final->SetBinError(3,0.5776185);
   syst_no_smearing_final->SetBinError(4,2.879208);
   syst_no_smearing_final->SetBinError(5,2.691847);
   syst_no_smearing_final->SetBinError(6,2.422922);
   syst_no_smearing_final->SetBinError(7,3.178881);
   syst_no_smearing_final->SetBinError(8,4.151014);
   syst_no_smearing_final->SetBinError(9,5.560586);
   syst_no_smearing_final->SetEntries(9);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_final->SetFillColor(ci);
   syst_no_smearing_final->SetFillStyle(0);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_final->SetLineColor(ci);

   ci = TColor::GetColor("#66cc99");
   syst_no_smearing_final->SetMarkerColor(ci);
   syst_no_smearing_final->SetMarkerStyle(24);
   syst_no_smearing_final->SetMarkerSize(1.1);
   syst_no_smearing_final->GetXaxis()->SetLabelFont(42);
   syst_no_smearing_final->GetXaxis()->SetLabelSize(0.035);
   syst_no_smearing_final->GetXaxis()->SetTitleSize(0.035);
   syst_no_smearing_final->GetXaxis()->SetTitleFont(42);
   syst_no_smearing_final->GetYaxis()->SetLabelFont(42);
   syst_no_smearing_final->GetYaxis()->SetLabelSize(0.035);
   syst_no_smearing_final->GetYaxis()->SetTitleSize(0.035);
   syst_no_smearing_final->GetYaxis()->SetTitleFont(42);
   syst_no_smearing_final->GetZaxis()->SetLabelFont(42);
   syst_no_smearing_final->GetZaxis()->SetLabelSize(0.035);
   syst_no_smearing_final->GetZaxis()->SetTitleSize(0.035);
   syst_no_smearing_final->GetZaxis()->SetTitleFont(42);
   syst_no_smearing_final->Draw("CPsame");
   
   TF1 *syst_no_smearing_final_fit_exp_FULL = new TF1("syst_no_smearing_final_fit_exp_FULL","expo",10,60);
   syst_no_smearing_final_fit_exp_FULL->SetFillStyle(0);
   syst_no_smearing_final_fit_exp_FULL->SetLineWidth(1);
   syst_no_smearing_final_fit_exp_FULL->SetLineStyle(2);
   syst_no_smearing_final_fit_exp_FULL->GetXaxis()->SetNdivisions(506);
   syst_no_smearing_final_fit_exp_FULL->GetXaxis()->SetLabelFont(43);
   syst_no_smearing_final_fit_exp_FULL->GetXaxis()->SetLabelSize(24);
   syst_no_smearing_final_fit_exp_FULL->GetXaxis()->SetTitleSize(24);
   syst_no_smearing_final_fit_exp_FULL->GetXaxis()->SetTitleOffset(2.3);
   syst_no_smearing_final_fit_exp_FULL->GetXaxis()->SetTitleFont(43);
   syst_no_smearing_final_fit_exp_FULL->GetYaxis()->SetNdivisions(506);
   syst_no_smearing_final_fit_exp_FULL->GetYaxis()->SetLabelFont(43);
   syst_no_smearing_final_fit_exp_FULL->GetYaxis()->SetLabelSize(24);
   syst_no_smearing_final_fit_exp_FULL->GetYaxis()->SetTitleSize(24);
   syst_no_smearing_final_fit_exp_FULL->GetYaxis()->SetTitleOffset(2.8);
   syst_no_smearing_final_fit_exp_FULL->GetYaxis()->SetTitleFont(43);
   syst_no_smearing_final_fit_exp_FULL->SetParameter(0,1.8746);
   syst_no_smearing_final_fit_exp_FULL->SetParError(0,0);
   syst_no_smearing_final_fit_exp_FULL->SetParLimits(0,0,0);
   syst_no_smearing_final_fit_exp_FULL->SetParameter(1,-0.01869492);
   syst_no_smearing_final_fit_exp_FULL->SetParError(1,0);
   syst_no_smearing_final_fit_exp_FULL->SetParLimits(1,0,0);
   syst_no_smearing_final_fit_exp_FULL->Draw("same");
   
   TF1 *syst_no_smearing_final_fit_exp_LEFT = new TF1("*syst_no_smearing_final_fit_exp_LEFT",10,12,2);
    //The original function : exp_exclude_1216 had originally been created by:
    //TF1 *syst_no_smearing_final_fit_exp_LEFT = new TF1("syst_no_smearing_final_fit_exp_LEFT",exp_exclude_1216,10,12,2);
   syst_no_smearing_final_fit_exp_LEFT->SetRange(10,12);
   syst_no_smearing_final_fit_exp_LEFT->SetName("syst_no_smearing_final_fit_exp_LEFT");
   syst_no_smearing_final_fit_exp_LEFT->SetTitle("exp_exclude_1216");
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(0,5.406762);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(1,5.404741);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(2,5.40272);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(3,5.400701);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(4,5.398682);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(5,5.396664);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(6,5.394646);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(7,5.39263);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(8,5.390614);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(9,5.388598);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(10,5.386584);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(11,5.38457);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(12,5.382558);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(13,5.380545);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(14,5.378534);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(15,5.376523);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(16,5.374513);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(17,5.372504);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(18,5.370496);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(19,5.368488);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(20,5.366481);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(21,5.364475);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(22,5.36247);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(23,5.360465);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(24,5.358461);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(25,5.356458);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(26,5.354456);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(27,5.352454);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(28,5.350453);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(29,5.348453);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(30,5.346454);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(31,5.344455);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(32,5.342457);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(33,5.34046);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(34,5.338463);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(35,5.336468);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(36,5.334473);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(37,5.332479);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(38,5.330485);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(39,5.328493);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(40,5.326501);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(41,5.324509);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(42,5.322519);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(43,5.320529);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(44,5.31854);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(45,5.316552);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(46,5.314565);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(47,5.312578);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(48,5.310592);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(49,5.308607);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(50,5.306622);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(51,5.304638);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(52,5.302655);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(53,5.300673);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(54,5.298691);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(55,5.296711);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(56,5.294731);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(57,5.292751);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(58,5.290773);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(59,5.288795);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(60,5.286818);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(61,5.284841);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(62,5.282866);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(63,5.280891);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(64,5.278917);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(65,5.276943);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(66,5.274971);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(67,5.272999);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(68,5.271028);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(69,5.269057);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(70,5.267087);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(71,5.265118);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(72,5.26315);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(73,5.261183);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(74,5.259216);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(75,5.25725);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(76,5.255284);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(77,5.25332);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(78,5.251356);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(79,5.249393);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(80,5.247431);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(81,5.245469);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(82,5.243508);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(83,5.241548);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(84,5.239588);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(85,5.23763);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(86,5.235672);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(87,5.233714);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(88,5.231758);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(89,5.229802);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(90,5.227847);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(91,5.225893);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(92,5.223939);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(93,5.221986);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(94,5.220034);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(95,5.218083);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(96,5.216132);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(97,5.214182);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(98,5.212233);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(99,5.210285);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(100,5.208337);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(101,10);
   syst_no_smearing_final_fit_exp_LEFT->SetSavedPoint(102,12);
   syst_no_smearing_final_fit_exp_LEFT->SetFillStyle(0);
   syst_no_smearing_final_fit_exp_LEFT->SetLineWidth(1);
   syst_no_smearing_final_fit_exp_LEFT->GetXaxis()->SetNdivisions(506);
   syst_no_smearing_final_fit_exp_LEFT->GetXaxis()->SetLabelFont(43);
   syst_no_smearing_final_fit_exp_LEFT->GetXaxis()->SetLabelSize(24);
   syst_no_smearing_final_fit_exp_LEFT->GetXaxis()->SetTitleSize(24);
   syst_no_smearing_final_fit_exp_LEFT->GetXaxis()->SetTitleOffset(2.3);
   syst_no_smearing_final_fit_exp_LEFT->GetXaxis()->SetTitleFont(43);
   syst_no_smearing_final_fit_exp_LEFT->GetYaxis()->SetNdivisions(506);
   syst_no_smearing_final_fit_exp_LEFT->GetYaxis()->SetLabelFont(43);
   syst_no_smearing_final_fit_exp_LEFT->GetYaxis()->SetLabelSize(24);
   syst_no_smearing_final_fit_exp_LEFT->GetYaxis()->SetTitleSize(24);
   syst_no_smearing_final_fit_exp_LEFT->GetYaxis()->SetTitleOffset(2.8);
   syst_no_smearing_final_fit_exp_LEFT->GetYaxis()->SetTitleFont(43);
   syst_no_smearing_final_fit_exp_LEFT->SetParameter(0,1.8746);
   syst_no_smearing_final_fit_exp_LEFT->SetParError(0,0);
   syst_no_smearing_final_fit_exp_LEFT->SetParLimits(0,0,0);
   syst_no_smearing_final_fit_exp_LEFT->SetParameter(1,-0.01869492);
   syst_no_smearing_final_fit_exp_LEFT->SetParError(1,0);
   syst_no_smearing_final_fit_exp_LEFT->SetParLimits(1,0,0);
   syst_no_smearing_final_fit_exp_LEFT->Draw("same");
   
   TF1 *syst_no_smearing_final_fit_exp_RIGHT = new TF1("*syst_no_smearing_final_fit_exp_RIGHT",16,60,2);
    //The original function : exp_exclude_1216 had originally been created by:
    //TF1 *syst_no_smearing_final_fit_exp_RIGHT = new TF1("syst_no_smearing_final_fit_exp_RIGHT",exp_exclude_1216,16,60,2);
   syst_no_smearing_final_fit_exp_RIGHT->SetRange(16,60);
   syst_no_smearing_final_fit_exp_RIGHT->SetName("syst_no_smearing_final_fit_exp_RIGHT");
   syst_no_smearing_final_fit_exp_RIGHT->SetTitle("exp_exclude_1216");
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(0,4.833065);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(1,4.793473);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(2,4.754204);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(3,4.715258);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(4,4.67663);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(5,4.638319);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(6,4.600322);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(7,4.562636);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(8,4.525259);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(9,4.488188);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(10,4.45142);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(11,4.414954);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(12,4.378787);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(13,4.342916);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(14,4.307338);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(15,4.272053);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(16,4.237056);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(17,4.202346);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(18,4.16792);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(19,4.133776);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(20,4.099912);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(21,4.066326);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(22,4.033014);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(23,3.999976);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(24,3.967208);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(25,3.934708);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(26,3.902475);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(27,3.870506);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(28,3.838799);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(29,3.807351);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(30,3.776161);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(31,3.745227);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(32,3.714546);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(33,3.684116);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(34,3.653936);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(35,3.624002);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(36,3.594315);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(37,3.56487);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(38,3.535666);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(39,3.506702);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(40,3.477975);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(41,3.449483);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(42,3.421225);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(43,3.393198);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(44,3.365401);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(45,3.337832);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(46,3.310488);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(47,3.283369);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(48,3.256471);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(49,3.229794);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(50,3.203335);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(51,3.177094);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(52,3.151067);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(53,3.125253);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(54,3.099651);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(55,3.074259);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(56,3.049074);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(57,3.024096);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(58,2.999323);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(59,2.974752);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(60,2.950383);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(61,2.926213);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(62,2.902242);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(63,2.878466);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(64,2.854886);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(65,2.831499);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(66,2.808303);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(67,2.785297);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(68,2.76248);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(69,2.73985);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(70,2.717405);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(71,2.695144);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(72,2.673065);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(73,2.651167);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(74,2.629449);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(75,2.607908);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(76,2.586544);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(77,2.565355);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(78,2.54434);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(79,2.523496);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(80,2.502824);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(81,2.482321);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(82,2.461985);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(83,2.441817);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(84,2.421813);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(85,2.401974);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(86,2.382297);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(87,2.362781);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(88,2.343425);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(89,2.324227);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(90,2.305187);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(91,2.286303);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(92,2.267574);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(93,2.248998);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(94,2.230574);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(95,2.212301);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(96,2.194178);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(97,2.176203);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(98,2.158375);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(99,2.140694);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(100,2.123157);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(101,16);
   syst_no_smearing_final_fit_exp_RIGHT->SetSavedPoint(102,60);
   syst_no_smearing_final_fit_exp_RIGHT->SetFillStyle(0);
   syst_no_smearing_final_fit_exp_RIGHT->SetLineWidth(1);
   syst_no_smearing_final_fit_exp_RIGHT->GetXaxis()->SetNdivisions(506);
   syst_no_smearing_final_fit_exp_RIGHT->GetXaxis()->SetLabelFont(43);
   syst_no_smearing_final_fit_exp_RIGHT->GetXaxis()->SetLabelSize(24);
   syst_no_smearing_final_fit_exp_RIGHT->GetXaxis()->SetTitleSize(24);
   syst_no_smearing_final_fit_exp_RIGHT->GetXaxis()->SetTitleOffset(2.3);
   syst_no_smearing_final_fit_exp_RIGHT->GetXaxis()->SetTitleFont(43);
   syst_no_smearing_final_fit_exp_RIGHT->GetYaxis()->SetNdivisions(506);
   syst_no_smearing_final_fit_exp_RIGHT->GetYaxis()->SetLabelFont(43);
   syst_no_smearing_final_fit_exp_RIGHT->GetYaxis()->SetLabelSize(24);
   syst_no_smearing_final_fit_exp_RIGHT->GetYaxis()->SetTitleSize(24);
   syst_no_smearing_final_fit_exp_RIGHT->GetYaxis()->SetTitleOffset(2.8);
   syst_no_smearing_final_fit_exp_RIGHT->GetYaxis()->SetTitleFont(43);
   syst_no_smearing_final_fit_exp_RIGHT->SetParameter(0,1.8746);
   syst_no_smearing_final_fit_exp_RIGHT->SetParError(0,0);
   syst_no_smearing_final_fit_exp_RIGHT->SetParLimits(0,0,0);
   syst_no_smearing_final_fit_exp_RIGHT->SetParameter(1,-0.01869492);
   syst_no_smearing_final_fit_exp_RIGHT->SetParError(1,0);
   syst_no_smearing_final_fit_exp_RIGHT->SetParLimits(1,0,0);
   syst_no_smearing_final_fit_exp_RIGHT->Draw("same");
   
   leg = new TLegend(0.18,0.755,0.57,0.855,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(18);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("syst_no_smearing_final_fit_exp","Exp. fit (10, 60) excl. (12, 16) GeV/#it{c}","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("NULL","#chi^{2}/ndf = 0.178","");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   leg->Draw();
      tex = new TLatex(0.19,0.885,"No MC tuning");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__64 = new TH1F("hframe__64","",1000,8,62);
   hframe__64->SetMinimum(0);
   hframe__64->SetMaximum(10);
   hframe__64->SetDirectory(0);
   hframe__64->SetStats(0);
   hframe__64->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__64->GetXaxis()->SetNdivisions(506);
   hframe__64->GetXaxis()->SetLabelFont(43);
   hframe__64->GetXaxis()->SetLabelSize(24);
   hframe__64->GetXaxis()->SetTitleSize(24);
   hframe__64->GetXaxis()->SetTitleOffset(2.3);
   hframe__64->GetXaxis()->SetTitleFont(43);
   hframe__64->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__64->GetYaxis()->SetNdivisions(506);
   hframe__64->GetYaxis()->SetLabelFont(43);
   hframe__64->GetYaxis()->SetLabelSize(24);
   hframe__64->GetYaxis()->SetTitleSize(24);
   hframe__64->GetYaxis()->SetTitleOffset(2.8);
   hframe__64->GetYaxis()->SetTitleFont(43);
   hframe__64->GetZaxis()->SetLabelFont(43);
   hframe__64->GetZaxis()->SetLabelSize(24);
   hframe__64->GetZaxis()->SetTitleOffset(1.1);
   hframe__64->GetZaxis()->SetTitleFont(43);
   hframe__64->Draw("sameaxis");
   c_cross_section_smoothing_check_4->Modified();
   c_cross_section_smoothing_check->cd();
  
// ------------>Primitives in pad: c_cross_section_smoothing_check_5
   c_cross_section_smoothing_check_5 = new TPad("c_cross_section_smoothing_check_5", "c_cross_section_smoothing_check_5",0.3383333,0.001,0.6616667,0.499);
   c_cross_section_smoothing_check_5->Draw();
   c_cross_section_smoothing_check_5->cd();
   c_cross_section_smoothing_check_5->Range(-0.7831331,-1.47929,64.27711,10.35503);
   c_cross_section_smoothing_check_5->SetFillColor(10);
   c_cross_section_smoothing_check_5->SetBorderMode(0);
   c_cross_section_smoothing_check_5->SetBorderSize(2);
   c_cross_section_smoothing_check_5->SetTickx(1);
   c_cross_section_smoothing_check_5->SetTicky(1);
   c_cross_section_smoothing_check_5->SetLeftMargin(0.135);
   c_cross_section_smoothing_check_5->SetRightMargin(0.035);
   c_cross_section_smoothing_check_5->SetTopMargin(0.03);
   c_cross_section_smoothing_check_5->SetBottomMargin(0.125);
   c_cross_section_smoothing_check_5->SetFrameFillColor(0);
   c_cross_section_smoothing_check_5->SetFrameBorderMode(0);
   c_cross_section_smoothing_check_5->SetFrameFillColor(0);
   c_cross_section_smoothing_check_5->SetFrameBorderMode(0);
   
   TH1F *hframe__65 = new TH1F("hframe__65","",1000,8,62);
   hframe__65->SetMinimum(0);
   hframe__65->SetMaximum(10);
   hframe__65->SetDirectory(0);
   hframe__65->SetStats(0);
   hframe__65->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__65->GetXaxis()->SetNdivisions(506);
   hframe__65->GetXaxis()->SetLabelFont(43);
   hframe__65->GetXaxis()->SetLabelSize(24);
   hframe__65->GetXaxis()->SetTitleSize(24);
   hframe__65->GetXaxis()->SetTitleOffset(2.3);
   hframe__65->GetXaxis()->SetTitleFont(43);
   hframe__65->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__65->GetYaxis()->SetNdivisions(506);
   hframe__65->GetYaxis()->SetLabelFont(43);
   hframe__65->GetYaxis()->SetLabelSize(24);
   hframe__65->GetYaxis()->SetTitleSize(24);
   hframe__65->GetYaxis()->SetTitleOffset(2.8);
   hframe__65->GetYaxis()->SetTitleFont(43);
   hframe__65->GetZaxis()->SetLabelFont(43);
   hframe__65->GetZaxis()->SetLabelSize(24);
   hframe__65->GetZaxis()->SetTitleOffset(1.1);
   hframe__65->GetZaxis()->SetTitleFont(43);
   hframe__65->Draw(" ");
   Double_t xAxis21[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_CPV = new TH1D("syst_CPV","",9, xAxis21);
   syst_CPV->SetBinContent(1,3.488669);
   syst_CPV->SetBinContent(2,3.205749);
   syst_CPV->SetBinContent(3,3.252469);
   syst_CPV->SetBinContent(4,0.8280857);
   syst_CPV->SetBinContent(5,3.664913);
   syst_CPV->SetBinContent(6,5.879289);
   syst_CPV->SetBinContent(7,4.001062);
   syst_CPV->SetBinContent(8,1.929963);
   syst_CPV->SetBinContent(9,5.844539);
   syst_CPV->SetBinError(1,3.39452);
   syst_CPV->SetBinError(2,2.134427);
   syst_CPV->SetBinError(3,1.927392);
   syst_CPV->SetBinError(4,1.430787);
   syst_CPV->SetBinError(5,3.67976);
   syst_CPV->SetBinError(6,3.096768);
   syst_CPV->SetBinError(7,3.059548);
   syst_CPV->SetBinError(8,5.949176);
   syst_CPV->SetBinError(9,14.60479);
   syst_CPV->SetEntries(9);

   ci = TColor::GetColor("#cc6666");
   syst_CPV->SetFillColor(ci);
   syst_CPV->SetFillStyle(0);

   ci = TColor::GetColor("#cc6666");
   syst_CPV->SetLineColor(ci);

   ci = TColor::GetColor("#cc6666");
   syst_CPV->SetMarkerColor(ci);
   syst_CPV->SetMarkerStyle(24);
   syst_CPV->SetMarkerSize(1.1);
   syst_CPV->GetXaxis()->SetLabelFont(42);
   syst_CPV->GetXaxis()->SetLabelSize(0.035);
   syst_CPV->GetXaxis()->SetTitleSize(0.035);
   syst_CPV->GetXaxis()->SetTitleFont(42);
   syst_CPV->GetYaxis()->SetLabelFont(42);
   syst_CPV->GetYaxis()->SetLabelSize(0.035);
   syst_CPV->GetYaxis()->SetTitleSize(0.035);
   syst_CPV->GetYaxis()->SetTitleFont(42);
   syst_CPV->GetZaxis()->SetLabelFont(42);
   syst_CPV->GetZaxis()->SetLabelSize(0.035);
   syst_CPV->GetZaxis()->SetTitleSize(0.035);
   syst_CPV->GetZaxis()->SetTitleFont(42);
   syst_CPV->Draw("CPsame");
   
   leg = new TLegend(0.18,0.755,0.57,0.855,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(18);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("syst_CPV_fit_pol1","Lin. fit (10, 60) GeV/#it{c}","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("NULL","#chi^{2}/ndf = 0.445","");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   leg->Draw();
      tex = new TLatex(0.19,0.885,"CPV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__66 = new TH1F("hframe__66","",1000,8,62);
   hframe__66->SetMinimum(0);
   hframe__66->SetMaximum(10);
   hframe__66->SetDirectory(0);
   hframe__66->SetStats(0);
   hframe__66->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__66->GetXaxis()->SetNdivisions(506);
   hframe__66->GetXaxis()->SetLabelFont(43);
   hframe__66->GetXaxis()->SetLabelSize(24);
   hframe__66->GetXaxis()->SetTitleSize(24);
   hframe__66->GetXaxis()->SetTitleOffset(2.3);
   hframe__66->GetXaxis()->SetTitleFont(43);
   hframe__66->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__66->GetYaxis()->SetNdivisions(506);
   hframe__66->GetYaxis()->SetLabelFont(43);
   hframe__66->GetYaxis()->SetLabelSize(24);
   hframe__66->GetYaxis()->SetTitleSize(24);
   hframe__66->GetYaxis()->SetTitleOffset(2.8);
   hframe__66->GetYaxis()->SetTitleFont(43);
   hframe__66->GetZaxis()->SetLabelFont(43);
   hframe__66->GetZaxis()->SetLabelSize(24);
   hframe__66->GetZaxis()->SetTitleOffset(1.1);
   hframe__66->GetZaxis()->SetTitleFont(43);
   hframe__66->Draw("sameaxis");
   c_cross_section_smoothing_check_5->Modified();
   c_cross_section_smoothing_check->cd();
  
// ------------>Primitives in pad: c_cross_section_smoothing_check_6
   c_cross_section_smoothing_check_6 = new TPad("c_cross_section_smoothing_check_6", "c_cross_section_smoothing_check_6",0.6716667,0.001,0.995,0.499);
   c_cross_section_smoothing_check_6->Draw();
   c_cross_section_smoothing_check_6->cd();
   c_cross_section_smoothing_check_6->Range(-0.7831331,-8.875739,64.27711,62.13018);
   c_cross_section_smoothing_check_6->SetFillColor(10);
   c_cross_section_smoothing_check_6->SetBorderMode(0);
   c_cross_section_smoothing_check_6->SetBorderSize(2);
   c_cross_section_smoothing_check_6->SetTickx(1);
   c_cross_section_smoothing_check_6->SetTicky(1);
   c_cross_section_smoothing_check_6->SetLeftMargin(0.135);
   c_cross_section_smoothing_check_6->SetRightMargin(0.035);
   c_cross_section_smoothing_check_6->SetTopMargin(0.03);
   c_cross_section_smoothing_check_6->SetBottomMargin(0.125);
   c_cross_section_smoothing_check_6->SetFrameFillColor(0);
   c_cross_section_smoothing_check_6->SetFrameBorderMode(0);
   c_cross_section_smoothing_check_6->SetFrameFillColor(0);
   c_cross_section_smoothing_check_6->SetFrameBorderMode(0);
   
   TH1F *hframe__67 = new TH1F("hframe__67","",1000,8,62);
   hframe__67->SetMinimum(0);
   hframe__67->SetMaximum(60);
   hframe__67->SetDirectory(0);
   hframe__67->SetStats(0);
   hframe__67->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__67->GetXaxis()->SetNdivisions(506);
   hframe__67->GetXaxis()->SetLabelFont(43);
   hframe__67->GetXaxis()->SetLabelSize(24);
   hframe__67->GetXaxis()->SetTitleSize(24);
   hframe__67->GetXaxis()->SetTitleOffset(2.3);
   hframe__67->GetXaxis()->SetTitleFont(43);
   hframe__67->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__67->GetYaxis()->SetNdivisions(506);
   hframe__67->GetYaxis()->SetLabelFont(43);
   hframe__67->GetYaxis()->SetLabelSize(24);
   hframe__67->GetYaxis()->SetTitleSize(24);
   hframe__67->GetYaxis()->SetTitleOffset(2.8);
   hframe__67->GetYaxis()->SetTitleFont(43);
   hframe__67->GetZaxis()->SetLabelFont(43);
   hframe__67->GetZaxis()->SetLabelSize(24);
   hframe__67->GetZaxis()->SetTitleOffset(1.1);
   hframe__67->GetZaxis()->SetTitleFont(43);
   hframe__67->Draw(" ");
   Double_t xAxis22[10] = {10, 12, 14, 16, 18, 20, 25, 30, 40, 60}; 
   
   TH1D *syst_combined_iso_prob = new TH1D("syst_combined_iso_prob","",9, xAxis22);
   syst_combined_iso_prob->SetBinContent(1,21.12044);
   syst_combined_iso_prob->SetBinContent(2,14.88375);
   syst_combined_iso_prob->SetBinContent(3,14.36753);
   syst_combined_iso_prob->SetBinContent(4,17.87723);
   syst_combined_iso_prob->SetBinContent(5,12.20418);
   syst_combined_iso_prob->SetBinContent(6,9.809003);
   syst_combined_iso_prob->SetBinContent(7,15.56078);
   syst_combined_iso_prob->SetBinContent(8,19.14352);
   syst_combined_iso_prob->SetBinContent(9,14.65654);
   syst_combined_iso_prob->SetBinError(1,7.767883);
   syst_combined_iso_prob->SetBinError(2,5.026011);
   syst_combined_iso_prob->SetBinError(3,5.185451);
   syst_combined_iso_prob->SetBinError(4,6.657629);
   syst_combined_iso_prob->SetBinError(5,4.54424);
   syst_combined_iso_prob->SetBinError(6,3.655449);
   syst_combined_iso_prob->SetBinError(7,5.785489);
   syst_combined_iso_prob->SetBinError(8,7.122251);
   syst_combined_iso_prob->SetBinError(9,5.459367);
   syst_combined_iso_prob->SetEntries(9);

   ci = TColor::GetColor("#ff9900");
   syst_combined_iso_prob->SetFillColor(ci);
   syst_combined_iso_prob->SetFillStyle(0);

   ci = TColor::GetColor("#ff9900");
   syst_combined_iso_prob->SetLineColor(ci);

   ci = TColor::GetColor("#ff9900");
   syst_combined_iso_prob->SetMarkerColor(ci);
   syst_combined_iso_prob->SetMarkerStyle(24);
   syst_combined_iso_prob->SetMarkerSize(1.1);
   syst_combined_iso_prob->GetXaxis()->SetLabelFont(42);
   syst_combined_iso_prob->GetXaxis()->SetLabelSize(0.035);
   syst_combined_iso_prob->GetXaxis()->SetTitleSize(0.035);
   syst_combined_iso_prob->GetXaxis()->SetTitleFont(42);
   syst_combined_iso_prob->GetYaxis()->SetLabelFont(42);
   syst_combined_iso_prob->GetYaxis()->SetLabelSize(0.035);
   syst_combined_iso_prob->GetYaxis()->SetTitleSize(0.035);
   syst_combined_iso_prob->GetYaxis()->SetTitleFont(42);
   syst_combined_iso_prob->GetZaxis()->SetLabelFont(42);
   syst_combined_iso_prob->GetZaxis()->SetLabelSize(0.035);
   syst_combined_iso_prob->GetZaxis()->SetTitleSize(0.035);
   syst_combined_iso_prob->GetZaxis()->SetTitleFont(42);
   syst_combined_iso_prob->Draw("EPsame");
   
   TF1 *syst_combined_iso_prob_fit_lin_cst_FULL = new TF1("*syst_combined_iso_prob_fit_lin_cst_FULL",10,60,3);
    //The original function : iso_prob_lin_cst_fit_FULL had originally been created by:
    //TF1 *syst_combined_iso_prob_fit_lin_cst_FULL = new TF1("syst_combined_iso_prob_fit_lin_cst_FULL",iso_prob_lin_cst_fit_FULL,10,60,3);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetRange(10,60);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetName("syst_combined_iso_prob_fit_lin_cst_FULL");
   syst_combined_iso_prob_fit_lin_cst_FULL->SetTitle("iso_prob_lin_cst_fit_FULL");
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(0,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(1,21.6777);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(2,21.12044);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(3,20.56317);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(4,20.0059);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(5,19.44864);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(6,18.89137);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(7,18.3341);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(8,17.77684);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(9,17.21957);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(10,16.66231);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(11,16.10504);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(12,15.54777);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(13,14.99051);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(14,14.43324);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(15,13.87597);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(16,13.31871);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(17,12.76144);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(18,12.20418);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(19,11.64691);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(20,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(21,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(22,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(23,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(24,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(25,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(26,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(27,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(28,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(29,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(30,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(31,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(32,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(33,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(34,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(35,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(36,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(37,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(38,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(39,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(40,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(41,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(42,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(43,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(44,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(45,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(46,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(47,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(48,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(49,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(50,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(51,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(52,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(53,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(54,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(55,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(56,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(57,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(58,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(59,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(60,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(61,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(62,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(63,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(64,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(65,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(66,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(67,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(68,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(69,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(70,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(71,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(72,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(73,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(74,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(75,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(76,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(77,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(78,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(79,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(80,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(81,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(82,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(83,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(84,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(85,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(86,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(87,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(88,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(89,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(90,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(91,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(92,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(93,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(94,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(95,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(96,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(97,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(98,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(99,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(100,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(101,10);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetSavedPoint(102,60);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetFillStyle(0);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetLineWidth(1);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetLineStyle(2);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetXaxis()->SetNdivisions(506);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetXaxis()->SetLabelFont(43);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetXaxis()->SetLabelSize(24);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetXaxis()->SetTitleSize(24);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetXaxis()->SetTitleOffset(2.3);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetXaxis()->SetTitleFont(43);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetYaxis()->SetNdivisions(506);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetYaxis()->SetLabelFont(43);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetYaxis()->SetLabelSize(24);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetYaxis()->SetTitleSize(24);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetYaxis()->SetTitleOffset(2.8);
   syst_combined_iso_prob_fit_lin_cst_FULL->GetYaxis()->SetTitleFont(43);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetParameter(0,33.38029);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetParError(0,0);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetParLimits(0,0,0);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetParameter(1,-1.114533);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetParError(1,0);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetParLimits(1,0,0);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetParameter(2,13.09109);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetParError(2,0);
   syst_combined_iso_prob_fit_lin_cst_FULL->SetParLimits(2,0,0);
   syst_combined_iso_prob_fit_lin_cst_FULL->Draw("same");
   
   TF1 *syst_combined_iso_prob_fit_lin_cst_LEFT = new TF1("*syst_combined_iso_prob_fit_lin_cst_LEFT",10,12,3);
    //The original function : iso_prob_lin_cst_fit had originally been created by:
    //TF1 *syst_combined_iso_prob_fit_lin_cst_LEFT = new TF1("syst_combined_iso_prob_fit_lin_cst_LEFT",iso_prob_lin_cst_fit,10,12,3);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetRange(10,12);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetName("syst_combined_iso_prob_fit_lin_cst_LEFT");
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetTitle("iso_prob_lin_cst_fit");
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(0,13.09109);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(1,22.21268);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(2,22.19039);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(3,22.1681);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(4,22.14581);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(5,22.12352);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(6,22.10122);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(7,22.07893);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(8,22.05664);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(9,22.03435);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(10,22.01206);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(11,21.98977);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(12,21.96748);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(13,21.94519);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(14,21.9229);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(15,21.90061);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(16,21.87832);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(17,21.85603);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(18,21.83374);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(19,21.81145);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(20,21.78916);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(21,21.76686);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(22,21.74457);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(23,21.72228);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(24,21.69999);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(25,21.6777);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(26,21.65541);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(27,21.63312);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(28,21.61083);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(29,21.58854);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(30,21.56625);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(31,21.54396);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(32,21.52167);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(33,21.49938);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(34,21.47709);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(35,21.4548);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(36,21.43251);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(37,21.41021);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(38,21.38792);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(39,21.36563);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(40,21.34334);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(41,21.32105);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(42,21.29876);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(43,21.27647);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(44,21.25418);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(45,21.23189);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(46,21.2096);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(47,21.18731);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(48,21.16502);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(49,21.14273);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(50,21.12044);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(51,21.09815);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(52,21.07585);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(53,21.05356);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(54,21.03127);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(55,21.00898);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(56,20.98669);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(57,20.9644);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(58,20.94211);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(59,20.91982);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(60,20.89753);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(61,20.87524);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(62,20.85295);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(63,20.83066);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(64,20.80837);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(65,20.78608);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(66,20.76379);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(67,20.74149);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(68,20.7192);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(69,20.69691);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(70,20.67462);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(71,20.65233);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(72,20.63004);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(73,20.60775);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(74,20.58546);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(75,20.56317);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(76,20.54088);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(77,20.51859);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(78,20.4963);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(79,20.47401);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(80,20.45172);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(81,20.42943);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(82,20.40714);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(83,20.38484);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(84,20.36255);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(85,20.34026);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(86,20.31797);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(87,20.29568);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(88,20.27339);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(89,20.2511);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(90,20.22881);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(91,20.20652);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(92,20.18423);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(93,20.16194);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(94,20.13965);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(95,20.11736);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(96,20.09507);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(97,20.07278);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(98,20.05048);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(99,20.02819);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(100,20.0059);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(101,10);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetSavedPoint(102,12);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetFillStyle(0);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetLineWidth(1);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetXaxis()->SetNdivisions(506);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetXaxis()->SetLabelFont(43);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetXaxis()->SetLabelSize(24);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetXaxis()->SetTitleSize(24);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetXaxis()->SetTitleOffset(2.3);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetXaxis()->SetTitleFont(43);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetYaxis()->SetNdivisions(506);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetYaxis()->SetLabelFont(43);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetYaxis()->SetLabelSize(24);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetYaxis()->SetTitleSize(24);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetYaxis()->SetTitleOffset(2.8);
   syst_combined_iso_prob_fit_lin_cst_LEFT->GetYaxis()->SetTitleFont(43);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetParameter(0,33.38029);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetParError(0,0);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetParLimits(0,0,0);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetParameter(1,-1.114533);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetParError(1,0);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetParLimits(1,0,0);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetParameter(2,13.09109);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetParError(2,0);
   syst_combined_iso_prob_fit_lin_cst_LEFT->SetParLimits(2,0,0);
   syst_combined_iso_prob_fit_lin_cst_LEFT->Draw("same");
   
   TF1 *syst_combined_iso_prob_fit_lin_cst_RIGHT = new TF1("*syst_combined_iso_prob_fit_lin_cst_RIGHT",18,60,3);
    //The original function : iso_prob_lin_cst_fit had originally been created by:
    //TF1 *syst_combined_iso_prob_fit_lin_cst_RIGHT = new TF1("syst_combined_iso_prob_fit_lin_cst_RIGHT",iso_prob_lin_cst_fit,18,60,3);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetRange(18,60);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetName("syst_combined_iso_prob_fit_lin_cst_RIGHT");
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetTitle("iso_prob_lin_cst_fit");
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(0,13.31871);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(1,12.8506);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(2,12.3825);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(3,11.9144);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(4,11.44629);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(5,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(6,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(7,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(8,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(9,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(10,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(11,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(12,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(13,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(14,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(15,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(16,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(17,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(18,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(19,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(20,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(21,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(22,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(23,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(24,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(25,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(26,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(27,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(28,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(29,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(30,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(31,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(32,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(33,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(34,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(35,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(36,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(37,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(38,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(39,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(40,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(41,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(42,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(43,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(44,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(45,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(46,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(47,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(48,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(49,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(50,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(51,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(52,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(53,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(54,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(55,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(56,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(57,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(58,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(59,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(60,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(61,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(62,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(63,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(64,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(65,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(66,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(67,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(68,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(69,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(70,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(71,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(72,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(73,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(74,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(75,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(76,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(77,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(78,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(79,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(80,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(81,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(82,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(83,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(84,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(85,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(86,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(87,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(88,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(89,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(90,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(91,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(92,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(93,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(94,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(95,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(96,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(97,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(98,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(99,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(100,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(101,18);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetSavedPoint(102,60);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetFillStyle(0);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetLineWidth(1);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetXaxis()->SetNdivisions(506);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetXaxis()->SetLabelFont(43);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetXaxis()->SetLabelSize(24);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetXaxis()->SetTitleSize(24);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetXaxis()->SetTitleOffset(2.3);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetXaxis()->SetTitleFont(43);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetYaxis()->SetNdivisions(506);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetYaxis()->SetLabelFont(43);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetYaxis()->SetLabelSize(24);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetYaxis()->SetTitleSize(24);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetYaxis()->SetTitleOffset(2.8);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->GetYaxis()->SetTitleFont(43);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetParameter(0,33.38029);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetParError(0,0);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetParLimits(0,0,0);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetParameter(1,-1.114533);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetParError(1,0);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetParLimits(1,0,0);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetParameter(2,13.09109);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetParError(2,0);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->SetParLimits(2,0,0);
   syst_combined_iso_prob_fit_lin_cst_RIGHT->Draw("same");
   
   leg = new TLegend(-2.353437e-185,-2.353437e-185,-2.353437e-185,-2.353437e-185,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(18);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("syst_combined_iso_prob_fit_lin_cst","Lin. + const. fit (10, 60) excl. (12, 18) GeV/#it{c}","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("NULL","#chi^{2}/ndf = 0.598","");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
      tex = new TLatex(0.19,0.885,"Iso. probability");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hframe__68 = new TH1F("hframe__68","",1000,8,62);
   hframe__68->SetMinimum(0);
   hframe__68->SetMaximum(60);
   hframe__68->SetDirectory(0);
   hframe__68->SetStats(0);
   hframe__68->GetXaxis()->SetTitle("#it{p}_{T} (GeV/#it{c})");
   hframe__68->GetXaxis()->SetNdivisions(506);
   hframe__68->GetXaxis()->SetLabelFont(43);
   hframe__68->GetXaxis()->SetLabelSize(24);
   hframe__68->GetXaxis()->SetTitleSize(24);
   hframe__68->GetXaxis()->SetTitleOffset(2.3);
   hframe__68->GetXaxis()->SetTitleFont(43);
   hframe__68->GetYaxis()->SetTitle("Syst. Unc. (%)");
   hframe__68->GetYaxis()->SetNdivisions(506);
   hframe__68->GetYaxis()->SetLabelFont(43);
   hframe__68->GetYaxis()->SetLabelSize(24);
   hframe__68->GetYaxis()->SetTitleSize(24);
   hframe__68->GetYaxis()->SetTitleOffset(2.8);
   hframe__68->GetYaxis()->SetTitleFont(43);
   hframe__68->GetZaxis()->SetLabelFont(43);
   hframe__68->GetZaxis()->SetLabelSize(24);
   hframe__68->GetZaxis()->SetTitleOffset(1.1);
   hframe__68->GetZaxis()->SetTitleFont(43);
   hframe__68->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.1,0.935,0.85,0.985,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetTextFont(43);
   pt->SetTextSize(28);
   text = pt->AddText("iso_prob_lin_cst_fit");
   pt->Draw();
   c_cross_section_smoothing_check_6->Modified();
   c_cross_section_smoothing_check->cd();
   c_cross_section_smoothing_check->Modified();
   c_cross_section_smoothing_check->cd();
   c_cross_section_smoothing_check->SetSelected(c_cross_section_smoothing_check);
}
